### ISSUE TITLE
AudioBuffer copyFrom/To channel ambiguity

### ISSUE THREAD

**Issue by nickjillings** [WebAudio/web-audio-api#1004]
The function descriptions seem rather cryptic here as to what actually happens, especially if I only want to copy a portion of the buffer. Say I have a buffer of 2 channels, each 2048 samples long. If I do the following:

``` javascript
    var myBuffer = context.createAudioBuffer(2, 2048, context.sampleRate);
    var destination = new Float32Array(1024);
    myBuffer.copyFromChannel(destination, 0);
```

what should the behaviour be? Should I get an error because my buffer is not big enough or will it only copy the first 1024 samples (as I think it should).
Equally if the last line were `myBuffer.copyFromChannel(destination, 0, 2000)`, meaning only the last 48 samples are captured, would there be an error, fill the rest of the destination array with zeros, or completely ignore them.

The same issues exist in the copyToChannel.

The third argument is also strange, `startInChannel` doesn't immediately sound like an `offset`, even though that is what it is.

From the spec:

> When reading data from an AudioBuffer's channels, and the data can be processed in chunks, copyFromChannel should be preferred to calling getChannelData

it would seem that copyFromChannel can be used to access the buffer on a frame-by-frame basis but when handled in odd circumstances there is room for difference in the implementation.

**Comment by rtoy** [comment]
Yes, the spec should be a bit clearer on what should happen in these situations.

**Comment by rtoy** [comment]
Action item: Find out what browsers currently do.

**Comment by rtoy** [comment]
Wrote this really awful hack to test:  http://rtoy.github.io/webaudio-hacks/tests/copy-channel.html  You need to examine the console logs currently to see what's happening; I'll try to clean it up later so that the console log isn't needed.

Until then, Chrome doesn't throw any errors.  It just fills in the parts of the array that it can, leaving other parts untouched.  Firefox throws an error if the destination array for copyFromChannel is longer than the buffer. Edge behaves like Chrome. Safari doesn't support AudioContext (still prefixed), so I don't care.

I kind of like Chrome's behavior (but I'm biased because I wrote it).  Firefox's behavior is also ok with me, except that I find it strange that it only throws an error if the destination array is too long.

For me, just using the parts of the array is more useful.  Consider if I only want a part of a huge AudioBuffer.  I'd have to create a Float32Array of the same size even if I only wanted the first 5 samples.  Of course, I could use `getChannelData` in that case, but that has other implications.

**Comment by rtoy** [comment]
Proposal:  `copyFromChannel` and `copyToChannel` copies data until it runs out of data in either the source or the destination.  Elements that are not modified by the copy remain unchanged. No errors are signaled.

Thus for example above in https://github.com/WebAudio/web-audio-api/issues/1004#issue-179734476, only the first 1024 values of `myBuffer` are copied from `myBuffer` to `destination`.

Likewise, for the case `myBuffer.copyFromChannel(destination, 0, 2000)`, the last 48 samples from `myBuffer` are copied to `destination`; the other values in `destination` are untouched.

Similar idea holds for `copyToChannel`.

**Comment by rtoy** [comment]
Oh, and maybe rename `startInChannel` to `offset` or `startIndex`.  I always read `startInChannel` to refer to a channel number, not an index to a sample in the buffer.
