### ISSUE TITLE
Section 2.1.7 unclear about resuming a closed context

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1100]
In https://webaudio.github.io/web-audio-api/#system-resources-associated-with-an-audiocontext, the third paragraph says

> suspend and close allow authors to release system resources. Releasing system resources means releasing the system resources such as threads, processes, audio streams, but conserving the state of the AudioContext such that it can continue to operate later after resuming if needed.

The last sentence make no restrictions on resuming, but a closed AudioContext cannot be resumed.  We should make this explicit somehow.

**Comment by padenot** [comment]
On the algorithm that describes `resume`, [step 2](https://webaudio.github.io/web-audio-api/#widl-BaseAudioContext-resume-Promise-void):

> If the control thread state flag on the AudioContext is closed reject the promise with InvalidStateError, abort these steps, returning promise. 

To me, you can't resume a closed context, so the sentence "it can continue to operate later after resuming if needed." does not really apply because you can't reach the state "after resuming".

**Comment by rtoy** [comment]
Yes, but at that point in the text, you haven't reached the description of what resume does, and unless you look there first, I find the text still confusing because it looks like you can resume a closed context.
