### ISSUE TITLE
PeriodicWave constructor behavior is not defined

### ISSUE THREAD

**Issue by bzbarsky** [WebAudio/web-audio-api#1120]
There is no clear definition of how this constructor should behave.  This leads to problems like https://bugzilla.mozilla.org/show_bug.cgi?id=1324181 where it's totally unclear what should actually happen for various inputs.

**Comment by rtoy** [comment]
To resolve this issue, I think we need to say what happens if both `real` and `imag` are given but the lengths are different.  I think we have two options here:

1. It's an error, like for `createPeriodicWave`; both must have the same length
2. The shorter is zero-padded to have the same length as the longer.  This is a convenience.

I prefer the first, to make the behaviour consistent with the factor method.  The convenience factor isn't really compelling to me because if you need to specify both components, they very likely have to be the same length anyway to get all of the harmonics and phase that you want.

**Comment by padenot** [comment]
I agree with @rtoy.
