### ISSUE TITLE
MSE (+EME) does not enable accurate scheduling of playback from HTMLMediaElement

### ISSUE THREAD

**Issue by kirbysayshi** [WebAudio/web-audio-api#1148]
An example use case is a live DJ mixing tool:

- Audio Track A, tempo 115
- Audio Track B, tempo 115
- The user wants to trigger Track B to begin on the last beat of Track A (assuming the user knows where the last beat is in seconds).

Both tracks use EME, and thus cannot be decoded into AudioBuffer chunks. They must use `<audio>` tags, which only offers the `.play()` interface.

[As this jsfiddle shows](https://jsfiddle.net/k07v5vnn/latest), executing `.play` on two `<audio>` tags in the same tick does not guarantee that playback will begin in sync (although that test, due to how bare bones it is, does allow them to play ~10ms of each other in FF, chrome is a much more audible ~30ms. A real-world example including the actual EME decryption would be considerably more delayed. The promise interface also adds ~30ms).

MSE's `createMediaElementSource` (which is permitted in Chrome for EME `<audio>`) is the "bridge" between these two APIs, but does not provide an alternate scheduling interface for playback: the `<audio>` tag is still bound by the HTMLMediaElement interface, which has inconsistent timing (at least according to my tests).

Perhaps I'm missing a technique that allows accurate MSE playback scheduling?

**Comment by joeberkovitz** [comment]
Between EME and the need to unify media handling and web audio at an underlying architectural level, this is for v.next

**Comment by soulwire** [comment]
Here's a more complete demo to further illustrate @kirbysayshi's comments regarding the latency between calling `play()` and playback actually starting / the event or promise handler being called.

https://soulwire.github.io/eme-playback-test/

It's a simple sequencer, which attempts to synchronize playback of `HTMLMediaElement`s (via `MediaElementAudioSourceNode`s) and a precisely timed `OscillatorNode` that serves as a metronome. The samples use EME (Clear Key encrypted) and therefore can't be loaded into an `AudioBuffer`, which leaves the `HTMLMediaElement`'s `play` method as the only interface for requesting playback.

As demonstrated in the example, there's some variable latency between calling `play()` and receiving the `playing` event or the play promise resolving (this delay seems to be particularly severe in FF.)

Given the asynchronous nature of the JS event loop, I might expect some small discrepancy between playback starting and event handlers being called. However in this example the main thread isn't being taxed very much and often the delay is audible, suggesting that playback itself is (inconsistently) delayed. Network / streaming conditions shouldn't be a factor here either, since each `HTMLMediaElement` reports that it `canplaythrough` before actually being asked to play.

It's therefore very difficult to mitigate the effects of not having the `AudioScheduledSourceNode` interface when attempting precise and predictable playback of encrypted content.

**Comment by padenot** [comment]
This is not possible right now in the Web Audio API. `HTMLMediaElement` is not intended for precise, low-latency playback. We (Mozilla) tried making it so ages ago, but nobody cared and people said "we'll just use the Web Audio API". `HTMLMediaElement` has a different trade-off than the Web Audio API, it prefers saving CPU, memory and therefore battery instead of being very low-latency.

Also I don't quite understand why you would pipe EME content into the Web Audio API, given you can get the actual audio content without any loss using the Web Audio API regardless, but it's none of my business I suppose.

**Comment by rtoy** [comment]
I think the use case is that you have permission to stream someone else's content under the condition that it's encrypted.

**Comment by kirbysayshi** [comment]
> Also I don't quite understand why you would pipe EME content into the Web Audio API, given you can get the actual audio content without any loss using the Web Audio API regardless

@padenot do you know of a procedure to get the EME content accurately? As far as I know, the only technique is `createMediaElementSource` + scriptProcessorNode; but this approach is flawed since there is no way to know when the data flowing into the scriptProcessorNode is real yet slient audio, or 0-samples while waiting for the `HTMLMediaElement` to begin playing.

@rtoy yes, that is a very valid description of the use case.

**Comment by padenot** [comment]
> @padenot do you know of a procedure to get the EME content accurately? As far as I know, the only technique is createMediaElementSource + scriptProcessorNode; but this approach is flawed since there is no way to know when the data flowing into the scriptProcessorNode is real yet slient audio, or 0-samples while waiting for the HTMLMediaElement to begin playing.

[MediaRecorder](https://w3c.github.io/mediacapture-record/) +  [HTMLMediaElement.captureStream](https://w3c.github.io/mediacapture-fromelement/#dom-htmlmediaelement-capturestream()). No need for the Web Audio API here.

**Comment by joeberkovitz** [comment]
We don't think this is a Web Audio issue. Synchronizing HTMLMediaElements is an HTML issue https://github.com/whatwg/html/issues/192#event-657527751 which has been closed. Feels like this issue is really just asking for that one to be reopened, which could be lobbied for.
