### ISSUE TITLE
MediaElementAudioSourceNode and MediaStreamAudioSourceNode attributes

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1157]
Currently `MediaElementAudioSourceNode` and `MediaStreamAudioSourceNode` have no attributes.  However, Chrome actually defines readonly `mediaElement` and `mediaStream` attributes, respectively, for these nodes.  I don't think they're strictly necessary, but it certainly is nice to be able to introspect these nodes to be able to find what element or stream are associated with these nodes.

Should these be defined?

**Comment by foolip** [comment]
That would be great, especially if the connection is already trivially available internally in other implementations.

**Comment by foolip** [comment]
The change was reverted, should this be reopened?

**Comment by joeberkovitz** [comment]
Since I'm no longer sure what's happening here, I'm reassigning to the last person who touched this (@rtoy).

**Comment by rtoy** [comment]
I think the issue is that @padenot wanted the attributes for the different nodes to have the same name instead of different names as done in the PR.

Also, @foolip mentioned that the attributes should use `[SameObject]`.

**Comment by foolip** [comment]
These names go back to [2011](https://trac.webkit.org/changeset/93054/webkit)/[2012](https://trac.webkit.org/changeset/124255/webkit) and are in both Chromium and WebKit. Changing them would require that two engine change, so it would be *very* nice to keep the names. That also matches the names of the members in the init dicts. Pretty please?

**Comment by padenot** [comment]
Hrm, this is not great, but OK, I probably misread that this had already been shipped for a while.

Gecko will implement this with the same names as the other implementations.

If there are other weird things that are not in the spec, but implemented anyways, it would be great to know them, so that we can have a spec that actually reflects what is being shipped, and we can work to have compatible implementations.

**Comment by foolip** [comment]
> If there are other weird things that are not in the spec, but implemented anyways, it would be great to know them, so that we can have a spec that actually reflects what is being shipped, and we can work to have compatible implementations.

Indeed! This issue was filed in response to https://crbug.com/697137, which was found by @LoonyBean using early versions of tooling that @mdittmer is building to find exactly mismatches like this between Blink's IDL and the specs we claim the IDL is from.

There are two others for Web Audio, https://crbug.com/697123 and https://crbug.com/707338.
