### ISSUE TITLE
decodeAudioData detaches ArrayBuffer

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1175]
In https://webaudio.github.io/web-audio-api/#widl-BaseAudioContext-decodeAudioData-Promise-AudioBuffer--ArrayBuffer-audioData-DecodeSuccessCallback-successCallback-DecodeErrorCallback-errorCallback, the algorithm says that `ArrayBuffer` is detached.  My (limited) understanding of this is that once this happens, the contents of the `ArrayBuffer` is basically gone in Javascript.  You can't call `decodeAudioData` twice on the same `ArrayBuffer`, and you can't even look into the original contents.

Is this how `decodeAudioData` is expected to work?

(Noticed this when trying to implement in Chrome, where we have some tests that were calling `decodeAudioData` multiple times on the same buffer.)

**Comment by padenot** [comment]
Yes, this is how it's supposed to work. At the time (when we implemented it in Firefox), this broke some content but it's fine now, I haven't heard about a website not working because of this for a long time.

In practice, what happens is that you're giving away the content of the buffer to the decoding thread, because you can't have shared memory on the web today. Same for `AudioBufferSourceNode` or convolution impulses, etc.

When [`SharedArrayBuffer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer) (available for testing in pre-release version of Firefox), we can opt-in to support them in `decodeAudioData` and others, and we'll be able to save some memory in some use-cases.

**Comment by rtoy** [comment]
Excellent. Well, except for the unexpected inability to re-use the buffer, but that's working as intended, then.

Chrome has SharedArrayBuffer behind a bunch flags too.  Supporting that with decodeAudioData will probably be v.next. :-)

**Comment by bartread** [comment]
Can I, well, no, not "can I": I _am_ going to make an observation that this is _absolutely terrible_. This seems to be yet another situation where actual use cases of the web audio API have not been taken into account.

For example, I have some games that play three different pieces of music:

- Title screen
- In game
- Game over

These are fairly short 2-3 minute pieces of music but, even so, you're looking at multiple megabytes of data.

I used to just load them, and use decodeAudioData to decode them only once, and just reuse the decoded audio over and over again. This works great: it's really fast, there's no lag when you want to play some music (because you don't need to decode it again).

But there is one very big problem:

I noticed this in Chrome first but native memory usage in my games was sky high. Chrome Dev Tools is awesome but it's not good at teling you what's going on with native memroy, particularly, so I had to do some digging.

Of course, when I realised what the problem was it seemed blatantly obvious: it's the decoded audio which, of course, is *massive* - hundreds of megabytes. You can, to some extent, mitigate this by reducing the sample rate of your audio (note: not the encoding bitrate; that will make no difference) but, obviously, with music, it really starts to suffer if you drop below about 22KHz so you may not have that option.

The solution? Decode the audio only when you need it and throw it away when you're done. And this had been working great, right up until Chrome 59, and I see now the above error, and I've also noticed it happening in Firefox. (And this must have been happening for a while but I generally only play a game once to test so a second attempt is never made to play music.)

That hundreds of megabytes I mentioned is something you can probably get away with on a desktop (although it makes it look like your page is just terribly implemented when you look at it in, say, Chrome Task Manager), but it can certainly be problematic on mobile devices. The flipside is that because you decode the audio only once there's no lag and you don't chew the battery so much, but if your web page simply crashes due to memory usage that hardly matters.

So my options at this point are:

1) Go back to consuming hundreds of megabytes of native memory by reusing decoded audio.

2) Hope the mp3 files are still in the browser cache and go back to loading them every time I need to play them. This risks a cache miss and the cost (to the user, mainly) of pulling down the file again, or simply not being able to play the music if the device has lost connectivity.

3) Experiment with using the &lt;audio&gt; element for playing music (only) to see if it's any more memory efficient.

None of these options is particularly palatable.

Honestly, I hope whoever designed the Web Audio API is paying some attention to this, because there are some genuinely dreadful decisions that have been made in its specification. You've made it really hard to reuse objects and buffers, you've made it really hard to be efficient with memory, and you've made it really hard to play sound reliably. The first of these is problematic for any JS app hoping to achieve anything like real-time performance, and the second is problematic for mobile, which is where much web usage comes from nowadays.

People slagged Flash off for security holes, and it perhaps unfairly got a bad wrap because of poorly implemented sites that used it and swalled CPU cores whole, but it was *really good* at handling multimedia reliably. I don't get the feeling that the browser APIs, with which it is supposed to be replaced, are getting the same level of attention to detail.

Please: stop making bad assumptions about how people want to work with audio in the browser. What I want, what we all need, is not opinionation, but flexibility in the APIs.

Thanks for taking the time to read this.

**Comment by chrisguttandin** [comment]
Hi @bartread,

if you really need the old behavior you can use [ArrayBuffer.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/slice) to copy the ArrayBuffer before decoding it: `decodeAudioData(myArrayBuffer.slice(0))`.

Alternatively, you could use a [Service Worker](https://developer.mozilla.org/de/docs/Web/API/Service_Worker_API) to make sure the network requests to your mp3 files are cached.

**Comment by bartread** [comment]
Hi @chrisguttandin,


Thanks for the response, I do appreciate that.

The thing is, doesn't `ArrayBuffer.prototype.slice()` work by creating a copy of the original data? I'll grant you that from a memory standpoint this is much better than having hundreds of MB of decoded audio hanging around, but it's not going to do anything for latency[1], because now you have two (relatively) expensive operations:

1. Copy the ArrayBuffer.
2. Decode the audio data.

*[1] Latency in the sense of I want to play music starting at time `T` but actually it will start at time `T + X`, where `X` is the time taken to complete operations (1) and (2).

That also ties up the foreground thread for longer, and could lead to a noticeable glitch in rendering, at least on mobile devices. Again, not ideal.

The Service Worker suggestion is interesting in that, yes, I'm pretty sure it will work... but, it just adds to my frustration in the sense that we're getting into more (IMO) unnecessary complexity just to handle a fairly straightforward use case (I'd like to repeatedly play minutes long audio files without using tons of memory or experiencing significant lag). And that's all just fuel to the fire of my argument that whilst the Web Audio API might be a wet dream for a certain kind of software architect, it has not been well-designed with real use cases in mind.

I'm aware that this is probably not the optimal place to bang on this particular drum so if you can point me in the direction of a more appropriate forum I'd be happy to take the argument there.

I also appreciate the fact that you've suggested some workable solutions. Clearly neither is ideal but they will work and at least get me over a hump.


Thanks again,


Bart

**Comment by chrisguttandin** [comment]
Hi @bartread,

I’m not involved in the design process of this specification. I’m just following it. However I think that the problem you are describing is exactly the reason for choosing to neuter the ArrayBuffer instead of copying it. Copying is expensive.

There is a mailing list of the Audio Working Group: https://lists.w3.org/Archives/Public/public-audio/.

**Comment by padenot** [comment]
To be specific, at the time of this decision, there was no construct on the web platform that allowed to create a read-only slice of audio data. Not having this neutering resulted in more than one exploitable crashes in implementations.

As mentioned in the beginning of this thread, we now have `SharedArrayBuffer`, with intent to implement (or even ship) by more than one vendor.

Hopefully we'll be able to have this fixed soon, as it has been reported multiple times.

**Comment by wahengchang** [comment]
Is there a way to solve `ArrayBuffer` is gone in `decodeAudioData` function ?

I am working on a chunk streaming audio function, fetching audio binary file and append to audioContext one after one. So far, fetching and playback the first file is going well.
However the first `typeArray` is gone after running `audioContext.decodeAudioData(this.chunk)`.

```js

    const loadChunk = function(buffer1, buffer2) {
          const tmp = new Uint8Array(buffer1.byteLength + buffer2.byteLength);
          tmp.set(new Uint8Array(buffer1), 0);
          tmp.set(new Uint8Array(buffer2), buffer1.byteLength);
          return tmp.buffer;
    }

const  load = function(index) {
        const audioContext = this.audioContext
        let tempChunk

        return axios.get(`/chunks/${_files[index]}`, headers())
        .then((res)=>{
            if(index ===0) {
                this.chunk = res.data .     // or new SharedArrayBuffer(res.data)
            }
            else {
                this.chunk = this.loadChunk(this.chunk,  res.data) 
            }
            return audioContext.decodeAudioData(this.chunk)
        }).then(buf => {
            // -----------> this.chunk became a empty typeArray

            const _audioSource = audioContext.createBufferSource();
            _audioSource.buffer = buf;
            _audioSource.connect(audioContext.destination);
            _audioSource.start();
        })
    },

```

**Comment by padenot** [comment]
No, this is expected. You can clone it beforehand, though.

**Comment by wahengchang** [comment]
I did try both `buffer1.slice()` and `res.data.slice()`, they all does not help.

What is a better way to clone ?

**Comment by padenot** [comment]
This is not a support forum, please go on stackoverflow or somewhere else.

That said, cloning a buffer in js is usually done by doing `buffer.slice(0)`, as already written in this very thread.

**Comment by AndreVanKammen** [comment]
This is still very unexpected behavior (i just ran into it and wasn't expecting it), can't you pass ownership back to the main thread after decoding?
