### ISSUE TITLE
onstatechange behavior differs from .addEventListener('statechange')

### ISSUE THREAD

**Issue by ffxsam** [WebAudio/web-audio-api#1229]
I'm getting some really strange behavior. Someone please tell me if I've got something wrong here:

```js
  this.audioCtx.addEventListener('statechange', ({ target }) => {
    // Force state props to be re-sent to wrapped component
    console.log('state change!', target.state);
    if (target.state !== 'closed') this.forceUpdate();
  });
```

This works as expected. Any time the state changes, it fires off and forces my React component to update. However, when I change the code to:

```js
  this.audioCtx.onstatechange = ({ target }) => {
    // Force state props to be re-sent to wrapped component
    console.log('state change!', target.state);
    if (target.state !== 'closed') this.forceUpdate();
  };
```

It fires off a couple times upon `AudioContext` initialization, but never works after that. I issue multiple `resume` and `suspend` calls, and the `console.log` statements never happen. This occurs in all major browsers.

**Comment by rtoy** [comment]
Is this an issue with the spec?  It seems not, and you're actually reporting an implementation bug.  If so, file a bug against the implementation(s) that you are using.

**Comment by ffxsam** [comment]
That's why I was posting here, to see if anyone knows if this is part of the spec. It's odd that every browser I tried this on had the same behavior, which led me to believe there was something different about these two ways of event handling.

**Comment by rtoy** [comment]
I would expect the behaviour to be the same.  A small self-contained example would be really helpful. Maybe everybody made the same mistake.

**Comment by padenot** [comment]
@ffxsam, have you found an error in your code, or do you have a simple test case? You can open bugs in impementations:

- WebKit: https://bugs.webkit.org/enter_bug.cgi?product=WebKit&component=Web%20Audio (WebKit bugzilla account needed).
- Blink: https://new.crbug.com/ (Google account needed).
- Gecko: https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Web%20Audio (GitHub, Persona or Mozilla Bugzilla account needed). 

I'm closing this because the spec is very clear on what is supposed to happen, for example for [suspend](https://webaudio.github.io/web-audio-api/#widl-BaseAudioContext-resume-Promise-void): 

> Queue a task to fire a simple event named statechange at the BaseAudioContext.

which, translated from spec linguo, means: "put a `statechange` event at the back of the event queue for this event loop". That in turns provoke the invocation of the `onstatechange` handler or the `addEventListener`.

**Comment by ffxsam** [comment]
Can't replicate in a barebones sandbox. Closing.
