### ISSUE TITLE
Behaviour of the interaction between deprecated `setPosition` method on `PannerNode` and the new behaviour of the `AudioParam.value` setter

### ISSUE THREAD

**Issue by padenot** [WebAudio/web-audio-api#1268]
Consider the following:
- On a `PannerNode`, have one of the `AudioParam` be automated using a curve
- When the `AudioContext.currentTime` reaches the curve region, call `setPosition`

This is specced as being equivalent to setting the `AudioParam`s directly. This in turn is equivalent to calling `AudioParam.setValueAtTime(v, ac.currentTime)` with `v` the value being set and `ac` the `AudioContext`.

Should `setPosition` now throw ? Should it swallow the exception ?

**Comment by padenot** [comment]
@rtoy, what do you think? I'm doing some changes to gecko in the area and it's unclear what I need to do here.

**Comment by rtoy** [comment]
(Sorry for the delay!)

That's a good question.  For consistency, I think `setPosition` should throw to be consistent with what `setValueAtTime` would do in this situation.. (Chrome doesn't do this I think.)

But `setPosition` is noted as being deprecated, so I think there's a lot of leeway in what to do.

On the other hand, I really like `setPosition` as a super convenient short hand for setting the position instead of doing three setValueAtTime() calls.

**Comment by padenot** [comment]
Let's just throw for consistency.

**Comment by rtoy** [comment]
Sounds perfect.

**Comment by rtoy** [comment]
Oh, I guess we need to make this change for both the `PannerNode` and the `AudioListener`.  And `setOrientation` needs to spec'ed to throw too.
