### ISSUE TITLE
MediaElementSource should contain all Tracks as outputs

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#132]
> Originally reported on W3C Bugzilla [ISSUE-17345](https://www.w3.org/Bugs/Public/show_bug.cgi?id=17345) Tue, 05 Jun 2012 11:37:40 GMT
> Reported by Philip Jägenstedt
> Assigned to 

Audio-ISSUE-54 (MediaElementAudioSourceNode): MediaElementAudioSourceNode [Web Audio API]

http://www.w3.org/2011/audio/track/issues/54

Raised by: Philip Jägenstedt
On product: Web Audio API

HTMLMediaElement is integrated into Web Audio API using the MediaElementAudioSourceNode interface and createMediaElementSource. This looks like an unnecessarily complicated way of making the connection.

Suggestion:

Extend the HTML AudioTrack interface [1] with an "AudioSourceNode node" member. This allows us to use multiple audio tracks from a single HTMLMediaElement.

[1] http://www.whatwg.org/specs/web-apps/current-work/multipage/the-video-element.html#audiotrack

**Comment by joeberkovitz** [comment]
Closing since the TPAC 2014 resolution was implemented and adding more outputs to the node does not heklp the developer distinguish one audio track from another on a meaningful basis. Developers can already control the active track of an HTMLMediaElement and thus affect which track will be piped into the MediaElementSourceNode.
