### ISSUE TITLE
Web Platform Test: upstreaming test suites from vendors

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#1388]
I realized we don't have an open issue for this one. I leave this note as a future reference.

Upstream target: https://github.com/w3c/web-platform-tests/tree/master/webaudio

**Comment by rtoy** [comment]
Initial start:  Create a Chrome/Firefox/Edge, etc., directories for the current vendor-specific tests.

Then move the tests around as needed.

**Comment by svgeesus** [comment]
@padenot  you mentioned 4 AnalyserNode tests would be upstreamed soon. I guess these will show up in https://github.com/w3c/web-platform-tests/tree/master/webaudio/the-audio-api/the-analysernode-interface ?

**Comment by hoch** [comment]
I thought it would rather be something like:
https://github.com/w3c/web-platform-tests/tree/master/webaudio/firefox/analyser

Isn't this the consensus for WPT? Collecting the vendor-specific tests in different locations and then merge them later?

**Comment by padenot** [comment]
> I thought it would rather be something like:
> https://github.com/w3c/web-platform-tests/tree/master/webaudio/firefox/analyser
> 
> Isn't this the consensus for WPT? Collecting the vendor-specific tests in different locations and then merge them later?

Talking with @jgraham, he told me the first form (without vendor directories) is preferred.

**Comment by jgraham** [comment]
Yes, we have tried quite hard to remove vendor directories. Maybe part of the confusion is that we have also tried to make it possible for vendors to upstream wpt tests from their own repositories, so in that sense they are collected in different locations and then merged, but in all cases it makes more sense to put the tests into their expected final location, rather than adding confusion from vendor directories.

**Comment by rtoy** [comment]
I find this a bit unfortunate.  We do fully expect to move all of these "vendor" directories into the final locations.  But as a way to keep track of tests that are now being added, this makes life much easier to see what is new and how it breaks. (We fully expect lots of firefox tests to fail on chrome and vice versa).

In addition, chrome's tests have a wrapper around testharness (to provide much better information on failures).  If this goes in, we get into a state where many tests are written in one style but many are written in another.  That seems rather unfortunate to keep it this way.

I also expect lots of duplication of tests (chrome has that problem).  How do we handle filename conflicts?  The first one to land wins?  That also seems unfortunate.

**Comment by svgeesus** [comment]
So, are the tests going into vendor-specific directories or one WG one?

**Comment by rtoy** [comment]
I certainly prefer vendor-specific directories for now, as an intermediate step.  You can file an issue and assignment to me to move all of the vendor tests into the final resting place, if you like.

**Comment by svgeesus** [comment]
I was mainly trying to avoid the situation where lack of clarity on where to put the tests, meant we didn't have tests for a while.
I agree that vendor-specific directories will make triaging for overlap easier.

**Comment by jgraham** [comment]
Again, this is something we have tried (and mostly succeeded) in eliminating from the repository, because it generally doesn't work. Whilst the tests are in vendor directories they don't help interop because everyone is happy to assume that tests from other vendors aren't supposed to pass in their implementation for whatever reason. Then the actual act of moving tests around can cause problems (because the path is the basis of the test id and so things like vendor metadata and wpt.fyi results can get lost after a move).

If you want to edit the tests before they are run by vendors then that can happen on a branch. Otherwise, just land the tests with any renaming necessary to produce unique test names. If you want to know which tests came from each vendor for triage purposes the git history will tell you. If you want to rewrite some tests in a different style it's better to do it in-place so that if the project is never completed we still end up with the tests in a sensible place, rather than with unexpectedly long-lived vendor directories that result in interop issues being ignored.

**Comment by rtoy** [comment]
I understand your point and I agree that vendor directories are bad.

Sadly, when I look at, say, https://wpt.fyi/webaudio/the-audio-api/the-audioparam-interface/retrospective-exponentialRampToValueAtTime.html, two of four browsers are marked as passing.  The two browsers that fail the test fail because they timed out.  The two browsers that pass the test pass because of an error: ConstantSourceNode not implemented or AudioContext not implemented (prefixed version). (That seems wrong.)

I definitely do want to fix this, either be fixing the test itself or by removing it.  And piling on tons of new tests in this directory isn't going to help me fix things.  And having to look through git logs just makes my life that much more difficult.

It's also pretty clear that no one is paying any attention to these tests, including me. :-(  Probably because everyone has his own set of tests with probably better coverage than the existing tests.

I *do* want to pay attention to these tests. I just don't want to have to deal with everything all at once, everywhere.

**Comment by rtoy** [comment]
Oops. I think I misinterpreted the results for the two browsers that pass.  These two both pass the first test but fail the second with errors.  That seems ok.  Why the other two timeout needs investigation.

**Comment by padenot** [comment]
Some gecko tests are now at [0].

[0]: https://github.com/w3c/web-platform-tests/tree/master/webaudio/the-audio-api/the-analysernode-interface

**Comment by rtoy** [comment]
Not a blocker.  Leave open until every one has "finished" upstreaming their tests.

**Comment by rtoy** [comment]
From yesterday's teleconf, Chrome has upstreamed their tests for all nodes except those from A to C.

**Comment by mdjp** [comment]
@padenot please could you give us an update of the progress from your side?

**Comment by padenot** [comment]
We've recently started to look closely at Firefox's results on the current set of wpt, and we have some tests that can complement those. We still have quite some work to be compliant though.

**Comment by rtoy** [comment]
Can we close this?  Everyone who is active has committed to moving tests or creating new tests in WPT.  We have a fairly large set of tests, and more are being created/added.
