### ISSUE TITLE
Silence hint for AudioWorklets

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1480]
This is a small optimization (Chrome uses this internally a lot).

If an input to an `AudioWorkletNode` is known by the implementation to
be silent, it would be nice to inform the node of that.  This allows
the node to shortcut the computations and produce a default output.

This could be indicated by making the input be an array of length 1
containing the value 0 for all channels of the input.

This is in the same spirit as #1464.

It would also be nice if the worklet could indicate that the output is
silent, but I can't think of a good way to do that without causing
additional consing.

**Comment by joeberkovitz** [comment]
I'd suggest defining this as a hint that each channel of an input will have a constant value for the entire rendering quantum, not merely a zero value.

**Comment by rtoy** [comment]
In last weeks teleconf, I said I was ok with a non-zero value.  But since then, I've reconsidered.  I think the array should only have length 1 (with a value of 0, but not really important) **only** if the input is silent.

For many audio nodes, zero input implies zero output (ignoring memory considerations). The hint allows you to bypass most of the processing and just zero out the output arrays. 

However, if the input is constant but not zero, you don't really get to bypass anything.  You end up either writing special code to handle the single-element array, or copying the value to a new array so that you can continue to use the existing general case code.  So for simplicity, I prefer just doing the hint only if the value is 0.

This differs from an `AudioParam`, because you still need to know the value, whether it's zero or not.

**Comment by rtoy** [comment]
Action Item:  rtoy to write a PR for one of the proposed optimizations.

**Comment by rtoy** [comment]
An alternative:  Don't change the array lengths, but add another parameter to `process()`.  This parameter specifies whether the corresponding input is silent or not.  So, maybe `process(inputs,outputs,parameters, silenceHint)`.  This could be an array of booleans or bytes or something.

Advantage:
- the array lengths are always fixed
- you can ignore the extra arg if you don't care about the hint
- completely backward compatible

Disadvantage:
- More garbage generated because of the extra (small) array
- Extra parameter to the method.

**Comment by rtoy** [comment]
Action @rtoy: Make PR based on the proposal in https://github.com/WebAudio/web-audio-api/issues/1480#issuecomment-367783564

**Comment by rtoy** [comment]
Teleconf:  Let's postpone this to V2.  That kind of implies the approach has to be an extra parameter so we don't break existing worklets.

**Comment by rtoy** [comment]
Handled by active processing concept.

**Comment by andremichelle** [comment]
I just figured that the parameter array is also truncated to one entry, if only one other node is connect to that parameter. This should be considered as automated, since the incoming values are a-rate.
From the specs: "However, if no automation is scheduled during this render quantum, the array MAY have length 1[...]"

**Comment by marcelblum** [comment]
Hello from 2023, I noticed this is closed as completed but it's not clear exactly how or if it actually has been "handled by active processing concept" (is that a reference to v2?). Even in the latest browsers it seems that in order to accomplish this I must add to my audioWorklets something like

```javascript
checkForNotSilence(value) {
  return value !== 0
}
process(inputs, outputs, params) {
  if (inputs[0][0]?.some(this.checkForNotSilence) || inputs[0][1]?.some(this.checkForNotSilence)) {
    \\ ...
  }
  return true;
}
```

which feels horribly inefficient yet can tremendously minimize cpu use (and glitching in other active nodes) when idle.

**Comment by padenot** [comment]
It's been "handled by active processing concept" since we made the change in a PR that was meant to specifiy the "active processing" concept: https://github.com/WebAudio/web-audio-api/issues/1935, itself part of the larger theme of garbage collection observability: https://github.com/WebAudio/web-audio-api/issues/1471.

The prose now [reads](https://webaudio.github.io/web-audio-api/#ref-for-dom-audioworkletprocesscallback-inputs):

> If there are no [actively processing](https://webaudio.github.io/web-audio-api/#actively-processing) [AudioNode](https://webaudio.github.io/web-audio-api/#AudioNode)s connected to the 𝑛th input of the [AudioWorkletNode](https://webaudio.github.io/web-audio-api/#AudioWorkletNode) for the current render quantum, then the content of inputs[n] is an empty array, indicating that zero channels of input are available. This is the only circumstance under which the number of elements of inputs[n] can be zero.

This means that you can do:

```js
process(inputs, outputs, params) {
  if (!inputs[0]) {
     // No input, nothing to do, either early return or output a the tail of
     // a DSP algorithm (if this is a reverb/delay, etc.)
  }
  return true;
}
```

If there are nodes connected to this `AudioWorkletProcessor` that are _explicitely_ sending silence to the `AudioWorkletProcessor`, you'll have to check the input though, this isn't something we're detecting. The above covers things like: `AudioBufferSourceNode` or `MediaElementAudioSourceNode` that hasn't started / have ended, possibly connected to (e.g.) lots of gain nodes or other processing node, that kind of situation, but wouldn't cover e.g. the playback of a portion of silence in an audio file.

You can also choose to return `false` or `true` in the `if (...)` above, but that's up to you, depending on what your `AudioWorkletProcessor` does.

**Comment by marcelblum** [comment]
Ok I see the broader reason why this was throwing me off. My code was already going ahead with expensive processing only if `inputs[0].length`. The problem is that different browsers seem to define "active" differently. On Chrome even if an inactive silent Gain is connected to an AudioWorkletNode, with nothing else connected in the chain, `inputs[0]` is populated with silence. But on FF `inputs[0]` will indeed be empty under the same conditions. Demo which connects a gain node to an AudioWorkletNode after 5 seconds:

https://codepen.io/keymapper/pen/NWLzRWJ

I guess it would be a leap to call this a Chrome "bug" but certainly it's pretty significantly different behavior that can lead to inferior performance in Chrome in these types of cases.

**Comment by hoch** [comment]
Currently Chrome's AudioWorklet behavior is not really up-to-date w.r.t the current spec language. This active processing logic is one of those gaps. If you can file a bug in crbug.com, we will definitely take a look at them and make a plan for it.

**Comment by marcelblum** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1425268
