### ISSUE TITLE
Valid number inputs/outputs for ChannelMerger and ChannelSplitter?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1590]
In both https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-createchannelmerger and https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-createchannelsplitter, the spec says the errors are thrown for invalid values for the number of inputs or outputs, respectively.

But I can't find anywhere that says the the valid range is.  

In particular, is 0 allowed? I would say no.  Creating such nodes are pretty much useless.

Also, let's say the browser supports just 32 channels, the minimum required.  Can I create a merger with 33 inputs?  I think that should throw an error because that imply 33 channels in the output, which is not supported.

What about a splitter with 33 outputs?  The splitter is pretty well-defined so that the 33rd output will always be silence because we can't have more than 32 channels in the input.  But maybe for consistency with the merger, it should also throw?

**Comment by karlt** [comment]
Yes, I agree that throwing for number of inputs or outputs greater than the
supported number of channels is probably what was intended by "exception MUST
be thrown for invalid parameter values" and "values of up to 32 MUST be
supported."

Similarly I assume that one is the intended minimum of inputs or outputs.

One is the implied minimum number of channels in
https://webaudio.github.io/web-audio-api/#channel-up-mixing-and-down-mixing
> Each of these connections from an output represents a stream with a specific non-zero number of channels.

and in
https://webaudio.github.io/web-audio-api/#dom-audionode-channelcount
> If this value is set to zero or to a value greater than the implementation’s maximum number of channels the implementation MUST throw a NotSupportedError exception.

and in
https://webaudio.github.io/web-audio-api/#defining-a-valid-audioworkletprocessor

> If no connections exist to the nth input of the node during the current render quantum, then the content of inputs[n] is an empty array, indicating that zero channels of input are available. This is the only circumstance under which the number of elements of inputs[n] can be zero.

I'm not so clear on the situation for `computedNumberOfChannels` with "max" `ChannelCountMode` and no input connections, but a minimum of one is implied by the output stream non-zero channels requirement and
https://webaudio.github.io/web-audio-api/#configuring-channels-with-audioworkletnodeoptions
> the output channel count will match computedNumberOfChannels from the input.

There are also exceptions in https://github.com/WebAudio/web-audio-api/issues/1578 but there seem to be reasons for those exceptions to the general one-channel-minimum case.

**Comment by rtoy** [comment]
I was talking about the valid range for the number of inputs or outputs, not the number of channels.  Is it valid to do new ChannelMergerNode(context, {numberOfIputs: 0})?  Kind of useless to have a merger that you can't connect too, but not totally wrong.  Similarly, an splitter with no outputs is rather useless.

Should they be allowed?

**Comment by karlt** [comment]
I assume the intention was to throw an exception for number of inputs or outputs outside the valid range for number of channels.

ChannelMergerNode has "a single output whose audio stream has a number of
channels equal to the number of inputs."  It is not valid to do new ChannelMergerNode(context, {numberOfIputs: 0}) because the number of channels of output must be at least one.

Similarly for ChannelSplitterNode, `channelCount` is specified as `numberOfOutputs` and `channelCount` cannot be zero, which implies `numberOfOutputs` cannot be zero.

**Comment by rtoy** [comment]
Yes, you're right about the ChannelMergerNode.  I certainly would prefer a more explicit statement of this in the definition of numberOfInputs or something.  Finding this constraint in some text is pretty hard.

I agree with what you say for ChannelSplitterNode.  A bit roundabout, but valid.  And clearly we need to be able to have at least 32 outputs.  But can there be more?

**Comment by karlt** [comment]
Yes, it would certainly be helpful to spell this out more clearly/directly.

For the same reasons that ChannelSplitterNode's `numberOfOutputs` cannot be
zero, `numberOfOutputs` cannot be greater than the "implementation’s maximum
number of channels".

If the channel maximum is greater than 32, then I'm not aware of any existing
requirements for ChannelSplitterNode.  If more than 32 channels are supported,
then `numberOfOutputs` greater than 32 at least MAY be supported, but this is
not currently explicitly required.  Perhaps this could be changed so that
`numberOfOutputs` up to the "implementation’s maximum number of channels" MUST
be supported.  I don't have a strong opinion.

The situation for `numberOfInputs` in ChannelMergerNode seems consistent with
`numberOfOutputs` in ChannelSplitterNode, and I think that's a good thing for
the sake of the fewest number of surprises.

**Comment by rtoy** [comment]
I think the only thing left to decide is what error to throw when the value is outside the range. I think NotSupportedError is appropriate here since that's what happens when creating an `AudioBuffer` with an invalid number of channels.

**Comment by rtoy** [comment]
Oops. We already say IndexSizeError.  I'm not going to change that.
