### ISSUE TITLE
[QUESTION] AudioContext as an event scheduler

### ISSUE THREAD

**Issue by BioPhoton** [WebAudio/web-audio-api#1640]
[QUESTION]
Hi!
As the AudiaContext.currentTime result is way more accurate as other time systems i.e. Date.now(), I'm curious if it is possible to schedule some not audio-related code with AudioContext or OfflineAudioContext.

Thanks for your time and answer,
Michael

**Comment by Mr21** [comment]
Not really, the precision of `AudioContext.currentTime` is for all others Web Audio methods.
A callback in JS implicitly means not in real time, because it's in JS.
All the value that you can calc and predict by ctx.currentTime will be used with the low-audio-level c++ methods of the browser.

The only no-audio thing you can do with it, is measuring time precisely maybe for benchmark i don't know. Why do you need so much time precision?

**Comment by JohnWeisz** [comment]
It's not really possible in an arbitrary fashion, but even it _was_ possible, your callbacks would be still subject to message-queuing, just as with `setTimeout`.

**Comment by BioPhoton** [comment]
I was trying to use the suspend promise to execute some code. But as you said the same queue.
