### ISSUE TITLE
Update Travis CI integration

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1696]
We currently use github service to integrate with Travis.  But that's deprecated so we need to move this eventually to a github app for travis.

**Comment by padenot** [comment]
Github Service is going away on 31st of January 2018, so this one is becoming a bit pressing.

**Comment by hoch** [comment]
The [PR Preview](https://github.com/tobie/pr-preview) is still using GitHub Service. I am not sure it can be migrated to the new webhooks.

**Comment by hoch** [comment]
Also Travis CI integration is registered under your account, @padenot. :)

https://github.com/WebAudio/web-audio-api/settings/hooks/6126589

**Comment by hoch** [comment]
What's being deprecated is "GitHub Services". We have two items - "IRC" and "Travis CI".
There are two migration paths from the deprecated service: "webhooks" and "GitHub Apps".
Since [Travis CI offers GitHub Apps](https://github.com/apps/travis-ci) for their service, I think it's the better option.

**Comment by hoch** [comment]
I followed through the instruction, but it seems like we can't have both (service and app) at the same time. I started the app installation, but it failed because we already have a legacy service hook. It seems like a bit of downtime for Travis CI is inevitable since we have to delete the service and then setup the app.

WDYT @padenot?

**Comment by padenot** [comment]
I've started the process, but there is a bit of a manual validation thing. I've sent an email to travis-ci, will report back.

**Comment by padenot** [comment]
Checking PR now works fine, automatic deploy does not work anymore because everything changed there. I'm fixing it right now.

**Comment by padenot** [comment]
This is now fixed by https://github.com/WebAudio/web-audio-api/commit/74a67006a42a8dacce7cee2ae8320b515c0d5233, automatic deploy works well. 

There are a few differences, such as a slightly messier state of the `gh-pages` branch (that contains everything, but this is more robust, no issue with not copying the right files), and different commiter name/email.

I think all the defaults work well for us, but it seems to be quite flexible, let me know if there is something to improve.

An example of a deploy commit: https://github.com/WebAudio/web-audio-api/commit/eb44da177947dc24356ee8c59d03d51c31e99bb8 (it's very big because it's the first one).
