### ISSUE TITLE
Specify what happens when you connect() to an AudioParam on the AudioListener

### ISSUE THREAD

**Issue by Manishearth** [WebAudio/web-audio-api#1700]
The AudioListener has many AudioParams, which you can set timeline events on. This is great.

However, you can also connect the outputs of other nodes to it, via `AudioNode.connect(param)`.

This seems pretty tricky to deal with correctly. The processing model doesn't handle it at all, it just mentions that you should "compute the values" for the params, which isn't possible for when nodes are connected to the params since we haven't started computing the outputs of the nodes yet.

If we were to include this in the graph algorithm there would be significant complexity added -- the cycle breaker algorithm needs to understand the "special" dependency on the listener from panner nodes -- this contributes to cycles but cannot be broken.

Ideally we should make connecting to such params a hard error on the DOM side (or a "does nothing" thing on the audio renderer's side). No browser implements these as params yet, so we should be good for now. I don't really see the value in allowing audio nodes to connect to listener params; this sounds like a recipe for massive vertigo and not much else.

cc @padenot @ferjm

**Comment by karlt** [comment]
Thanks for filing this.
"Compute the value(s) of the AudioListener's AudioParams for this block"
does seem out of place now.

Although AudioListener is an object on the AudioDestinationNode, it is really
a connected input to all PannerNodes (and not connected to
AudioDestinationNode).

If there are no PannerNodes upstream from the listener, then there need be no
cycle.

If the listener can be included with the AudioNodes in the list "to be
processed", and the implicit connection from AudioListener to PannerNodes can
be described, then I expect "Order the AudioNodes of the AudioContext to be
processed" will perform as required and mute in the case of a Panner upstream
from Listener.

That's all assuming there's good reason not to just deprecate AudioListener
AudioParams.

**Comment by karlt** [comment]
> note that describing this connection complicates things significantly, you now have two kinds of connections, only one of which can be broken via DelayNode insertion

I expect a DelayNode to always be able to break cycles.  I don't know of a need to have two kinds of cycles.

**Comment by Manishearth** [comment]
because the other dependencies are audio stream dependencies, whereas the dependency of a panner node on the listener is a different kind of dependency, it doesn't make sense to insert a delay node inside it because the data being used is position data, not audio data.

**Comment by Manishearth** [comment]
If it gets modelled the way I proposed, then you basically pretend that it's an audio stream and it kind of works, but it's still not pretty :smile:

**Comment by padenot** [comment]
> Ideally we should make connecting to such params a hard error on the DOM side (or a "does nothing" thing on the audio renderer's side). No browser implements these as params yet, so we should be good for now. I don't really see the value in allowing audio nodes to connect to listener params; this sounds like a recipe for massive vertigo and not much else.

Chrome has shipped this a while ago (M52).

Audio signal as a control parameter is a fundamental building block in audio synthesis (for example, it is the basis of FM synthesis), and so special casing the `AudioParam` of the `AudioListener` to not be able to be connection destination would both break compatibility and prevent legitimate uses-cases.

Instead, let's just amend the Processing model section, as @karlt mentions: Instead of just ordering `AudioNode`s, also order `AudioParam`s that have been connected to. This is in fact quite necessary, the current state of things is a bit too hand-wavy and sub-optimal: there could be a block of unnecessary delay induced in the control signal, if you interpret strictly the text.

I think what is needed is to:
- Include `AudioParam`s in the processing ordering algorithm (in practice, only the `AudioParam` that have been connected to need to be included here).
- Transitively visit `AudioNode`s that are inputs to another `AudioNode` (named `destination`) transitively *via* `destination`'s `AudioParam`s. In other word, we explicitly write down the implicit (for now, but necessary in practice) precedence dependency of an `AudioNode` and its own `AudioParam`s.
- Add an implicit connection from the `AudioListener` to all `PannerNode`.

**Comment by Manishearth** [comment]
> Instead of just ordering AudioNodes, also order AudioParams that have been connected to

This isn't the high order bit here -- in fact, the way I interpreted the current algorithm _already_ was that audioparams are considered connections.

We should clarify this anyway, but this is not the tricky thing to fix here, the tricky thing is the implicit connection.

**Comment by Manishearth** [comment]
I'm still skeptical that the connecting to audioparams for listeners is necessary (note that you can do it for panner nodes). It is true that some algorithms need connecting to params, but I'm skeptical that algorithms need it for connecting to _these_ params.

I should look at chrome again, I checked the source and it didn't seem to do it but I may not have looked properly.

**Comment by padenot** [comment]
> This isn't the high order bit here -- in fact, the way I interpreted the current algorithm already was that audioparams are considered connections.

The three items needs to be fixed for this to work correctly, this is a spec and should not be "interpreted" (and too often it has to be :-)).

**Comment by padenot** [comment]
@rtoy, @hoch, do you have an opinion here? I hear Chrome is considering changing the way it computes the order in which to process the nodes, I wanted to make sure you've seen this one.

**Comment by rtoy** [comment]
First, this is an interesting question.  Second, I don't think we can get rid of the AudioParams for the listener.  They're needed so you can move the listener around smoothly.  (I suspect no one actually moves the listener.)

Third, without thinking super hard about the consequences, I'm ok with disallowing connecting to the listener params.  Disallowing connections is also kind of weird because it's a fundamental feature of AudioParams.  However, this disallows fine control over position and orientation.  If you want to move the listener around in space on a complicated path, having an audiobuffersources that contain the carefully computed x,y,z coordinates of the path makes the motion straightforward.  Doing that with linearRampToValue is a bit more work.  

Finally, to @padenot question, we have thought about it but it seems unlikely because it's a huge change of the internals and you can't do it in pieces.  It has to be all or nothing.

I was trying to do a simple test of connecting to the listener's audioparam, but Canopy has a bug that doesn't let me do the connection. :-(  I think Chrome will do the right thing here because when you need the listener values, it should pull on the inputs to get the data before returning the values.

**Comment by hoch** [comment]
It's a radical idea, but @rtoy and I thought about making the AudioListener as an AudioNode with zero input and zero output. If it becomes an AudioNode, we don't have to treat it specially. Right? So it will fit in the current processing model without changing anything.

However, this changes the inheritance scheme in IDL so it might mean a significant change depending on your view point. This kind of change requires an intent and approval for browsers to ship.

Personally, I am against adding more magic like disallowing connection to AudioParams in AudioListener.

**Comment by padenot** [comment]
> I suspect no one actually moves the listener.

What does this mean? A quick search on github shows quite a lot of uses, and is going to land in three.js, which is used all over the place.

**Comment by padenot** [comment]
> Personally, I am against adding more magic like disallowing connection to AudioParams in AudioListener.

Same.

**Comment by rtoy** [comment]
Ah, I didn't do a search.  That's cool. I was expecting people to move the sources around instead of the listener.

If we fix the algorithm as suggested in https://github.com/WebAudio/web-audio-api/issues/1700#issuecomment-405918078, then everything should be ok?

**Comment by Manishearth** [comment]
> this is a spec and should not be "interpreted" (and too often it has to be :-)).

Right, like I said we should clarify that part anyway, but my point is that explicitly handling audioparams is not the core of my problem here -- I always assumed that to be implicit in the algorithm so it never was a problem for me. It's the weird non-audio-stream dependency between listeners and panners that's the problem.

**Comment by rtoy** [comment]
The implicit dependency has always been a bit weird to me.

One nice approach about making the listener be a real node with no inputs and one output (containing 9 channels) is that then we could actually polyfill a panner node and a listener node using worklets.  As it is today, you can't because of the hidden dependency because there's no way for the poly-filled panner to get the automation values from the listener.  I think it's too late to do this for V1.

**Comment by Manishearth** [comment]
What's the final plan here? I'd like to implement this :smile:

**Comment by padenot** [comment]
Sorry @Manishearth, I meant to write something here but I forgot. We discussed with @rtoy in a call last week. The decision goes like this (similar to what I said in [this comment](https://github.com/WebAudio/web-audio-api/issues/1700#issuecomment-405918078)):

- There is an implicit connection from the `AudioListener` to all `PannerNode`. 
- `AudioParam` have to be taken into account when computing the ordering of computation of `AudioNode`s: if an `AudioNode` A connnected to the `AudioParam` of an `AudioNode` B, then A needs to be computed before B.
- There is an implicit connection between an `AudioNode`/`AudioListener` and their `AudioParam`: i.e. you compute the param first, then the rest.

By transitivity, say an `AudioNode` A is connected to `upX` of the `AudioListener`, and a `PannerNode` B exists in the graph, then A will be computed first, then B.

Normal rules for cycles apply.

I'll come up with some normative text when I have the chance.

**Comment by Manishearth** [comment]
Okay, I'll implement this with the nine-channel thing. With luck that won't be slower or anything.
