### ISSUE TITLE
setValueCurve duration when start time is clamped

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1712]
In https://webaudio.github.io/web-audio-api/#dom-audioparam-setvaluecurveattime, the `startTime` is clamped to `currentTime`.  This is fine.

But now what happens to `duration`?  Does the event end at time `startTime + duration` or at `max(startTime, currentTime) + duration`?  The former makes quite a bit of sense, but the latter is much easier to explain what happens.

**Comment by padenot** [comment]
I think the former makes more sense. The latter could really be problematic, because it would shift the phase of the automation.

**Comment by karlt** [comment]
> So, if the event ends at startTime + duration, this effectively makes the duration equal to duration - (currentTime - startTime)? That also messes up the curve values because the number of samples is different.

This may be kind of useful if the startTime is only just missed, to soften the impact
of the miss.

But I guess using an AudioBufferSourceNode might be more appropriate if aiming
to schedule a short transient effect as soon as possible, and phase is not important.
Its duration would not be shortened on missing its startTime.

> Or do we want to say startTime isn't clamped. Then the first output would correspond to the sample at currentTime, skipping over all the samples that would have been output between startTime and currentTime? This preserves the (interpolated) output samples, but the output will be missing the beginning part of the curve.

This was the behavior in
https://www.w3.org/TR/2015/WD-webaudio-20151208/#widl-AudioParam-setValueCurveAtTime-AudioParam-Float32Array-values-double-startTime-double-duration

I don't recall exactly why that was changed.  Maybe it was to soften the
impact of just missing the start, but worth checking before reverting to that
behavior.  I'm not clear which would be better.

**Comment by rtoy** [comment]
I vaguely remember this was changed to define what happens if the time for an automation is in the past.  I think for other automation methods it makes sense to clamp to currentTime.  But `setValueCurveAtTime` is a bit more complicated and we probably didn't consider this back then.

**Comment by karlt** [comment]
There are similar issues even for non value-curve events sometimes.

If, for example, there are existing events at times 2 and 4, currentTime = 3,
and an event is added with startTime = 1, then clamping startTime to reorder
the events so that the added event is after the existing event at time 2 could
produce unexpected results, for multiple types of added events.

The difference with setValueCurveAtTime may really only be that the duration
makes it difficult to insert the event in any random place.

**Comment by rtoy** [comment]
I think people have wanted to schedule events in the past on purpose, including with negative time values.

There's another related issue.  setValueCurve can't overlap other automations, so the actual event startTime and duration are important in catching the overlap.

**Comment by karlt** [comment]
https://github.com/WebAudio/web-audio-api/issues/713 was the discussion re the
change to clamp `startTime` to `currentTime`.  It looks like the intention may
have been to avoid missing the start of the automation in the same way as the
`start()` method on source nodes starts immediately if the `when` parameter is
in the past.  Source nodes, however, often don't have other event times that
affect the signal.  `stop()` is the exception, but `offset` can be used
instead.  AudioParams have the additional complication of how a change to
`startTime` on one event would interact with other events.

Something to consider may be to only change `startTime` to `currentTime` if
there are no other events between `startTime` and `currentTime`.  For value
curves, I don't know whether it would be better to limit `startTime` changes
so that `startTime + duration` does not pass any other events, or whether
reducing `duration` is better.

**Comment by rtoy** [comment]
This is acceptable to me, although it does make setValueCurveAtTime a bit different from the other automations.

**Comment by karlt** [comment]
Consider:
```
oldTime = ctx.currentTime;
...
param.cancelAndHoldAtTime(oldTime);
...
param.setValueCurveAtTime(values, oldTime, duration);
```
If `currentTime` can advance before the `cancelAndHoldAtTime`, then
`currentTime > oldTime` and an implicit `setValueAtTime` event may be inserted
at `currentTime`.  Whether `setValueCurveAtTime` throws or not (due to
conflict with the `setValueAtTime`) would depend on whether `currentTime` had
advanced or not.  This seems to be a problem caused by clamping for one method
and not another, and the interaction with the instability of `currentTime`.

**Comment by karlt** [comment]
I guess `startTime` could be clamped to `currentTime`, but the start of the
curve removed when clamping happens, in much the same way as
`cancelAndHoldAtTime()` would remove the end of a curve.

That would provide the same curve as not clamping (when there are no
conflicting events).

It's hard to say whether compressing the curve by merely reducing `duration`
or skipping the start of the curve is better, because it depends on the
situation.  Reducing `duration` would be simpler, and probably more consistent
with the effects of clamping times on other events.

Not clamping (and so skipping the start of the curve) seems reasonable if
times are not clamped for any types of events.

**Comment by padenot** [comment]
WG resolution: remove all clamping.

This makes the system predictable. When rendering a render quantum, take the state of the AudioParam timeline, and compute the correct value.

Mention in the spec as a note that this means that if one schedules event in the past, discontinuities can (and will) happen, and that this is intended.

```js
setValueAtTime(1.0, 0.0);
linearRampToValueAtTime(2.0, 10.0);

// ... time passes, currentTime is now 5.0

setvalueAtTime(5.0, 0.0); // this makes the value jump because we've changed the start value of the curve

```

**Comment by rtoy** [comment]
Question on how this should behave:

```
setValueAtTime(1,0);
// time passes until current time is 5
setValueAtTime(0, 1)
```
The second event is inserted at time 1 but it's time 5.  What is the output now at time 5 and later? 0? I think this makes sense.

What if I do this instead?
```
setValueAtTime(1,0);
// time pass until current time is 5
setTargetAtTime(0, 1, 1);
```
What is the output now at time 5?  Will we get a discontinuous jump from 1 down to whatever the target event would be after 4 sec have elapsed (because it started at time 1 and we're at time 5)?

**Comment by karlt** [comment]
That's a good question, thank you rtoy.
The discontinuity you describe is the simplest model based on the resolution,
but there is definitely a question re whether that is useful.

Perhaps there's an alternative approach along the lines of defining curves in
such a way that any new event would only affect the curve after current time.

In a sense, times are not clamped, because events stay in the same order.
But with the `setTargetAtTime(0,1,1)` applied at `currentTime = 5` the curve
would not start approaching 0 until `currentTime = 5`.

For the case of
```
setValueAtTime(1,0);
// time pass until current time is 5
linearRampToValueAtTime(0, 10);
```
the linear ramp from 1 to 0 would begin from 1 at `currentTime = 5`.

Under that system, a curve from `setValueCurveAtTime` would not be adjusted,
and so the start of the curve may be ignored if called with
`startTime < currentTime`.

**Comment by padenot** [comment]
Do we think it's better to have something that makes the model more complex to reason about, but make some cases behave better?

I'm thinking that because we seem to have a problem to agree on a behaviour, it's probably best to have something that is simple and predictable.

**Comment by karlt** [comment]
Clamping the start or end time reorders events, which is not good for predictability.

Removing clamping removes the problem of reordering, but leaves the problem of unnecessary discontinuities, and some of these are situations that seem likely to be common. e.g.
```
param.cancelAndHoldAtTime(currentTime);
param.linearRampToValueAtTime(2.0, currentTime + 1.0);
```
`currentTime` will/may have passed by the time the rendering happens and so the start of the ramp is skipped (unless the automations are adjusted in some way, such as proposed in https://github.com/WebAudio/web-audio-api/issues/1712#issuecomment-420524694).

I expect it is worthwhile having a little more complexity to address the most common discontinuities.

**Comment by padenot** [comment]
I'm having a bit of a hard time understanding what is being proposed here.

I think @karlt's proposal means that an event now has a `scheduled time`, which is the time to consider when inserting the event in the timeline, and an `effective start time`, used to compute the values. If `scheduled time` < `currentTime` on insertion, then `effective start time` is `currentTime`. Otherwise `effective start time` is `scheduled time` (that's the normal case). In effect, this seem to remove a class of discontinuities, where an set of events would have been continuous if `currentTime` on the main thread was not lagging behind.

In the example from https://github.com/WebAudio/web-audio-api/issues/1712#issuecomment-420524694, the curve is now continuous, but the values are not what they appear to be: the affine function's slope is now much steeper. If other curves are being scheduled at the same time, on other parameters or nodes, this can be a problem. 

It's unclear to me that one is better than the other, but it's also unclear that I've understood the proposed solution.

**Comment by hoch** [comment]
Hmm. I thought we're clamping, but it can't find the reference in the code. I don't think Chrome is doing the clamping for the curve automation afaik. @rtoy would know better.

**Comment by padenot** [comment]
It's unclear if this is changeable at all, then.

**Comment by padenot** [comment]
Yes, it's been like that for a long time it seems.

**Comment by rtoy** [comment]
Teleconf: the duration is set as if the time was currentTime.  So effectively the curve is moved from the given time to the clamped currentTime.

**Comment by rtoy** [comment]
The current spec says 

> The amount of time in seconds (after the startTime parameter)...

And the `startTime` parameter is explicitly clamped to `currentTime`. I think there's nothing to do here, unless we really want to make it explicit.

**Comment by rtoy** [comment]
Adding back WG review for a final review.  I don't think there's anything that needs to be changed, but want to hear other opinions.

**Comment by hoch** [comment]
Conclusion from WG Telecon: The spec is sufficient as is. Nothing to do here.
