### ISSUE TITLE
PannerNode constructor should enforce attribute constraints

### ISSUE THREAD

**Issue by Manishearth** [WebAudio/web-audio-api#1728]
https://webaudio.github.io/web-audio-api/#pannernode

Things like the [coneOuterGain](https://webaudio.github.io/web-audio-api/#dom-pannernode-coneoutergain) have setters that enforce that they're within a range, but the constructor doesn't. It probably should (or otherwise define this behavior as a clamp).

**Comment by Manishearth** [comment]
While we're here, perhaps we should also clamp rolloffFactor if the distance model is changed to linear.

**Comment by rtoy** [comment]
Thanks for the report.  Yes, `coneOuterGain` in the constructor should do something if you're setting it out of range.  Not sure if we should fail to construct or just clamp the value.

For the `rolloffFactor`, in https://webaudio.github.io/web-audio-api/#dom-pannernode-rollofffactor, we already give nominal ranges for each distance model and say that the rolloff should be clamped to the nominal range.  Were you expecting more?

**Comment by Manishearth** [comment]
Oh, I misunderstood how the rolloff thing works. Thanks

**Comment by rtoy** [comment]
Teleconf result:  constructor should throw error if coneOuterGain is outside the range.  Similarly, for a negative rolloffFactor.

**Comment by padenot** [comment]
Legacy.

**Comment by Manishearth** [comment]
Also: The spec says that both maxDistance and refDistance should throw for non-positive values, however [the test](https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/webaudio/the-audio-api/the-pannernode-interface/panner-distance-clamping.html) and Chrome's impl seem to think that refDistance should be allowed to be zero. Firefox just doesn't throw on these setters. Should we change the spec or the impl?

**Comment by rtoy** [comment]
The documentation for the [distance formulas](https://webaudio.github.io/web-audio-api/#enumdef-distancemodeltype) have explicit sentences about what happens when dref (refDistance) is 0 for the inverse and exponential models. I think the linear model is still well-defined if refDistance is 0.. thus, refDistance is allowed to be zero.  The referenced test passes when refDistance = 0. 

We should probably rephrase the text to be more explicit and say refDistance must be in [0, inf). 

For [maxDistance](https://webaudio.github.io/web-audio-api/#dom-pannernode-maxdistance), an error is thrown when it is non-positive.  maxDistance is only used for the linear model, and with a quick inspection, it seems the equation is still well-defined if maxDistance is 0.  Maybe 0 should be allowed?  Or maybe not allowed?  In either case perhaps we should explicitly say the valid range is [0, inf) or (0, inf).

**Comment by rtoy** [comment]
Actually, @Manishearth, can you open a new issue for maxDistance/refDistance instead?  That would be really great if you could.

Closing again.

**Comment by Manishearth** [comment]
Opened https://github.com/WebAudio/web-audio-api/pull/1736
