### ISSUE TITLE
Unclear what value is returned by AudioParam.value

### ISSUE THREAD

**Issue by tszynalski** [WebAudio/web-audio-api#1788]
Should `AudioParam.value` return the computed value for the parameter at `AudioContext.currentTime`? The spec is not clear on this:
https://webaudio.github.io/web-audio-api/#AudioParam-attributes

I know this issue was under discussion before (e.g. here: https://github.com/WebAudio/web-audio-api/issues/318), but I'm not sure which definition was approved.

Thanks in advance.

**Comment by hoch** [comment]
Even though the spec is not perfectly clear, I think this captures the resolution of the issue:
https://github.com/WebAudio/web-audio-api/issues/318#issuecomment-172217060

Do you see any interoperability problem here (e.g. different values across browsers)?

**Comment by karlt** [comment]
Gecko has not implemented this properly yet, partially because the spec keeps changing.

> Even though the spec is not perfectly clear, I think this captures the resolution of the issue:
> [#318 (comment)](https://github.com/WebAudio/web-audio-api/issues/318#issuecomment-172217060)

I'm not clear what the difference is between *automation* and *intrinsic* value.  I would expect the *automation* value to be the value from automation methods, which is what the *intrinsic* value is, but the comments there imply there is a difference.

Before https://github.com/WebAudio/web-audio-api/pull/1257, the spec stated:
```
When read, the <code>value</code> attribute always returns the <em>intrinsic</em> value for the current time.
```
This meant that what the getter returned (*intrinsic* value) was consistent with what setting the value changes.  We were intending to implement this in Gecko.

After that change, the value specified for the gettter depends on what has happened most recently.
If a particular control message has been received more recently than the setter was called, then the value returned is the *computedValue* from the previous rendering, which is at a time *before* `currentTime`.  Otherwise the value returned is the value set, which is an *intrinsic* value.

IOW the value returned may or may not, depending on the situation, include the component from inputs connected to the AudioParam.

I do not intend to implement this in Gecko.  The inconsistency is not helpful.
Sending messages continually for every AudioParam with a connected input is also too expensive.  If a client wants to read from the inputs, they can connect a ScriptProcessorNode, AnalyserNode, or AudioWorkletNode.

**Comment by tszynalski** [comment]
Is [this comment](https://github.com/WebAudio/web-audio-api/issues/318#issuecomment-172217060) really the final version? That's not the feeling I get from the discussion below it.

As a developer, my first-instinct expectation would be that 

```
// ...ramp in progress...
AudioParam.setValueAtTime(AudioParam.value, AudioContext.currentTime);
```
should preserve continuity. What it feels like I'm doing here, is that I'm taking the current automation value and setting it as the "constant" value. I would also expect it to automatically cancel the ongoing ramp (right now I believe the ramp is spec'ed to just go back to ramping after the setValue call, not sure why you'd ever want that). I know I can achieve the same effect with `cancelAndHoldAtTime(currentTime)`, but I believe the above should work, too.

Regarding the question about browser differences, Chrome's `AudioParam.value` returns something close to the automation value, but far enough that doing `AudioParam.setValueAtTime(AudioParam.value, AudioContext.currentTime);` in the middle of a ramp will cause discontinuity artifacts. Firefox always returns the initial "stable" value (even after the ramp has completed!), which makes the getter completely useless.


PS. I'm gonna come clean – after spending some time with the spec, I don't really understand the difference between _intrinsic_ and _computed_ value. Intrinsic value is, I assume, equivalent to the automation value. 
And according to [this](https://webaudio.github.io/web-audio-api/#computation-of-value), "computedValue is the sum of the intrinsic value and the value of the input AudioParam buffer".
I tried to understand what "input AudioParam buffer" means, but I wasn't able to. It can't be the audio stream that you connect to a gain node because you wouldn't sum the audio stream with the intrinsic value. I think having an example in the spec would go a long way.

**Comment by hoch** [comment]
This is AudioParam's `.value` getter definition:

> Getting this attribute returns the contents of the [[current value]] slot, which maintains the value of this parameter at the conclusion of the most recent render quantum on the audio rendering thread, or the most recently assigned value if no rendering has taken place.

So it is the most recent _computedValue_. The question here is what "the most recent" means.

From my perspective, the intrinsic value is a value calculated by AudioParam's own operation. (e.g.  setter and automations) This excludes parameter modulation from the external source.

To answer the question in the previous comment, it is impossible to avoid discontinuity from `AudioParam.setValueAtTime(AudioParam.value, AudioContext.currentTime)`.

The definition of `currentTime` goes: 
> "This is the time in seconds of the sample frame immediately following the last sample-frame in the block of audio most recently processed by the context’s rendering graph."

So the value you get from `currentTime` is a time position in the past. Similarly, the value you get from `AudioParam.value` is also a computed value in the past. So when you schedule a data point with values from the past, there will be a conflict with ongoing automation in the rendering thread.

**Comment by tszynalski** [comment]
Thank you for the explanation. I think the spec would be clearer if it said "computed value" instead of "[[current value]]". Any chance this can be changed?

I'm not sure I understand why `currentTime` is supposed to be in the past. The definition you quoted doesn't say it's the time of the last processed frame – it says it's the time of the frame **following** the last processed frame. So it looks like it is the frame currently being processed, and on the face of it, I don't see why I shouldn't be able to modify this frame. If this is wrong, I'd be grateful if you would set me straight.

**Comment by karlt** [comment]
> I tried to understand what "input AudioParam buffer" means, but I wasn't able to. It can't be the audio stream that you connect to a gain node because you wouldn't sum the audio stream with the intrinsic value.

It is intended to describe the signal from an AudioNode connected to the
AudioParam.  e.g. `modulationGain.connect(hfo.detune)` at
https://www.w3.org/TR/2018/WD-webaudio-20180619/#example-6f281013

> I'm not sure I understand why `currentTime` is supposed to be in the past. The definition you quoted doesn't say it's the time of the last processed frame – it says it's the time of the frame **following** the last processed frame. So it looks like it is the frame currently being processed, and on the face of it, I don't see why I shouldn't be able to modify this frame.

It is a frame that may be currently being processed.
The processing happens in parallel with the JS interacting with the AudioContext.  If the processing of that frame has already begun, then JS cannot change that processing.

**Comment by karlt** [comment]
> > Getting this attribute returns the contents of the [[current value]] slot, which maintains the value of this parameter at the conclusion of the most recent render quantum on the audio rendering thread, or the most recently assigned value if no rendering has taken place.
> 
> So it is the most recent _computedValue_.

That is the part that is inconsistent because it describes the getter sometimes returning a value for a quantity that is different from what the setter would modify.  However,
```
Setting this attribute has the effect of assigning the requested value to the [[current value]] slot
```
which means that the getter may return that value, which is an *intrinsic* value, not a `computedValue`.

**Comment by tszynalski** [comment]
@karlt  Thanks for the explanation about AudioNodes connected to an AudioParam – I've got it now. I think the spec would benefit from better phrasing. For example, would it be possible to have it say the following?

https://webaudio.github.io/web-audio-api/#computation-of-value
> 2. The _computedValue_ is the sum of the intrinsic value and the value of the input AudioParam buffer. For example, it is possible to connect an OscillatorNode as an input to a `GainNode.value` parameter in order to introduce oscillations in the gain value (note this is not the same as the usual practice of connecting a OscillatorNode to a GainNode in order to change its signal level). In such a case, the output of the OscillatorNode is the _AudioParam input buffer_ and the sum of the intrinsic value and the input buffer is the _computedValue_.

**Comment by tszynalski** [comment]
@karlt 
Gotcha, so the .value getter returns the intrinsic value. But right now the [definition of AudioParam.value ](https://webaudio.github.io/web-audio-api/#dom-audioparam-value) doesn't say that. Instead it says something about the "[[current value]] slot", which is not helpful, especially that if you click the [[current value]] link, you won't get any useful definition, either.

Couldn't the description say something like this?

> The [[current value]] slot stores the current intrinsic value, i.e. it takes into account any automation functions in progress, but does not take into account any `AudioNodes` connected to the `AudioParam`.

Secondly, is [this part of the spec](https://webaudio.github.io/web-audio-api/#computation-of-value) correct in light of what you said?

> The computedValue is the sum of the intrinsic value and the value of the input AudioParam buffer. **When read, the value attribute always returns the computedValue for the current time**.

**Comment by hoch** [comment]
@tszynalski Thanks for your suggestion, but what we currently have doesn't seem to be a problem:

> 2. The computedValue is the sum of the intrinsic value and the value of the input AudioParam buffer. When read, the value attribute always returns the computedValue for the current time.

I prefer to clarify the confusion by phrasing things better, not by enumerating examples.

The real problem here is we have different implementations between Chrome and FireFox, but I find returning the more recent computed value much more useful. I understand that the operation can be expensive and slow depending on the implementation (posting a task), but also we can't just change that without evaluating potential breakage out there. Querying this value to update the visual counterpart is a quite common practice in many apps, so we have to think about that.

**Comment by tszynalski** [comment]
@hoch 

As I see it, the problem is that the spec is difficult to understand. It could be made better by adding an example to describe the idea of connecting AudioNodes to AudioParams (as opposed to other AudioNodes), which is necessary to understand the difference between intrinsic value and computedValue.

Phrasing things better does not preclude using examples. In fact, the spec as it is now uses a fairly large number of examples (just Ctrl+F "example" to find out) in addition to formal descriptions. Examples are much easier to understand than dry, abstract algorithms. In fact, I think the only way to understand something abstract (let's say, function limits) is to come up with some quick example in your head. If the spec is supposed to be readable by developers (not just a handful of browser devs), clarity should be one of the goals. At least that's what I had in mind when I submitted my suggestion.

**Comment by hoch** [comment]
The example in this case kind of tricky because it makes the prose less normative. What rather we need is a clear definition of `intrinsic value`, `computed value`, and `current value`. IMO if the spec lacks clarity, it needs to be solved by a normative way first. Examples are generally better to be wrapped under "non-normative" or "informative" note.

> In fact, the spec as it is now uses a fairly large number of examples (just Ctrl+F "example" to find out) in addition to formal descriptions. 

It doesn't necessarily mean that the practice is recommended. There other specs that are succinct, precise and also normative - and that should be our goal in fact. With that said, I really appreciate your contribution here and perhaps you could help us define those terms better.

Still we have an interop problem on our hands and I don't have a clear answer for that.

**Comment by tszynalski** [comment]
@hoch 
I think I just see it differently. My experience writing human-readable technical texts tells me there should be a general description (which is the one that establishes the norm of behavior), but it should be followed by an example to help people instantly grasp the idea. Absent that, readers will just have to come up with their own private examples as they try to grok the description.
I don't care if the example is in a separate box labeled "EXAMPLE", "INFORMATIVE" or "UNICORNS", as long as it's there.

Regarding making the normative part clearer, I've already suggested a possible change above:

Current version:

> Getting this attribute returns the contents of the [[current value]] slot, which maintains the value of this parameter at the conclusion of the most recent render quantum on the audio rendering thread, or the most recently assigned value if no rendering has taken place.

I suggest adding this sentence:

> The [[current value]] slot stores the current intrinsic value, i.e. it takes into account any automation functions in progress, but does not take into account any AudioNodes connected to the AudioParam.

**Comment by hoch** [comment]
I guess we agree to disagree here.

But we still have not answered the second question: Chrome gives a computed value, but FireFox gives you an intrinsic value. Before writing a prose or examples, we have to make a decision. Like I mentioned, this would be a breaking change and we can't push it out without knowing what's out there.

@padenot WDYT?

**Comment by tszynalski** [comment]
@hoch Ah, so you guys still don't know whether it should return the intrinsic or the computed value? That explains the contradictory language in the current WD.

Actually, Firefox doesn't really return any useful value:
https://bugzilla.mozilla.org/show_bug.cgi?id=1438353

I guess .value getter should return the intrinsic value, just because the setter sets the intrinsic value (any asymmetry here would be totally unacceptable), but there should be a separate .computedValue property that gets you the final value (e.g. when you want to do a real-time visualization of some AudioParam).

**Comment by padenot** [comment]
I don't like the asymmetry, but I suppose that having the final value (downmixed input audio + parameter value from the timeline) can be useful maybe? 

Synchronously querying the rendering thread for a value can probably be made efficient if we really want, but I'd rather avoid, it's not amazing.

**Comment by hoch** [comment]
> any asymmetry here would be totally unacceptable

AudioParam is a bit different because basically you're peaking a value from another thread. The formal asymmetry doesn't make much of sense when your value is flaky anyway. If that's the case, making it useful for developers seems sensible. Like I mentioned, many projects are already using `.value` to update UI elements.

Also the meaning of _the intrinsic value_ is actually quite blurry because the setter uses `setValueAtTime()` method internally. So the value-setting operation is not done by a regular ECMA abstract operation, but is done by WebAudio's automation system.

@padenot I am slightly confused on your last comment. So the final value for `.value` getter is useful, but you'd rather avoid?

**Comment by hoch** [comment]
> Backward compatibility may not be that big of a problem -- how many of those apps you mentioned have AudioNodes connected to AudioParams?

Once again, such change will have to go through the browser vendor's launching process along with the extensive research on potential breakage.

**Comment by tszynalski** [comment]
In 2017, you guys changed it from intrinsic value to (vaguely defined) computed value. Did you worry about backward compatibility then?

**Comment by hoch** [comment]
If WG somehow underestimated such breaking change in the past, that would be a mistake. However, that mistake in the past doesn't automatically allow us to do the same mistake today.

I hope this discussion is not heading to "pointing fingers". I am trying to support the discussion as I can by providing surrounding facts. Also now it seems like this issue is about changing the API rather than make some clarifications.

**Comment by tszynalski** [comment]
Perhaps the people who were in charge in 2017 didn't think the issue to be as serious as you paint it? 

Anyway, I don't have much else to add besides the arguments I gave above. If the W3C finds the backward compatibility problems so enormous as to excuse having a setter that sets a different value than is returned by the getter, I guess that's life. Won't be the first pitfall in the Web Audio standard.

**Comment by rtoy** [comment]
There's a fine line between a bug in the implementation and a feature change.  If Chrome made this change in 2017 it was probably considered a bug in the implementation, especially if it had been in the spec for a long time or the spec was clarified.  If the change were to be made today, perhaps a different choice would be have been made.  Or it might depend on the phase of the moon or the CL author's mood on that day.

**Comment by padenot** [comment]
> @padenot I am slightly confused on your last comment. So the final value for `.value` getter is useful, but you'd rather avoid?

Yeah my comment was not too precise. I could see that having `value` returning the last computed param value be useful, but it's unclear that this out-weights the usefulness, especially considering the fact that someone that needs this particular feature can do it on their own, paying the cost only if needed.

**Comment by rtoy** [comment]
Teleconf:  the value should be the value from the automation timeline, ignoring any values from any input to the audioparam.

**Comment by rtoy** [comment]
I think this basically means updating ``[[current value]]` to mean the intrinsic value (which is already kind of defined but not as a dfn, which we should do) and also updating the algorithm for rendering a graph that `[[current value]]` is updated with the intrinsic value and not the computed value.
