### ISSUE TITLE
parameters and return value of processorCtor parameter to AudioWorkletGlobalScope.registerProcessor()

### ISSUE THREAD

**Issue by karlt** [WebAudio/web-audio-api#1839]
AudioWorkletGlobalScope.registerProcessor() is declared in webidl with the processorCtor parameter of type VoidFunction.
https://webaudio.github.io/web-audio-api/#audioworkletglobalscope
"The VoidFunction callback function type is used for representing function values that take no arguments and do not return any value."
https://heycam.github.io/webidl/#VoidFunction

However, "the construction of an AudioWorkletProcessor" requires calling Construct() with a list of options, and so the processorCtor would be called with an argument.

Further, the return value is from the constructor is used in the Construct algorithm, and so I'm not clear how a missing return value would be enforced or ignored.
https://tc39.github.io/ecma262/#sec-construct
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new

**Comment by karlt** [comment]
Blink declares `callback BlinkAudioWorkletProcessorConstructor = any (any options);`
https://chromium.googlesource.com/chromium/src/+blame/52dded60a7c8b0c66637c35a9450744d99ef1581/third_party/blink/renderer/modules/webaudio/audio_worklet_global_scope.idl#21
which is the same as Function.
https://heycam.github.io/webidl/#Function
So I guess s/VoidFunction/Function/ is appropriate here.

**Comment by karlt** [comment]
Oh, I missed the `...` in Function.
Function has multiple arguments, and so I guess it is better to have something similar to the blink webidl to clarify that only one parameter will be used.

**Comment by hoch** [comment]
I can add `callback AudioWorkletProcessorConstructor = any (any options)` in the IDL of AudioWorkletGlobalScope.

**Comment by bzbarsky** [comment]
Why is the return type of this callback `any`?  What is the actual processing model?  

In https://webaudio.github.io/web-audio-api/#instantiation-of-AudioWorkletNode-and-AudioWorkletProcessor second algorithm block (which is not directly linkable, sadly) step 6 certainly seems to make assumptions about the return value not just being `any` but being an `AudioWorkletProcessor` instance, right?  As the spec is written, even with this PR, that's not at all guaranteed.

Also, the manual `Construct` call returns a completion, not just a value.  Importantly, it does NOT throw an exception in the sense that IDL understands exceptions.  So the way the spec is written right now, exception handling is undefined.  It should probably use https://heycam.github.io/webidl/#construct-a-callback-function instead of ES `Construct` to turn abrupt completions into exceptions as needed.  See https://html.spec.whatwg.org/multipage/custom-elements.html#concept-upgrade-an-element step 8 for an example.
