### ISSUE TITLE
Why AudioWorklet disables Atomics.wait?

### ISSUE THREAD

**Issue by orange4glace** [WebAudio/web-audio-api#1848]
I didn't test on other browser but only Chrome and it might only matter on Chrome.

As [AudioWorklet SharedArrayBuffer model example](https://github.com/GoogleChromeLabs/web-audio-samples/tree/master/audio-worklet/design-pattern/shared-buffer) shows, a separate `Worker` thread produce audio data and `AudioWorklet` thread consumes the produced data continuously.
But this sample code has race condition [issue](https://github.com/GoogleChromeLabs/web-audio-samples/issues/177) when producing audio data on `Worker` thread takes heavy time for some reason and `Worklet` thread tries to consume before the data is produced.
Which means `Worklet` should check whether data is ready or not. Two possible solutions are (as written on [here](https://github.com/GoogleChromeLabs/web-audio-samples/issues/177#issuecomment-479721892)

1. Send message when output buffer is ready via MessagePort
2. Block AWP until output buffer is ready (Atomics.compareExchange or spin-lock)

But both of them seems to have a problem.

1. Main UI thread must get involved as a relay in message passing between AWP and DWG. As a result, there might be a delay issue when UI thread is kinda busy.
2. Performance issue

Glitching is not a problem in here since glitching has already happened when consumer suffers lack of data. Rather than, this such unnatural solution to solve this situation makes me feel bad. If `Atomics.wait` can be used in `Worklet` thread, it can just wait using `Atomics.wait` until data is ready and everything will looks fine.

Or, is there any technical / design issue which prevents `Atomics.wait` to be enabled on `AudioWorklet`?

**Comment by hoch** [comment]
By design, [AudioWorkletProcessor](https://webaudio.github.io/web-audio-api/#audioworkletprocessor) must be synchronously processed by "rendering thread". If the user code in the processor blocks the thread (like `Atomics.wait`), it will stall the entire graph rendering loop affecting the other processors' progress. That's why AudioWorkletGlobalScope does not have `Atomics.wait`.

For real-time audio use case, synchronously blocking the thread is generally not a good idea. I'll update my example with a better shared memory model.

**Comment by padenot** [comment]
<http://www.rossbencina.com/code/real-time-audio-programming-101-time-waits-for-nothing> is the classic reference for this kind of question, but the bottom line is: one should never ever ever wait in a real-time audio callback, so we disabled `Atomic.wait`, because there is no good reason to have it, and not having it clearly sends a message to authors, they if they are trying to wait on anything, they are doing something wrong (of course they can busy-wait, etc., it's not foolproof).

**Comment by JohnWeisz** [comment]
> For real-time audio use case, synchronously blocking the thread is generally not a good idea.

 > one should never ever ever wait in a real-time audio callback, so we disabled Atomic.wait [...] if they are trying to wait on anything, they are doing something wrong

None of this applies to OfflineAudioContext though, right? This is probably just an oversight, but I think it should be pointed out that there is probably no reason whatsoever to disable `Atomics.wait` in this case (no reason other than the consistency of available APIs, that is).

-----

Consider the following problem: it's well known that OfflineAudioContext can process audio much faster than real-time, and that the effective rate at which audio blocks are processed can change pretty much randomly as far as implementations are concerned. Thus, I believe reliable cross-thread offline audio processing is essentially impossible without a blocking wait at one point, such as when buffer underflow occurs, because there are no _guarantees_ about cross-thread processing completion whatsoever (not to mention the additional latency we have with the long buffer).

If there is nothing else to process on the audio rendering thread, it won't wait for cross-thread processing to finish by itself, it will just rush to the next block as soon as computationally possible. Granted this can be somewhat alleviated with a longer buffer, but only for so long before the offline rendering thread rushes through too many blocks for cross-thread processing to keep up. At this point, the rendering thread must _wait_ for cross-thread processing to finish (or replenish the buffer), otherwise the result will contain dropouts or repeats (depending on how the cross-thread buffer is implemented).

_Note: this issue won't happen with a real-time AudioContext of course, because it will wait a predetermined amount of time before processing the next block, which gives us a clear window for cross-thread audio processing, but this is not the case in offline rendering mode._

To address this, I think cross-thread audio processing should be accepted and considered a possible bottleneck in offline rendering mode, and consequently `Atomics.wait` should be allowed in OfflineAudioContext.

The current workaround, as also hinted at by @padenot earlier, is a busy wait of course, which solves the problem nicely, but comes with the well-known downsides.

Any thoughts?

**Comment by kawogi** [comment]
Does this also apply to the WASM instruction `memory.atomic.wait`? Then it might be impossible/impractical to use muti-threaded code in a worklet at all. Even the compilation of an empty Rust program emits those commands an I'd guess a lot of library code (Mutex, Memory management, …) will do this as well.
Speaking for me: I'd rather experience an audible glitch than having my program crash randomly.

**Comment by sotrh** [comment]
Is there a work around for this? My audio worklet will crash periodically complaining that `Atomics.wait: cannot be called in this context`. I'm not calling atomics directly, I'm using a library called `futures-channel` to send events from the main thread to the audio worklet.

**Comment by padenot** [comment]
There is no work around, it is very much intended. Your library isn't thread safe and shouldn't be used in an `AudioWorkletGlobalScope`.

**Comment by JohnWeisz** [comment]
While I don't want to encourage it much, as far as your calling code is concerned, `Atomics.wait(array, offset, value)` is basically equivalent to a busy wait from a code execution flow POV:

```
while (Atomics.load(array, offset) !== value);
```

It's not the exact same thing of course, mainly because a busy wait is much less efficient (though also faster to pick up the value change in a microtiming environment, given it doesn't have to go through OS thread scheduling AFAIK), and you typically **don't want to do this in a real-time AudioContext** (fine for an OfflineAudioContext though, if you know what you are doing).

So if you really need it, you can polyfill as such, but again, you don't want to do this in a real-time AudioContext.

https://timur.audio/using-locks-in-real-time-audio-processing-safely is a good read on a mix of audio processing and multithreading.

**Comment by sotrh** [comment]
> Your library isn't thread safe and shouldn't be used in an AudioWorkletGlobalScope.

Not my library @padenot , but good to know. Also, thanks @JohnWeisz for the article. It feels like it's really hard find me to find literature on this topic.

**Comment by padenot** [comment]
http://www.rossbencina.com/code/real-time-audio-programming-101-time-waits-for-nothing contains 99% of what you need to know, but for most intents and purposes it can build down to do: do not do anything in your callback that can has a duration you don't control.

If / when you're a real pro, like Timur is (linked above), then you can start doing fancy stuff and break rules.

**Comment by Nearoo** [comment]
If I may offer, unsolicited, some perspective from a less experienced DSP developer.

I understand & appreciate the advice of that article @padenot . However, making the audio thread wait-free might not always be the first priority when getting started with DSP development, and just trying to make something run. I would guess that many people that run into the `Atomic.wait` issue come from compiling their code to native first, then trying to port to the web, then noticing that they need a major refactoring before they can do that. 

Of course, I agree that they _should_ do that. But if they didn't _have_ to do it, it could make porting native code to the web significantly less painful. It would allow them to refactor to wait-less only once they're ready - just like in the native case. 😄 

I also think that the mindset: "We know what you want, and it's not that, so we made it impossible" can be slightly dangerous, as there might still be cases where it's either needed or more practical do it regardless, due to different priorities of the project, or due to a technical reason somewhere in the techstack. 

Just my 2¢, no offense, I love what you guys are doing here.

**Comment by Vanilagy** [comment]
@JohnWeisz Ah, cool to learn I'm not the first to suggest this.

My current busy-waiting-based solution achieves excellent performance, but it does definitely spend a good amount of time busy-waiting. This is because it is synced with a video rendering and encoding thread, which is typically the bottleneck (video processing runs at ~10x real-time). But there are cases where audio rendering is slower, and there, zero time is being spent busy-waiting with my solution.

But hey, it's maximally performant in the sense that it's not a bottleneck. Only hogs the CPU more than I'd like. However, since it's in a separate thread, the effect of this is typically not noticable.
