### ISSUE TITLE
Obtain an AudioBuffer from a MediaElementAudioSourceNode

### ISSUE THREAD

**Issue by TobyMellor** [WebAudio/web-audio-api#1872]
**Describe the feature**
The ability to obtain a buffer source from an audio element. Even when an audio element is fully loaded, it's not possible to schedule samples of audio using a MediaElementAudioSourceNode.

https://groups.google.com/a/chromium.org/forum/?fromgroups#!topic/chromium-html5/HkX1sP8ONKs

https://stackoverflow.com/questions/11292076/load-audiodata-into-audiobuffersourcenode-from-audio-element-via-createmediae

**Comment by TobyMellor** [comment]
For context, I'm trying to precisely schedule audio that comes from EME https://developers.google.com/web/fundamentals/media/eme.

e.g. Using https://developer.spotify.com/documentation/web-playback-sdk/ or Apple's Player

**Comment by rtoy** [comment]
I think the third answer on the stackoverflow question will do what you want: connect a `ScriptProcessorNode` or `AudioWorkletNode` to the output of the `MediaElementAudioSourceNode` and capture the audio data to do whatever you want with it, including making an `AudioBuffer` for use with an `AudioBufferSourceNode`.

Not sure how useful that will be since you don't have a whole lot of control over when you get the data so the captured data won't be sample accurate, even if the `AudioBufferSourceNode` will give you sample-accurate timing.

**Comment by TobyMellor** [comment]
Thank you. Yes I'm not sure if this would work in my case.

Perhaps EME support for an AudioBuffer could be considered? Or some implementation of `setMediaKeys`? I can't find any examples at all of where WebAudio was used with EME :(

**Comment by rtoy** [comment]
There is work on a new decoding API and that would presumably include support for EME.  The shape of the API or even all the capabilities aren't known yet; we're still in the early stages.  But I think it will be handled by the media API and not WebAudio.  But certainly the needs of WebAudio should influence the decoding API.

**Comment by rtoy** [comment]
This needs to be reviewed by the group.

**Comment by rtoy** [comment]
Teleconf:  Too late to do anything in v1.  Punting to the next version.

**Comment by mdjp** [comment]
This will not be considered for V2, as it is better placed in webcodecs.

https://github.com/WICG/web-codecs
