### ISSUE TITLE
accessing parent scope from within a AudioWorkletProcessor

### ISSUE THREAD

**Issue by Foeg** [WebAudio/web-audio-api#2037]
Apologies if this is the wrong forum. I have an issue but it is really a question.

I am using audioWorklet.addModule to add some audio processing to 
a webrtc stream.
It all works as advertised - thank you.

However after doing some processing on the audio, if conditions are met
I want to sent the audio off (via tcp/udp) to be further processed.
I was planning to use XMLHttpRequest() but I get a 
"XMLHttpRequest is not defined" error
when invoked from within the process() .

Probably just my javascript newbieness, but how to I get access
to the scope of the parent where XMLHttpRequest is defined
from inside my AudioWorkletProcessor

Happy to hear alternative suggestions.

**Comment by rtoy** [comment]
You should ask somewhere else since this is not a spec issue.

I think, however, that the right way to communicate something from the process() method is to use the [message port](https://webaudio.github.io/web-audio-api/#dom-audioworkletprocessor-port) from the `AudioWorkletProcessor` to send an appropriate message to the main thread to do what you want.  The main thread can use the port to send the data back to the processor as needed. (Or you could possible used a `ShareArrayBuffer` to pass the data back to the processor.

**Comment by Foeg** [comment]
Thanks.
