### ISSUE TITLE
AudioBufferSourceNode: Allow for (small) negative offsets in Start() when subsampling

### ISSUE THREAD

**Issue by collares** [WebAudio/web-audio-api#2047]
This refers to the discussion at https://github.com/WebAudio/web-audio-api/issues/2032#issuecomment-524111689. In my opinion, @karlt makes a very good point in his comment: Due to subsampling, "interpolating" before the first sample provides (in some cases) meaningful audio content to be played. Consider the case, extracted from buffer-resampling.html, where the buffer's sample rate is 8000Hz and the context's sample rate is 48000Hz. Interpolating, even linearly, before the first sample would give us 5 non-silent samples which improve the audio quality in stitching cases. 

For backwards compatibility, the AudioBufferSourceNode can't start playing before its start time, so I am suggesting an opt-in alternative: Allowing for negative offsets (at least those falling between "buffer sample -1" (silence) and buffer sample 0) would have the desired outcome and address @karlt's audio quality concern. In this way, buffer stitching (as in sub-sample-buffer-stitching.html) could be achieved in a robust manner without linear extrapolation at the endpoints. The spec already allows for offsets a bit before after the last buffer sample (see #2032; this behavior is tested in buffer-resampling.html), so this would merely make the playback symmetric with regards to endpoints.

**Comment by karlt** [comment]
I suspect there may be another way to address this.

> This also begs the question of what does `start(t)` then really mean if there is non-zero output before `t`?

I think that is a key part of the issue here.

Half the energy of the first sample in the buffer is before the time of the first sample and half is after, so centering the first buffer sample on time `t` is always placing half the energy of the first sample before the time `t`.

When the sample rate of the buffer matches that of the AudioContext and `t = n/sampleRate` for integer n, we don't notice any complications because we interpret the first ABSN output sample with its energy centered around the time `t`.  The differences in interpretation show up when "Resampling of the buffer may be performed arbitrarily by the UA at any desired point".

I've been assuming that the first sample in the buffer corresponds to buffer playhead position 0 and that the last sample corresponds to playhead position `buffer.duration - 1/buffer.sampleRate`.  However, it would be just as reasonable to assume that the first sample corresponds to playhead position `1/buffer.sampleRate` and that the last sample corresponds to position `buffer.duration`.  So the question arises whether symmetry would be better. i.e. first and last samples centred at `0.5/buffer.sampleRate` from each end.

There are similar interpretations possible for the time of the first sample rendered by the AudioContext.  Presumably this should be consistent with that of the buffer playhead position.  I have been assuming that the first sample rendered by the context corresponds to time zero.  However, there is a strong case to indicate that this is wrong.

`AudioParam.setValueAtTime(value, startTime)` "Schedules a parameter value change at the given time", so it produces a step function change at `startTime`.  If a PCM representation of this function has a sample point exactly at `startTime`, then that sample point would render a value mid-way between the values before and after `startTime`.  No implementation AFAIK implements `setValueAtTime(newValue, 0)` so that the first sample has a value mid way between the values before and after the change.  Instead, implementations render `newValue` at the first sample.  It is as if the first sample rendered corresponds to time `0.5/context.sampleRate`.

`start(t)` means that initial buffer playhead position (`offset`) will be aligned with time `t`.

For zero `offset`, first buffer sample corresponding to playhead position `0.5/8000`, and first ABSN output sample corresponding to time `t + 0.5/48000`, there will be sufficient output samples after time `t` to capture most of the energy of the first buffer sample.

**Comment by karlt** [comment]
> We know what the delay is, so drop the samples before the delay, and just keep those samples in the new buffer.

Those leading samples are there because they contain some of the energy from the buffer signal.  If delay is measured to the time corresponding to the center of the first buffer sample (This is not the only interpretation of delay.), dropping the samples before the delay when up-sampling would be dropping much of the energy of the first sample.

I would agree though that it is reasonable to expect clients wanting precise output to resample themselves.

**Comment by padenot** [comment]
AudioWG call:

We discussed this, and, bottom line, this sentence:

> I would agree though that it is reasonable to expect clients wanting precise output to resample themselves.

more or less summarize the group's position. In this day and age with `AudioWorklet` available, it's reasonable to expect authors to do something on their own if they want precise control over everything.
