### ISSUE TITLE
Privacy re-review of latest changes

### ISSUE THREAD

**Issue by svgeesus** [WebAudio/web-audio-api#2061]
I [raised an issue for privacy re-review](https://github.com/w3cping/tracking-issues/issues/13) for updated CR of v1.

**Comment by samuelweiler** [comment]
I don't remember much about the earlier review of this spec, so I took a fresh look, and I also looked back at some issues others had raised in the past.

For concerns about access to audio itself, I am content with this spec's overall approach of pushing the problem of user consent to getUserMedia.

I'm more concerned about fingerprinting.  The excuse of "In practice however, this merely allows deduction of information already readily available by easier means (User Agent string), such as "this is Chrome running on an x86"." no longer flies with me - as we see more and more attempts to limit passive FP surface (like the UA string), this may be less relevant.  So I'd like to see you explore a bit more re: what FP'ing is enabled here beyond just sampling rate.  For example: is number of sampling channels a newly exposed item?   And how much does PannerNode reveal about the HW?  https://webaudio.github.io/web-audio-api/#pannernode  (These are just examples.  I'd like your evaluation of the whole lot.)

I would also like to see more efforts to mitigate FP'ing within this spec.  As a specific thing re: sampling rates: I suggest you recommend (rather than just implying) a specific fingerprinting mitigation: reframe the informative "most devices use..." as a specific suggestion that UA's pick one of those rates and hide anything higher behind a permission prompt. I would like to see just one of them picked, and that likely has to be 44kHz (being the least common denominator), but I'll leave that to you.  See this issue for more details:
https://github.com/WebAudio/web-audio-api/issues/1457#issuecomment-552943389

Related to the issue raised in https://github.com/WebAudio/web-audio-api/issues/1486, is there some way to restrict otherwise-unpermissioned output of sounds beyond normal hearing?  As in, if you want sub- or super-sonic output, you need to jump through a hoop?  (So that the exceptional case requires hoops, but the normal case doesn't.)

**Comment by snyderp** [comment]
Seconding @samuelweiler 's note above.

For some solutions the spec could incorporate, this might be a good way of fixing the spec:

https://hal.inria.fr/hal-01527580/document
Laperdrix, Pierre, Benoit Baudry, and Vikas Mishra. "FPRandom: Randomizing core browser objects to break advanced device fingerprinting techniques." International Symposium on Engineering Secure Software and Systems. Springer, Cham, 2017.

The approach is to add _extremely_ small, imperceivable variation to output audio, to prevent it from being used as a FP target.   The paper uses a +/1 .001% change in volume per frame.

Not mentioned in the paper, but the spec could also seed that "small random variation" with a fixed, per session seed, to make sure things were consistent (even at this imperceivable level) w/in sessions, but not between (e.g. FP protections).

**Comment by pes10k** [comment]
@svgeesus just wanted to re-engage on this.  Brave is now shipping a version of whats described in https://github.com/WebAudio/web-audio-api/issues/2061#issuecomment-555095662.

Whether this approach is correct or not, PING is still very interested in finding a solution to the problem, and getting it included in the spec.  How can we help

**Comment by padenot** [comment]
It is known that the fingerprinting is a result of the differences in implementation of floating point computation on different hardware, operating system, operating system versions, and nothing else. Merely updating `libm.so` on a unix system, for example, changes the fingerprint.

If PING wants to find a solution to the problem they could independently confirm that it is indeed the case. Then they could demonstrate how to perform the calculations in a standard way using a software library to make it standard across hardware at least, ideally across OSes as well.

Then they could evaluate the performance impact of their solution.

**Comment by rtoy** [comment]
From Chrome's metrics, 48 kHz is by far the most common rate on Android and Windows.  For MacOSX and Linux, the most common is 44.1 kHz.

If we must choose only one rate, I suggest 48 kHz so that low-end Android devices don't have to resample from 44.1 kHz to 48 kHz.

**Comment by pes10k** [comment]
@padenot Its not PINGs role or responsibility (or, even in PINGs charter) to design new features or to do the kind of measurement you're describing.  PINGs responsibility is to make sure standards are privacy preserving by default and don't allow the kind of harm the current API allows. The kind of cost benefit work you're describing is the responsibility of the working group.

What PING can do though is suggest approaches and evaluate designs that the WG comes up with, to ensure they are privacy preserving.  Some proposals the WG might consider that don't require specifying low-level details like floating point differences are given here, in a similar discussion on canvas based fingerprinting: https://github.com/whatwg/html/issues/5373

More broadly, you might consider any of the following to fix the issue (i'm not endorsing any particular one, just listing them as options):
1. Permission access to APIs that allow for JS introspection (analyzer, serialization)
2. requiring a user gesture / activation for methods for the above
3. add randomization to the output (the original idea for this approach, AFAIK, comes from [1], brave's shipping approach is a bit different [2]
4: preventing audio read back operations in 3p frames

Of particular importance to the spec, it'd be ideal to have a solution that didn't require privacy sensitive users to disable the APIs. This issue isn't to request a specific solution to the problem, but to track conversation for getting a solution into the spec.

1: 3: Laperdrix, Pierre, Benoit Baudry, and Vikas Mishra. "FPRandom: Randomizing core browser objects to break advanced device fingerprinting techniques." International Symposium on Engineering Secure Software and Systems. Springer, Cham, 2017.
2: Brave uses a per-session, per-1p eTLD+1 seed to deterministically but unpredictably alter the volume by [0, .01] percent when read by the analyzer and serialization APIs

**Comment by pes10k** [comment]
@rtoy if the difference in rate 100% aligns with the OS and / or the browser vendor (e.g. it doesn't tell you anything the UA doesn't already tell you), then there isn't additional fingerprinting surface given away, and theres no need to monkey with the rate.  Do you know if this is the case (e.g. the rate can always be predicted by the UA?

**Comment by rtoy** [comment]
People can adjust the sample rate if they want.  Or if they have different audio devices connected.  On my mac, I sometimes switch between 44.1 and 48.  And sometimes use 88.2 and 96 for testing purposes. Chrome's metrics don't tell us what the output device is, but given the metrics, the UA is a pretty good predictor of what the sample rate would be.

Don't think I can give out the actual statistics, but let's say you'd have far better than even odds on getting the rates I mentioned.

**Comment by padenot** [comment]
> @padenot Its not PINGs role or responsibility (or, even in PINGs charter) to design new features or to do the kind of measurement you're describing. PINGs responsibility is to make sure standards are privacy preserving by default and don't allow the kind of harm the current API allows. The kind of cost benefit measurements to choose between privacy-preserving options is the responsibility of the working group.

The point here is that the Web Audio API doesn't add any fingerprinting surface, except for the sample-rate, the channel count and the latency metrics, that are already mitigated in Firefox, and where we could add a provision in the spec. We (Mozilla people) have verified this.

This is what has been said all along. The real problem is arithmetic computations. None of the [solution proposed](https://github.com/WebAudio/web-audio-api/issues/2061#issuecomment-601891152) fix anything, in terms of user fingerprinting.

**Comment by pes10k** [comment]
> are already mitigated in Firefox

If you have a successful mitigation that works, fantastic.  Then the request here is to make that part of the normative / mandatory part of the spec.

> None of the solution proposed fix anything

I don't understand this claim at all.  Preventing untrusted sites from using the API certainly stops those sites from doing fingerprinting; adding noise / randomzation / per session changes to the audio operations causes the API to give slightly different responses on each session on each site, preventing the FP from being used for cross site session linkage, etc.

But, either way, like I said, im not advocating for any particular solution, im noting that the current spec is not private by default, and that the WG should make whatever changes needed to make it private by default

**Comment by karlt** [comment]
> adding noise / randomzation / per session changes to the audio operations causes the API to give slightly different responses on each session on each site, preventing the FP from being used for cross site session linkage, etc.

The same fingerprinting information is available from JS `Math`, for example, and so there is no reduction in fingerprinting from changing the audio signal.

**Comment by pes10k** [comment]
That would depend on the floating point lib used to implement the JS engine, no?  Similarly, if a vendor implemented Web Audio over OpenAL or some other path that could get to different hardware, that would again make the FP issues diverge.

The point being that replicating the same FP surface in additional sources is privacy harm itself (analogous to technical debt).

Further, there are many many fingerprinting libraries that target your API to identify users.  No single party is responsible for making sure every JS API doesn't reveal FP surface, but what WG are responsible for is making sure the functionality they define can't be used to harm people

**Comment by svgeesus** [comment]
@pes10k since the WebAudio implementation in Brave has now diverged from that in Chromium, it would be helpful to see the WPT results for the [Web Audio API testsuite](https://github.com/web-platform-tests/wpt/tree/master/webaudio/the-audio-api) for comparison.

**Comment by samuelweiler** [comment]
> The point here is that the Web Audio API doesn't add any fingerprinting surface, except for the sample-rate, the channel count and the latency metrics, that are already mitigated in Firefox, and where we could add a provision in the spec.

@padenot How has Firefox mitigated those?

**Comment by samuelweiler** [comment]
> People can adjust the sample rate if they want. Or if they have different audio devices connected. On my mac, I sometimes switch between 44.1 and 48. And sometimes use 88.2 and 96 for testing purposes. Chrome's metrics don't tell us what the output device is, but given the metrics, the UA is a pretty good predictor of what the sample rate would be.

@rtoy Thank you!

That answer says to me that sample rate is adding FP surface.  So, unfortunately, yeah, we need some sort of mitigation.  I'm looking forward to hearing what Firefox has done.

**Comment by samuelweiler** [comment]
> Related to the issue raised in #1486, is there some way to restrict otherwise-unpermissioned output of sounds beyond normal hearing? As in, if you want sub- or super-sonic output, you need to jump through a hoop? (So that the exceptional case requires hoops, but the normal case doesn't.)

I broke the above out into a new issue, since I haven't seen it addressed in this thread. 

https://github.com/WebAudio/web-audio-api/issues/2191

**Comment by samuelweiler** [comment]
The sample rate fingerprinting issue is being discussed in https://github.com/WebAudio/web-audio-api/issues/1457.

I created a new issue re: sub- and super-sonic sounds.

I think that leaves the floating point fingerprinting.  What do people think of the mitigation Brave implemented that @pes10k  describes above?   Since we have a worked example with running code, I'm inclined to think that mitigations of floating point library fingerprinting should be required, in some form.

**Comment by rtoy** [comment]
I am opposed to Brave's mitigation of adding a dithering signal.  It makes testing much harder, and makes it impossible to verify that things that are supposed to be exactly equal because now they're never equal.  (Yes, I've written a few tests to verify two approaches give exactly the same results because they should if done correctly.  Those tests would no longer work.)

This only mitigates floating-point fingerprinting from WebAudio.  You can get other fingerprinting by computing stuff with just plain Javascript, especially the special functions.  Timing how long it takes to compute Math.sin as well as the computed value could give information.

**Comment by pes10k** [comment]
@rtoy 
1. All of Brave's "randomness" deterministic, given a per session seed and the eTLD+1 of the top level frame.  It'd be easy enough to check that you get the same output from the same seed (thats what our tests do)
2. Again, im not suggesting that the group adopt Brave's approach (truly!).  I only suggest it (and the other approaches mentioned above) as possibilities other than "require everyone to ship and link to the same libm".  I think Brave's approach is good (I wouldn't have designed it otherwise!) but its very much meant to be in the category of "making fingerprinting significantly more difficult, but possibly not fundamentally impossible".  If we can increase the space between what benign access patterns look like, and what fingerprinters look like, that opens up all other sorts of possible mitigations.
3. Re floating point, JS, other end points, etc

3a. all this is very platform dependent!  Its completely possible to have a different libm / hardware implementation / or combo of both in different parts of your stack, on different browsers.  So while its possible that these all scrape down to the same point, thats definitely not a given (or ensured by the standards)
3b. even in situations where it all scrapes down to the same floating point implementation, its _still_ important to not expose that fingerprinting surface through web audio!  The only way the fignerprinting mess on the web gets addressed is to pay down the technical debt thats been accrued. Getting the surface out of web audio increases the benefit of removing it elsewhere, when those specs come up.  A WG determination that "we know we've added fingerprint surface and we're not going to remove it" damns the platform for the foreseeable future. 

So, TL;DR, the claim isn't "here is the right way to fix the problem", the claim is "there is a well known and [commonly exploited](https://publicwww.com/websites/fingerprint2/) problem in the spec that needs to be resolved, and here are some suggestions you might consider" :)

**Comment by samuelweiler** [comment]
> I am opposed to Brave's mitigation of adding a dithering signal.
...
> This only mitigates floating-point fingerprinting from WebAudio.

Reading between the lines, I understand that you don't like Brave's mitigation, but you find it sufficient for mitigating this bit of FP surface _in WebAudio_, noting that this discussion is specifically about the FP surface in WebAudio, not the FP surface elsewhere in the platform.

I propose, then, that the spec mandate mitigation of floating point fingerprinting (again, in this part of the API), leaving the mechanism unspecified - or perhaps suggesting the Brave mechanism as a worked example.  If other implementers want to do something better than what Brave has done, great.

**Comment by cwilso** [comment]
@pes10k I'm still confused by this issue.  If there are detectable floating-point-exposed fingerprints, why is this not a problem anywhere any floating point calculations are used (e.g., in CSS layout, Javascript math operations, ...), and why isn't the right approach to try to resolve all floating point fingerprinting systemically?  Otherwise this seems like bandaging one small exposure of a systemic issue.  I'm sure I'm missing something about this fingerprinting attack, so please take this as a real question.

**Comment by pes10k** [comment]
The issue is that there can be different floating point implementations in different parts of the system (including web audio), resulting from using specialized hardware for Web Audio operations, to the web audio libs using a different libm than canvas / JS / etc, etc.

So, even if its the case that all thats going on here is detecting floating point implementation (I haven't verified myself, but I can easily believe it), its that different parts of the browser can be using different floating point implementations (and almost certainly will be if any special web audio hardware is being used)

**Comment by cwilso** [comment]
"Special web audio hardware" would have to mean hardware that was performing floating point operations on the data, right?  Like, custom audio hardware that was performing ConvolutionNode operations or something?  I'm unaware if there are any such implementations - maybe @padenot or @rtoy should weigh in there.

**Comment by pes10k** [comment]
I only included specialized hardware as an example because it came up a couple of times in the conversations about sample rate.  The issue of audio using a different FP implementation than WebGL than JS is the general concern.

Study data and resources like panopticlick seem to suggest that there is something else going on too, and its not just duping the JS floating point.  The most recent panopticlick sees ~44 different web audio fingerprints; the [Online Tracking: A 1-million-site Measurement and Analysis](https://www.cs.princeton.edu/~arvindn/publications/OpenWPM_1_million_site_tracking_measurement.pdf) sees 713 different audio fingerprints during just the single study period, which I'd guess,but am not confident is more than just the number of FP implementations.

I'd be very interested to see the data showing that web audio fingerprints and JS fp fingerprints are always 1-1 on all popular platforms and browsers.

**Comment by samuelweiler** [comment]
> why isn't the right approach to try to resolve all floating point fingerprinting systemically?

1. Because defense in depth is not inherently bad.

2. Do you want to see this API held up awaiting such systemic mitigations?

**Comment by cwilso** [comment]
1. I understand defense in depth - I do have a CS degree.  However, I expect a systemic solution to floating point fingerprinting (e.g., mandating one true FP core everywhere) would not only remove all need for different uses of FP to use custom systems, in fact it might be dangerous to USE different solutions, as they add potential attack surface over that of the core FP system.  This isn't defense in depth like "oh, since I have pointer validation I can skip parameter checking".
2. Hey, this API isn't held up - it's shipping across pretty much every engine and browser out there.  As for the spec - personally, I'd say yeah, it is a waste of effort to try to solve floating point fingerprinting in this one place if it's not being solved in all the others, and a systemic change (requiring research into the actual costs there) should be pursued instead.  But then, I'm not an editor anymore, so my willingness (or not) for the spec to be "held up" is not particularly relevant.  I would certainly (as an AC rep) vote to move this spec to REC without resolving this issue.

It seems like the only acceptable solution to you is to mandate that Web Audio use a specific floating point library, or is there something I'm missing?

@pes10k you mentioned web audio fingerprints; I don't understand the details of what those fingerprints are using to identify uniqueness.  Have any pointers to details there?

**Comment by cwilso** [comment]
@padenot, could you take a look at the linked PING issue? (https://github.com/w3cping/tracking-issues/issues/53)

**Comment by rtoy** [comment]
In addition, the spec doesn't give code on how each node must be implemented.  Browsers can implement them correctly but still differ in output slightly due to different approaches, optimizations (SIMD), or even compilers.  

Speaking only for myself, I refuse to have the spec give exact code that must be used to implement each node.

**Comment by samuelweiler** [comment]
> It seems like the only acceptable solution to you is to mandate that Web Audio use a specific floating point library, or is there something I'm missing?

I see many acceptable solutions, some of which are in the "make every browser look the same" category and some in the "make every session look different" category.  

I am content with Brave's mitigation, which is fuzzing ("farbling") the output from WebAudio - the "make every session look different" approach. 

I am also content with trying to nail down the variations so all output looks the same (at least for a given browser on a given platform).  I recognize that there are problems with that approach, but if people prefer it, that's fine, too.

Ultimately, though, we have a working example that avoids floating point fingerprinting (or makes it notably harder) - Brave's fuzzing approach.  Given that, I want to see the spec mandate mitigation of floating point fingerprinting.  Earlier in the thread, rtoy said he was opposed to fuzzing, so I'm okay leaving discretion in the spec as to which approach a given implementation takes. 

(And I recognize that perhaps we have been talking past each other for a bit.  Does this help clarify?)

**Comment by cwilso** [comment]
>I am also content with trying to nail down the variations so all output looks the same (at least for a given browser on a given platform).

Wait, what?  How is this not true already?  A given browser on a given platform will always use the same floating point engine.

In conversation, I believe @padenot commented that fuzzing was defeatable, but I may be misremembering.

**Comment by pes10k** [comment]
@cwilso For myself, the question / concern here is two things:

1. Are we sure that the above is the case?  Its possible that in a browser the JS engine has a statically compiled floating point implementation, while web audio calls out to the system's (or vise versa, or both)!  The response from @padenot (anyone can do anything at anytime) is not wrong, but its not enormously helpful either.  The goal here is still just to understand if WebAudio poses any additional fingerprinting risk that just JS itself.

I think I understand @padenot to be saying that in current WebAudio implementations, there is nothing that touches audio hardware, or other FP-relevant surface.  If it is the case that WebAudio _cannot touch audio hardware_ and so will not be a way of generating fingerprinting surface beyond "browser X version U compiled with flags Y on OS version V and CPU type Z", then thats terrific, and i think we're probably good here. 

But if the API allows (and even seems intended) to call out to audio hardware, then there is significant additional FP risk, and the privacy concern seems well founded and clear.  The response "anyone can do anything anytime" is exactly the kind of thing that makes privacy-people worried!

2. Fingerprinters seem to think there is surface here beyond "browser X version U compiled with flags Y on OS version V and CPU type Z" (again, fingerprint2.js, among others). They could definitely be wrong,  but since they're the ones with (among?) the strongest incentive to be right here, I'm really trying to get certainty from the group that the fingerprinters are wrong.

The questions in https://github.com/w3cping/tracking-issues/issues/53#issuecomment-644249286 are trying to tease that out, though maybe poorly.

**Comment by cwilso** [comment]
1. For the known Web Audio implementations, yes, we're sure they use the default JS floating point.  I think by "touch audio hardware", you mean "pass off processing - e.g. floating point processing - to some other piece of hardware that may perform fingerprintable operations, e.g. due to a custom FP engine" - in which case, no, that is not enabled.  It is technically possible one could write an implementation of web audio that did its FP processing on a video card or other DSP chip, I suppose - but no one has done this, and it's not particularly interesting to enable in modern computing scenarios (i.e., no one builds audio DSP chips anymore for general purpose computers, because it's simply not worth offloading that task anymore.). (Audio processing needs are pretty constant, as there's no benefit in increasing sample rates or bit depth, and the processing cost isn't getting higher in pace with CPUs getting more powerful.)

Web Audio DOES "touch" audio hardware - but it's for input, output, and capability detection.  (Sample rate, e.g.). It doesn't hand off processing (particularly observable processing) to hardware.

So, no one is doing this in current implementations, and there's no impetus to do so.  As to the "anyone can do anything at any time" - this would not be any different than, say, offloading layout calculations to a video card GPU to lighten the CPU load, at which point (iiuc) you might have a fingerprinting issue.  That's probably MORE likely for someone to implement than offloading audio processing.

2. I haven't seen any evidence there is more surface here?

**Comment by samuelweiler** [comment]
>  I haven't seen any evidence there is more surface here?

This sort of flips Pete's question from https://github.com/w3cping/tracking-issues/issues/53#issuecomment-644249286 on it's head - Pete's asking "can you show there isn't new FP surface" and you seem to be asking "show me the surface"?  Each of you is asking someone else to do the heavy lifting.  

Unfortunately, the fingerprinters are the ones with the advantage here - they just have to find surface - they don't even have to understand exactly where it's coming from, and they don't have to share it with anyone else nor explain it to anyone else.  

Those of us to want to mitigate fingerprinting need to cut each other some slack.  We, collectively, have a much harder job than the fingerprinters.

In this case, the path of safety is to assume that there is some FP surface.

Brave have, to their credit, done the heavy lifting of finding a mitigation.

> In conversation, I believe @padenot commented that fuzzing was defeatable, but I may be misremembering.

Showing that it is defeatable would be useful work.  I am inclined, though, to take the mitigation at face value.  As I say [above](https://github.com/WebAudio/web-audio-api/issues/2061#issuecomment-655052277), I'm not asking to mandate this particular mitigation, but since we have a workable mitigation, I am inclined to mandate _some_ mitigation, leaving the choice of which one open.

**Comment by rtoy** [comment]
Speaking as a Chrome developer and not co-chair, I am opposed to Brave's mitigation. It makes testing already harder than it is. (Many of chrome's tests already produce different results between linux, mac, and windows, from **exactly the same code**.)

I am not, however, opposed to some kind of mitigation; I just don't know what it would be.

But requiring some mitigation is acceptable to me if the browser is free to choose an appropriate method.  However, this could make interop much more complicated because browsers will produce different output for exactly the same graph.  You may not be able to hear it, but you can certainly analyze the results and see it.

**Comment by rtoy** [comment]
Sounds like we have a plan.  Basically mandate some kind of anti-fingerprinting but not specifying the method.  Perhaps we could mention (but not require) dithering the output of each node like what Brave does.
