### ISSUE TITLE
decodeAudioData algorithm steps when document is gone?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#2176]
**Describe the issue**
The `decodeAudioData` algorithm doesn't describe what should happen when the document is gone.

**Where Is It**
https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-decodeaudiodata

**Additional Information**
A simple example is if an offline context is created in an iframe.  Then remove the iframe.  Finally, start a decode operation using the offline context.   What is supposed to happen here?

@domenic suggests adding checks for "document is active" or "document is fully active" before resolving promises and before doing any work.

**Comment by hoch** [comment]
For faster triaging, the issue scope should be minimal. However, this problem is not specific to `decodeAudioData`.

Probably it is worth creating an issue for this. I prefer throwing an exception on any operation after the associated execution context is detached from BaseAudioContext.

**Comment by padenot** [comment]
Now that I have restored the "unload a document" bit (https://github.com/WebAudio/web-audio-api/commit/d43886d75ba33219441e375c4062c1cb59646931), then it's easy to do so in the sense we can set a flag somewhere and we have all the promises handy so we can reject them (and can in any case call the error callbacks).

I agree with @hoch that throwing is best. This might be what already happens in Gecko, but I can double check.

**Comment by hoch** [comment]
The only concern is that this might be an observable change because of the exception. This will stop the user-code which was running okay previously.

That said, I am genuinely interested in the use case of this pattern. Why would anyone want to create a BAC from an iframe, detach, and expect the context to work properly? @padenot Have you seen any valid use case of this?

**Comment by domenic** [comment]
Just remember you cannot throw exceptions from promise-returning methods. Instead they should return forever-pending promises.

(They could return rejected promises, but the rejection handlers would not run in almost all cases, because the event loop does not run for inactive documents. The only case where it might run is if the document goes into bfcache then comes out of bfcache, which would continue the event loop where it left off.)

**Comment by hoch** [comment]
Yes, what we meant is to reject the promise with an exception. (right @padenot ?)

So given the circumstances, it seems that returning a pending promise is a right approach. Thanks for the advice @domenic! :)

**Comment by padenot** [comment]
Ok.

**Comment by rtoy** [comment]
Teleconf:  Need resolution of #whatwg/html/issues/2621 to proceed

**Comment by padenot** [comment]
It seems that the current way to do this would be something like this:

> If the document is not fully active, return a rejected promise and abort these steps.

everywhere we create a `Promise`.  This would (I think) work for us. @domenic, is this what you say in whatwg/html/issues/2621 (near the bottom, conversation with boris on March 12th).

**Comment by domenic** [comment]
Yes, that seems right. In particular you'll want to use something like

> If [this](https://heycam.github.io/webidl/#this)'s [relevant global object](https://html.spec.whatwg.org/#concept-relevant-global)'s [associated `Document`](https://html.spec.whatwg.org/#concept-document-window) is not [fully active](https://html.spec.whatwg.org/#fully-active), then return [a promise rejected with](https://heycam.github.io/webidl/#a-promise-rejected-with) a "[`InvalidStateError`](https://heycam.github.io/webidl/#invalidstateerror)" [`DOMException`](https://heycam.github.io/webidl/#idl-DOMException).

I apologize for this being so complicated and so unresolved for so long.

**Comment by padenot** [comment]
Fixed by #2210.
