### ISSUE TITLE
Awkward wrapping of text causes confusion in AudioWorkletProcessor section

### ISSUE THREAD

**Issue by a2sheppy** [WebAudio/web-audio-api#2199]
In §1.32.4.3, the table that describes the arguments to the `process()` method has an issue that may lead to confusion (it did for me).  At the default 100% zoom level in Chrome (at least), the text `outputs[n][m]` appears with a line wrap in between the two indices, so that it looks like this for the  `inputs` parameter:

![image](https://user-images.githubusercontent.com/1641439/80254484-42d1c600-8649-11ea-8031-70de1c63b839.png)

This happens again in the section on the `outputs` parameter.

That unfortunately spaced wrapping means that it's very easy to become enormously confused about how you get multiple channels worth of data out of this...

**Comment by rtoy** [comment]
Interesting.  Do you have a horizontal scrollbar at the bottom?

For me on Chrome, I have to resize the window to get this to happen.  But I've modified my font settings a lot including default size so that might have some effect.  I tried this with Firefox.  I can't get this to happen.  It always keeps the `inputs[n][m]` together on one line.

**Comment by padenot** [comment]
Unclear what CSS property we need to put on this to not break.

**Comment by padenot** [comment]
Apparently we need a zero width joiner here, like so: `&zwj;`.

**Comment by rtoy** [comment]
Or maybe this would work:  https://alligator.io/css/prevent-line-break/

Using `&nbsp;` every where like the last example would be terrible.  The CSS bits look manageable and reusable for other places where we want to prevent a line break.
