### ISSUE TITLE
Implementations disagree about the initial state when creating an AudioContext with user interaction

### ISSUE THREAD

**Issue by foolip** [WebAudio/web-audio-api#2218]
**Describe the issue**

I ran into a difference between implementations while trying to make https://github.com/web-platform-tests/wpt/pull/24405 work on Safari. This code demonstrates the problem:
```html
<!DOCTYPE html>
<button>click me</button>
<script>
window.AudioContext = window.AudioContext || window.webkitAudioContext;
document.querySelector('button').addEventListener('click', () => {
  const audioContext = new window.AudioContext();
  alert(audioContext.state);
});
</script>
```

Test it live here: https://software.hixie.ch/utilities/js/live-dom-viewer/saved/8268

Results:
- Chrome Canary 86.0.4202.0  says "running"
- Firefox Developer Edition 79.0b7 says "suspended"
- Safari Technology Preview 109 says "suspended"

My guess is that Chromium has logic when creating an AudioContext to start it running if possible, while Firefox and Safari do not.

https://webaudio.github.io/web-audio-api/#AudioContext does not say enough to say which behavior is correct, so I can't file implementation bugs or write web-platform-tests. It says:
> An AudioContext is said to be allowed to start if the user agent allows the context state to transition from "suspended" to "running". A user agent may delay this initial transition, to allow it only when the AudioContext's relevant global object has sticky activation.

It seems like this wording was not enough to arrive at interoperable implementations.

**Comment by padenot** [comment]
The [ctor](https://webaudio.github.io/web-audio-api/#dom-audiocontext-audiocontext) for `AudioContext` has the normative behaviour for this, in the form of an algorithm. An `AudioContext` starts `"suspended"`, and immediately tries to transition to `"running"` if `allowed to start`. It stays `"suspended"` otherwise.

**Comment by hoch** [comment]
In this case, the user gesture activates the audio context ("is allowed to start"), so the correct state would be "running". Also the description in AudioContext ctor seems appropriate.

Am I missing something?

**Comment by padenot** [comment]
Creating an `AudioContext` and immediately looking at its `state` attribute must always return `"suspended"`, per spec, regardless of the fact that it is `"allowed to start"`.

The transition to `"running"` happens in a subsequent task: a control message is sent to the render side and a regular task is sent, with the attribute value changing to `"running"` and a `"statechange"` event being fired.

This is a feature: it can be long to open a system level audio stream, and it's important to be able to know how long (our telemetry reports that it can take seconds in the long tail, especially the first time a process opens an audio stream).

**Comment by hoch** [comment]
> A user agent may delay this initial transition

Then the language here is problematic. This means UA can choose NOT to delay the initial transition as well as long as it has the user activation.

You can assume that going through thread hops will cause an arbitrary delay, but it also could have zero delay. I am not fully convinced that Chrome's implementation is incorrect. 

Also it's counterintuitive from the developer's perspective. Consider this code snippet:

```
document.querySelector('button').addEventListener('click', () => {
  const audioContext = new window.AudioContext();
  console.log(audioContext.state);
  const osc = new OscillatorNode(audioContext);
  osc.connect(audioContext.destination);
  osc.start();
});
```

What should this code do? If the immediate state is "suspended", then the rest of code should be silent. Otherwise it'd be very confusing.

**Comment by foolip** [comment]
It sounds like perhaps this is well-enough defined in the spec. Are there any tests that cover this? https://github.com/web-platform-tests/wpt/blob/master/webaudio/the-audio-api/the-audiocontext-interface/suspend-after-construct.html is a fairly elaborate test for the constructor, but it doesn't involve a user gesture AFAICT.

**Comment by foolip** [comment]
I've sent https://github.com/web-platform-tests/wpt/pull/24611 to shed some more light on this.

It looks like Firefox matches the spec in terms of timing. In Chrome, the state can synchronously be "running" which per https://github.com/WebAudio/web-audio-api/issues/2218#issuecomment-658866967 is not right. Safari fails because the API is prefixed, but if one changes that, it never fires the "statechange" event it seems.

**Comment by padenot** [comment]
> Then the language here is problematic. This means UA can choose NOT to delay the initial transition as well as long as it has the user activation.

The fact that it's `"suspended"` on creation in all cases because the state changes needs to happen on its own task because it's an event, so it will happen on another event loop turn. It can be fast or slow (cause by slow hardware or because it's blocked), but `state` can never change without `statechange` being fired in its own task and it starts as `"suspended"`.

**Comment by foolip** [comment]
@hoch https://github.com/web-platform-tests/wpt/pull/24611 exercises precisely this difference in state transition timing in Chrome and Firefox, and fails in Chrome. Can you give that a look before I land it? If the test is right, do you think fixing it in Chrome is straigtforward?

**Comment by hoch** [comment]
> it never fires the "statechange" event it seems.

I just realized this is the case for Chrome, which is incorrect per spec. I thought Chrome fires `statechange`.

> state can never change without statechange being fired in its own task and it starts as "suspended".

Based on the current spec, I have to agree. But [my question above](https://github.com/WebAudio/web-audio-api/issues/2218#issuecomment-658890574) still stands. What happens to the rest of Web Audio code after the immediate state reports "suspended"?

That also brings another question. Why can't a context start from "running" if the user activation is properly registered and the audio infra is completely ready to run? What are we losing by doing that?

>  If the test is right, do you think fixing it in Chrome is straigtforward?

I need to look at the history of Chrome code around this state transition, but the fix would be straightforward. I just need to pipe the transition through a task runner. This part of the code has been quite controversial, so I want to double check details before I make any changes.

**Comment by padenot** [comment]
> Based on the current spec, I have to agree. But [my question above](https://github.com/WebAudio/web-audio-api/issues/2218#issuecomment-658890574) still stands. What happens to the rest of Web Audio code after the immediate state reports "suspended"?

Having a context suspended when calling Web Audio API methods always has been fine. Those method calls will be reflected in the rendering when the render thread is finally running (because the audio system is now started, or because `resume` has been called, or because the context is now allowed to start).

> That also brings another question. Why can't a context start from "running" if the user activation is properly registered and the audio infra is completely ready to run? What are we losing by doing that?

I don't think it's useful to have a special behaviour for this edge case. A context always starts `"suspended"` and always transitions to `"running"` when it can, this reflects the reality of audio systems, where starting a stream takes some time, and this allows authors to know that this is the case. Authors are always sure that doing some setup in the first `"suspended"` to `"running"` transition will work. Even in Gecko where `AudioContext` are multiplexed on the same system level audio stream, and where a second `AudioContext` will start "immediately", it's useful to always have the initial transition.

**Comment by foolip** [comment]
To the extent that I was like a web developer when trying to make https://github.com/web-platform-tests/wpt/pull/24405 work, I have to agree that consistent behavior of always starting suspended and then transitioning to running would have led to less head-scratching on my part. Things that are sometimes synchronous and sometimes asynchronous can lead to said head-scratching.

That being said, obviously the impact of making the change in Chrome should be carefully considered.

**Comment by padenot** [comment]
For reference, because I wasn't sure if my memories were correct, this was always the normative behaviour, initially added to the spec in late 2014 by @cwilso: https://github.com/WebAudio/web-audio-api/pull/374/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR527

> The context state MUST begin in "suspended", and transitions to "running" when system resources are acquired and audio has begun processing.

This was later refactored to an algorithm to make it more explicit.

**Comment by hoch** [comment]
It is too late, but I am glad we have this discussion again. Thanks for clarification and I'll investigate the impact of this change in Chrome. (https://crbug.com/1106380)

@foolip Feel free to add me as a reviewer in https://github.com/web-platform-tests/wpt/pull/24611 since I already reviewed and agreed with the comments in this thread.

**Comment by guest271314** [comment]
Setting the relevant flags or preferences to enable or disable media playback also affect this.

**Comment by abent999** [comment]
Closed

**Comment by guest271314** [comment]
> Based on the current spec, I have to agree. But my question above still stands. What happens to the rest of Web Audio code after the immediate state reports "suspended"?

Nothing should happen. Similar to `exit()` in PHP with regard to not processing further code, while simultaneously similar to `await` in JavaScript unless and until `resume()` is called.

In the case of Chromium `"suspend"` event is dispatched twice when `resume()` is called.
