### ISSUE TITLE
Be explicit that initial transition to running needs to take [[suspended by user]] flag into account?

### ISSUE THREAD

**Issue by tidoust** [WebAudio/web-audio-api#2251]
I just [reported an issue against Webkit](https://bugs.webkit.org/show_bug.cgi?id=216972) which, unless I missed something, does not take the `[[suspended by user]]` flag into account when it runs the initial transition to `running` (delayed in Webkit). Other browser engines seem to be handling this case correctly, meaning that the following code will successfully end up in a `suspended` state across browsers (except Safari):

```js
button.addEventListener('click', async () => {
  const AudioContext = window.AudioContext || window.webkitAudioContext;
  const audioContext = new AudioContext();
  await audioContext.suspend();
  const node = audioContext.createOscillator();
  // State is `suspended`
});
```

That said, the spec does not explicitly state that the initial transition to `running` should take the `[[suspended by user]]` flag into account:
https://webaudio.github.io/web-audio-api/#allowed-to-start

If you all agree that's the right behavior, perhaps it should?

I note that the spec is neither fully clear about the fact that this "initial transition" will happen, nor is it about what that transition will do. For instance, the text could perhaps state that when the transition happens, and provided that the `[[suspended by user]]` flag is not set, the user agent must "send a control message to start processing".

**Comment by rtoy** [comment]
Today's teleconf:  Yes we should add a note to allowed-to-start that it needs to take into account [[suspended by user]].

**Comment by rtoy** [comment]
I see now that this is somewhat coupled with #2248 which describes how `start()` behaves with `[[suspended by user]]`.

But at least for the text for `allowed to start` could be adjusted to mention that the transition to running is also controlled by whether `[[suspended by user]]` is true or false.

**Comment by rtoy** [comment]
I think that in your example, the state could actually be "running" before you call `suspend` because a user-gesture caused the creation of the AudioContext.  Construction of the oscillator sould not start the context.

But, for eaxmple
```
const c = new window.AudioContext();

button.addEventListener('click', async () => {
  const node = new OscillatorNode(c);
  node.start();
});
```

the context should start suspended.  When the click occurs, starting the oscillator will start the context.  If you added `c.suspend()` after construction, then the click will not start the context.  This case is handled in the algorithm for [start](https://webaudio.github.io/web-audio-api/#dom-audioscheduledsourcenode-start).

So perhaps the only thing that's needed is to state that the transition to "running" (if allowed) follows the steps in [resuming an AudioContext](https://webaudio.github.io/web-audio-api/#context-resume).

**Comment by rtoy** [comment]
I think the latest version (8 March 2021) is ok as is.  There are four[ references to "allowed to start" and I think they explain the conditions where the context can start:

- [AudioContext constructor](https://webaudio.github.io/web-audio-api/#ref-for-allowed-to-start):  there's no need to talk about `[[suspended by user]]` in construction because it the context can't be suspended by the user at construction.
- [AudioContext.resume](https://webaudio.github.io/web-audio-api/#ref-for-allowed-to-start%E2%91%A0): the algorithm already handles the `[[suspended by user]]` flag appropriately.
- [AudioScheduledSourceNode.start](https://webaudio.github.io/web-audio-api/#ref-for-allowed-to-start%E2%91%A1):  the algorithm for starting explicitly checks for `[[suspended by user]]` before starting the context.
- [AudioBufferSourceNode.start](https://webaudio.github.io/web-audio-api/#ref-for-allowed-to-start%E2%91%A1): like for an `AudioScheduledSourceNode`, the algorithm explicitly checks `[[suspended by user]]` before starting the context.

We could update the description of `allowed to start` to mention `[[suspended by user]]`, but then the other places would need to be updated to remove the checks.  We could do this, but I think the current version is correctly specifing the behavior.  Have I missed something?

**Comment by tidoust** [comment]
> We could update the description of allowed to start to mention [[suspended by user]], but then the other places would need to be updated to remove the checks. We could do this, but I think the current version is correctly specifing the behavior. Have I missed something?

I may be misunderstanding what "delay the initial transition" means :)

What I do not see is the specification of what happens when a user agent that chose to delay the initial transition eventually decides to perform that transition on its own (without the user issuing a call to `resume()` or `start()`). That is what initially happened in Safari (bug has now been fixed) where the creation of an oscillator actually triggered the transition to `running`.

To clarify: If a user agent chooses _not to_ delay the initial transition, the [construction algorithm](https://webaudio.github.io/web-audio-api/#dom-audiocontext-audiocontext) says that a "control message to start processing" gets sent, which triggers the appropriate algorithm in the spec that, among other things, switches the context to a `running` state. That part is clear.

Now, if a user agent chooses to delay the initial transition, the [construction algorithm](https://webaudio.github.io/web-audio-api/#dom-audiocontext-audiocontext) leaves the context in a `suspended` state. That part is clear as well. Later on, when the user agent decides that it is now ok to run the initial transition, what should it do? The spec does not say anything about that. A naive approach would be to consider that it means sending a "control message to start processing". That algorithm works well at construction time, but not after a delay because it does not check the `[[suspended by user]]` flag which may have been set in the meantime.

**Comment by rtoy** [comment]
Yeah, this is complicated.  When the context is not allowed to start on construction, it's suspended as you say.  The only way to transition from this suspended state is to:

- Call `resume()` on the context from a user gesture
- Create some `AudioScheduledSourceNode` and `start()` it from a user gesture.

Both of these take the `[[suspended by user]]` flag in to account.


In all other cases, the context will not transition to running: `resume()` won't resume without a user gesture and `start()` won't either.

I think this is spelled out in the `resume` and `start` algorithms.

**Comment by tidoust** [comment]
Understood. Then my understanding was indeed incorrect and all the normative bits seem good!

It may be worthwhile to clarify that the transition cannot happen in a vacuum by replacing "A user agent may delay this initial transition" with "A user agent may initially disallow this transition". In particular, for me, "delay" suggests that something like "wait 2 seconds then do it" is legit, which is why I was wondering where the "do it" steps were defined. That is not the case in practice, there is nothing to be done after a delay, the transition will be triggered by other actions.

**Comment by rtoy** [comment]
Modifying the text as you suggest looks good.  Thanks for bringing this up!
