### ISSUE TITLE
outputLatency normative, non-optional

### ISSUE THREAD

**Issue by svgeesus** [WebAudio/web-audio-api#2330]
**Describe the issue**

outputLatency is a required part of the spec.

**Where Is It**

https://webaudio.github.io/web-audio-api/#dom-audiocontext-outputlatency

**Additional Information**

We don't have two implementations. The [Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=785409) indicates a lack of urgency to add this.

Given that, I was asked on today's transition call why is is not optional, or non-normative. Is it not implemented because of fingerprinting risk (even if quantized) or because of difficulty in estimating the latency?

**Comment by rtoy** [comment]
That's a good question.  Unless we can resolve that here in this issue, we might have to wait for the teleconf next week to decide on what to do.

But there is probably a fingerprinting risk. 

I also think estimating the latency is difficult and sometimes devices lie.  I defer to @padenot about that since Mozilla has implemented this.

**Comment by svgeesus** [comment]
To be clear, this one isn't a blocker on publishing a Proposed Rec; the [transition was approved today](https://github.com/w3c/transitions/issues/328#issuecomment-830187380).

The fingerprinting risk is already mentioned in the spec.

**Comment by rtoy** [comment]
Teleconf:  `outputLatency` is very important for synchronizing audio and video together.  `MediaElement` does this automatically, so the appropriate code is in each browser.

So, there's no change needed here.  This is required.
