### ISSUE TITLE
Links to GitHub references that could be W3C references (link stability)

### ISSUE THREAD

**Issue by svgeesus** [WebAudio/web-audio-api#2333]
**Describe the issue**

Several links point to drafts on GitHub when they could point to a stable W3C source instead. Some of those might automatically be fixed when the bikeshed **Prepare for TR: Yes** directive is used.

**Where Is It**

https://w3c.github.io/hr-time/ should link to https://www.w3.org/TR/hr-time-3/ which is a W3C Working Draft 24 March 2021

https://w3c.github.io/mediacapture-fromelement/ should link to https://www.w3.org/TR/mediacapture-fromelement/ which is a W3C Working Draft 19 January 2021

https://w3ctag.github.io/security-questionnaire/ should link to https://www.w3.org/TR/security-privacy-questionnaire/ which is a W3C Working Group Note, 23 March 2021

https://webaudio.github.io/Audio-EQ-Cookbook/audio-eq-cookbook.html should link to an archived copy on W3C site (regardless of whether we use the GitHub copy for maintenance). One possibility would be to issue it as a W3C Note. But we could also just put a copy somewhere in W3C space.

**Comment by rtoy** [comment]
Looks like all the links you mention are explicit `<a href>` links, so these will need to be updated.

For the cookbook, the current W3C archive version is incorrect or badly formatted in some places.  It would be great if we could update the current version.

But in the long term it might be better have that as a W3C Note so that it can be updated as needed.  (I don't foresee any real updates, thought.  I've gone over it with Robert Bristow-Johnson a while back, and I think everything is correct.  He did want to add some diagrams and such, but that's not really necessary.)

**Comment by svgeesus** [comment]
Do you recall where the W3C version is?

I agree that having a Note is a better place for this sort of thing.

**Comment by rtoy** [comment]
I think it was here:   https://www.w3.org/2011/audio/audio-eq-cookbook.html .  But looks like it immediately redirects to https://webaudio.github.io/Audio-EQ-Cookbook/audio-eq-cookbook.html now.

**Comment by rtoy** [comment]
Should references to `hr-time-2` be replaced by `hr-time-3`?

**Comment by svgeesus** [comment]
The table of contents for [hr-time-3](https://www.w3.org/TR/hr-time-3/) is identical to that of [hr-time-2](https://www.w3.org/TR/hr-time-2/) and there is no changes section. 

However [a diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Fhr-time-2%2F&doc2=https%3A%2F%2Fwww.w3.org%2FTR%2Fhr-time-3%2F) shows new features like `coarsen time` and ` relative high resolution time` so I guess it is more up to date. Do we use those new features?

**Comment by rtoy** [comment]
Grepping for hr-time-2 shows just two uses, and they both talk about `performance.now`.

What should I do with the audio cookbook link?  Change it to https://www.w3.org/2011/audio/audio-eq-cookbook.html even though it immediately redirects?  I vaguely remember we asked Doug or you(?) to do the redirect because the original version was a little buggy.

**Comment by rtoy** [comment]
F2F Meeting:  We'll make the cookbook a W3C Note so there's a stable W3C link to it.
