### ISSUE TITLE
WebIDL no longer defines "present"

### ISSUE THREAD

**Issue by svgeesus** [WebAudio/web-audio-api#2338]
**Describe the issue**

There are a bunch of links 

```html
<a href="https://heycam.github.io/webidl/#dfn-present">present</a>
```

but WebIDL no longer defines this so the link is broken. I traced it to [this issue](https://github.com/heycam/webidl/issues/381) where they defer to the infra definition `map-exists`. Although the [related pull request](https://github.com/heycam/webidl/pull/610/files) didn't seem to remove that term :(

So I believe this should be

```html
<a href="https://infra.spec.whatwg.org/#map-exists">present</a>
```

I have made this change in the Proposed Rec, as we are nt allowed to have broken links. If there is a better link, we have like 24 hours to update it.

**Comment by rtoy** [comment]
The first occurrence I looked at is [Step 2 of the `ConvolverNode` constructor](https://webaudio.github.io/web-audio-api/#ConvolverNode-constructors):

> If `buffer` is present, set the `buffer` attribute to its value.

Both `buffer` link to the `buffer` attribute.  Perhaps the first `buffer` is meant to be the `buffer` member of the `ConvolverOptions` dictionary?  Otherwise, I can't make sense of this sentence.

But I think the link to ` map-exists` is the right one for rest of the convolver constructor algorithm; they all talk about a dictionary member being "present" in the options dictionary.  So "map-exists" makes sense.

Since you already made the change for the PR, I'm not sure how to proceed here.

**Comment by padenot** [comment]
Probably back-port here, and we're good, no ?
