### ISSUE TITLE
registerProcessor outside of initial addModule evaluation not visible on the main thread

### ISSUE THREAD

**Issue by tklajnscek** [WebAudio/web-audio-api#2355]
I've just hit an issue where if I call `registerProcessor` from a function that doesn't execute during the initial evaluation that happens when `addModule` is called everything seems to succeed on the worklet side, but (at least in Chromium) the processor cannot be created from main thread, because the descriptor never syncs across and it the `AudioWorkletNode` constructor can't find it. 

Chromium apparently only syncs the processor list when the addModule initial evaluation completes (for each module). I figured this out by looking through the Chromium code (and that code pretty closely follows the standard). So I've read through the standard and I couldn't really find anything to imply that the sync might not happen. 

My actual use case is that I'm using this with Emscripten compiled code and that code is using MODULARIZE=1, which wraps all of the code in a closure so that it doesn't leak into the global scope. I'm sharing the same code as the main thread into the audio worklet thread (and other workers too) so what I did is I created a .js file with a dummy processor that I load along with my main js file (so 2x `addModule` calls on the `AudioContext`). I create the dummy processor on the main thread to establish a message channel with the worklet which then behaves much like a regular DedicatedWorker message channel would. This, with some minor fixes, makes it work with all the existing pthread code in Emscripten which lets you run pretty much any C++ compiled to WASM&JS in the worklets!

The dummy worker then receives a message to initialize and runs the module init function. That function calls `registerProcessor` to register it's processors and notifies the main thread that it's done (postMessage).

The main thread then tries to create one of those processors and it fails saying it's not registered.

I think there needs to be clear language in the standard on what is supposed to happen here.
Either it needs to be made clear that this should work and the browser vendors need to fix this.
Or it needs to be made an error in which case `registerProcessor` should throw an exception when called outside the initial eval instead of just swallowing the results.

To make matters worse, this starts working if you then register another module with addModule as that will do a sync which will also grab the missing processors and sync them.

I'm not entirely this is the right place to ask, so feel free to point me in the right direction, but it feels like this should be defined in the standard and this is not just a browser implementation issue.

**Comment by padenot** [comment]
It's already specified rather clearly I think: in the steps that describe `registerProcessor`,  the [step 8 and 9](https://webaudio.github.io/web-audio-api/#dom-audioworkletglobalscope-registerprocessor) clearly states that a task is sent back to control thread, for the `BaseAudioContext` to update the name -> process and name -> param maps. At no point anything is said about when this should be done or not done, so it should be done always.

In general, in standards, it is defined what should happen, not what should not happen, because specifying what should not happen doesn't have a limit.

This works well in Firefox and Safari. I'm sure the Chromium folks would appreciate an issue on their tracker: https://bugs.chromium.org/p/chromium/issues/entry. https://gist.github.com/padenot/2725e17aeee89c5718d6ba1484ea17c0 is the test case I used to verify this.

**Comment by hoch** [comment]
Yes, this seems like an oversight in the impl. Thanks for raising the issue @tklajnscek and creating a test case @padenot!

I filed an issue myself: https://crbug.com/1218892

**Comment by tklajnscek** [comment]
Great, thank you both for the lightning fast turn around and sorry for causing unnecessary here :)

**Comment by hoch** [comment]
FYI - it's fixed in Chrome Canary 93.0.4553.0.
