### ISSUE TITLE
Raw audio recording not supported

### ISSUE THREAD

**Issue by goldwaving** [WebAudio/web-audio-api#2391]
I am creating an audio editor app.  To allow editing of newly recorded audio, raw audio needs to be obtained.  Unless I am missing something, this basic functionality seems to be missing from the specification.  Here is what I have found so far:

1. ScriptProcessorNode is deprecated and should not be used.
2. MediaRecorder does not support raw audio.
3. AnalyserNode does not provide seamless sequential data (it has gaps or overlaps).
4. AudioWeblet is not supported on Safari and is needlessly complicated for such a simple task.

Is there another option I have not discovered yet?  If not, could an AudioPassThroughNode be considered.  It would have an ondata event that provides seamless, raw audio data passing through the node, perhaps with a starting time and an ending time and other details.  Alternatively **requiring** support for raw audio in MediaRecord would work.

**Comment by padenot** [comment]
This has been possible for years, many web apps are doing it. `AudioWorklet` is the solution to access audio sample data on the web. If you don't care about performances at all, you can simply `postMessage` the input chunks and call it a day, interleaving, converting to e.g. S16 samples, and slapping a RIFF header on it.

https://ringbuf-js.netlify.app/example/audioworklet-to-worker/ is a full example that is suited for high-performance workloads, heavily commented, and does Web Audio API -> WAV file. It does so without touching the main thread, so it is robust against load and real-time safe.

`ScriptProcessorNode` is **not** a valid solution because there is no resilience against any kind of load when using it. It's trivial to make a page that drops some audio.

[Web Codecs](https://w3c.github.io/webcodecs/) is also now available in Chromium and soon others, so sample-type conversion and encoding (to lossless and lossy audio formats) is supported. It's a few lines of code to (e.g.) get real-time microphone data, encode that in real-time to (e.g.) mp3 or aac or opus or flac and do something with it.

I'm closing this because the Web Audio API doesn't really deal with encoding: it's a processing API, and there are solutions already.

**Comment by emilfihlman** [comment]
Audioworklet is an abysmal "solution", and not simple at all.

I do not want any encoding, I want raw samples, and there is simply no reason why either mediarecorder can't be forced to add support for raw samples, or adding an analyser node to microphone input that gives out chunks on callback without dropping any of them.

The absurd thing is that sending raw samples has been made super easy with buffers, but getting raw samples is put behind absurd complexity.

**Comment by padenot** [comment]
It's so absurdly complex that an entire example to get raw samples is 25 lines of code, with about 50% of the lines being boilerplate.

```html
<script type="worklet">
  registerProcessor('test', class param extends AudioWorkletProcessor {
    constructor() { super(); }
    process(input, output, parameters) {
      this.port.postMessage(input[0]);
      return true;
    }
  });
</script>
<script type=module>
  var ac = new AudioContext;
  var worklet_src = document.querySelector("script[type=worklet]")
  const blob = new Blob([worklet_src.innerText],
                        {type: "application/javascript"});
  var url = URL.createObjectURL(blob);
  await ac.audioWorklet.addModule(url);
  var worklet = new AudioWorkletNode(ac, 'test', {});
  var osc = new OscillatorNode(ac);
  osc.start();
  osc.connect(worklet)
  worklet.connect(ac.destination);
  worklet.port.onmessage = (e) => {
    console.log(e.data[0]);
  }
</script>
```

**Comment by emilfihlman** [comment]
And the reason it couldn't be one line
analyser.addEventListener("dataavailable", callback)
is?

**Comment by nickjillings** [comment]
Callbacks on the main thread is a terrible idea for performance and you'll just lock up your app. You'll be getting more callbacks than you need, whilst the audio worklet provides you a thread just to process the audio information that you can process and then send back the information you are processing.

**Comment by emilfihlman** [comment]
That's based literally on nothing. At 48kS/s and 1024 samples per callback that's literally only 47 calls per second, much less than typical requestAnimationFrame, which runs at 60 fps usually, or even 120/144fps on modern phones, and usually does a lot more work than what analysing audio requires.

Patronizing or spreading fud is not ok.

**Comment by padenot** [comment]
> And the reason it couldn't be one line
> analyser.addEventListener("dataavailable", callback)
> is?

Yes, unconditionally firing an event in an isosynchronous fashion to the main thread from a real-time audio thread with an expectation of real-time guarantees and no drops of audio buffers, with fixed buffering and without a way to handle main thread overload or any other form of control is simply bad design and doesn't work, in the same way that `ScriptProcessorNode` doesn't work: under ideal and controlled condition it's fine, but in the real world it isn't: main thread load (in our case, the characteristics that is important is its responsiveness) isn't something that can be controlled by the website developer in practice.

If the main thread isn't responsive for some time, you suddenly have a large number of events queued to its event loop. When it's processing events again, it now has to process all those events, loading the main thread again, delaying more events to be delivered, etc.

This is the same reason why `requestAnimationFrame(...)` isn't an event: avoiding problems piling up under load without a way to handle back-pressure.

In the case of the Web Audio API, developers can instead devise their own mechanism that suit their use-case better, using the lower-level primitive that is the `AudioWorklet`, or the higher level primitive that is the `AnalyzerNode`.

If it's for recording and not dropping buffers is important, use a worker and add a buffer there. If it's for visualization, maybe compute the values needed on the real-time audio thread and send the desired characteristics to the main thread, etc.

For that, it's possible to use message passing (`postMessage(...)`) that is easy to use but less efficient (because it can cause garbage collection and allocations), it's also possible to use [real-time safe wait-free ring buffers based on atomics](https://ringbuf-js.netlify.app/) if the needs of the application is higher and its resilience is important.

Finally, `AnalyzerNode` suits the common case of needed some form of data for analysis, with some windowing but with the explicit non-guarantees about being able to get the entirety of the time-domain data without discontinuities or overlaps.

**Comment by goldwaving** [comment]
To follow up to my previous post and give some real world feedback...

Safari finally supports AudioWorklets, so I redesigned playback and recording in my app to use them.  Unfortunately Safari had a major [bug](https://bugs.webkit.org/show_bug.cgi?id=251091) that caused distortion, but that has since been fixed.  However audio playback on Safari is still very poor with frequent crackling and glitches when simply tapping the screen, even in the most basic app.

Using AudioWorklets requires more coding and has a steeper learning curve than should be required for such a simple task.  It is really just a work-around to overcome the real problem.

The biggest design flaw is that `AudioContext` is tied to the main thread (which may explain Safari's poor quality).  You have to create an `AudioContext` on the main thread.  Playback has to be started, stopped, and managed on the main thread.  `AudioContext` is tangled up in so many other things that prevent it from being available in Workers.  If `AudioContexts` could be created in Workers, it would make this whole argument about `ScriptProcessorNode` and AudioWorklets irrelevant.  There would be zero burden on the main thread.

One a separate note, 'decodeAudioData' does not belong in 'AudioContext' at all.  Moving that functionality to the WebCodec API to actually handle containers would make far more sense.  Web browser already have all that code to handle many different file types, but it is mostly wasted in the very limited 'decodeAudioData' function.

**Comment by goldwaving** [comment]
> Those are simply Safari bugs

Agreed, but the difficulty Apple is having with playing defect free audio might suggest that WebAudio is more complicated than it should be.

> Since it's not possible to create a Web Worker that has a real-time priority, being able to instantiate an `AudioContext` on a worker wouldn't change anything to the fact that `ScriptProcessorNode` isn't adequate

In real world apps AudioWorklets have to interact with Workers or the main thread where real-time priority is not available.  Without careful implementation, you end up with the same problems as `ScriptProcessorNode`, but with even more overhead (as in your example above).  AudioWorklets may be great for the small percentage of high end developers that need super low latency, real-time audio for a very specific use, but what about everyone else that just wants a simple way to get the audio data?  `ScriptProcessorNode` with a larger buffer size was very adequate.

> `decodeAudioData` was shipped on the Web for too long before the cross-browser-vendor standardization effort started, and it's impossible to remove it

Of course, but the lack of a better API after all of this time is disappointing and if `ScriptProcessorNode` can be deprecated, so can `decodeAudioData` (eventually).  There is a lot of code locked behind that one function that could be the foundation for an container handling API that WebCodec lacks.  However that probably should be discussed in a different topic.

**Comment by SevenSystems** [comment]
> padenot

Thanks so much for posting this code. It's funny I just spent 1 hour googling how to accomplish THE most basic, fundamental task of an audio recording API -- RECORD RAW AUDIO 😂
