### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by wytrych** [WebAudio/web-audio-api#2409]
**Describe the feature**
Support multithreading to be able to better utilise CPU in complex Web Audio apps, like DAWs.
 
**Is there a prototype?**
The very basic implementation is in Chrome already, where each AudioContext is run on a new thread. It could be enough to sanction this behaviour in a spec.

**Describe the feature in more detail**
The minimal way for it to work is as already described in Chrome. Each `new AudioContext()` is run on a separate thread. When running multiple contexts in parallel we of course run into problems like unsynced clocks and the lack of a single sink so it's impossible to have one master gain for example. These could be overcome by including also algorithms that would utilise multiple cpus behind the scenes. That would be easier to use, but also a lot of work and maybe not necessary to unlock the potential of more CPU power available to developers.

**Comment by hoch** [comment]
2023 TPAC Audio WG Discussion:

The WG believes that supporting multi-threaded rendering for the non-AudioWorklet case would make the project almost infeasible due to the significant complexity of the implementation.

Also similarly to https://github.com/WebAudio/web-audio-api/issues/2500#issuecomment-1719728519, using the [Web Worker with configurable QoS](https://github.com/riju/web-worker-quality-of-service/blob/main/explainer.md) would be more general and scalable solution for the worklet-powered use case. The WG will not be pursuing this capability as an active project.

**Comment by JohnWeisz** [comment]
> When running multiple contexts in parallel we of course run into problems like unsynced clocks and the lack of a single sink so it's impossible to have one master gain for example.

Given this is coming up a lot in search about AudioContext and multithreading, I'd like to add that it's already possible to have "sub"-AudioContext instances that then feed into a "main" AudioContext using SharedArrayBuffer and AudioWorklet, because this actually enables a way to stream audio between different AudioContext instances:

```
... -> [ctx1Gain] -> [ctx1WorkletProcessor] --- SharedArrayBuffer --- [ctx2WorkletProcessor] -> [ctx2Gain] -> ...
```

Of course, you'll need to implement a ring buffer of some sort and there _will_ be latency, but if you can compensate for that latency in your app (which is typically what multi-threaded DAWs do, including Logic), then this might prove feasible.
