### ISSUE TITLE
Proper FFT / IFFT missing

### ISSUE THREAD

**Issue by kickermeister** [WebAudio/web-audio-api#248]
I wonder why you didn't implemented a proper FFT and IFFT node for the Web Audio API. This would be definitively a great benefit for advanced audio processing within web browsers.. 
As far as I've understand the code, you are nearly there with the AnalyserNode which obviously conducts a FFT. But this node doesn't provide complex numbers as one would need for audio processing in frequency domain. Eventually, the possibility to transform the processed buffer back to the time domain with a proper IFFT would be also extremely helpful!

Any chance to implement this feature(s) in a future version?

**Comment by joeberkovitz** [comment]
WG feels that #468 is doing a better job of carrying the use cases expressed here forward. Closing.

**Comment by linolinco** [comment]
> On Mon, Oct 14, 2013 at 8:48 PM, Jean-Marc Valin
> [notifications@github.comwrote](mailto:notifications@github.comwrote):
> 
> The ConvolverNode can do convolution and cross-correlation for you.
> 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/[/issues/248](https://github.com/WebAudio/web-audio-api/issues/248)#issuecomment-26307484
> > .

(7 years late to the party, but I just have to throw in my 2c here)

This is backwards. You have at least 3 places already in WebAudio where an FFT/IFFT is used internally:
1. AnalyserNode performs an FFT (but exposes only the real coefficients, for no reason that I can see),
2. createPeriodicWave performs an IFFT (but perhaps not well optimised / on the audio render thread?),
3. ConvolverNode (if implemented properly) performs 2 FFTs, a multiplication, and an IFFT (but is monolithic).

That's 3 use cases already within your own API, but somehow FFT/IFFT is not an important fundamental audio operation?  Any decent WebAudio implementation will need an FFT/IFFT with windowing & overlap to implement ConvolverNode well - so why not expose it in the API so we can all use it?

Yes of course I can throw in my own userland FFT on top of the 1-3 already existing implementations. However, one key motivation for writing a Web App is platform independent code, and a platform-independent generic FFT will always be very suboptimal. Have a look at the fftw project to see how much optimisation potential there is; the FFT should be part of WebAudio so that this potential can be unlocked.

Had to get this off my chest. Was planning to port my professional audio application to WebAudio, but after discovering that as of late 2020 it still doesn't expose a proper FFT I'm rather put off. I don't think I've ever before seen an audio API without FFT in my life, have to say that the lack of it here makes me doubt the expertise of those in charge.

**Comment by padenot** [comment]
The current model doesn't lend itself well to having frequency-domain data between `AudioNode`s: everything is time domain.

There's been a request for a performance comparison between WASM+SIMD and optimized native code, to understand if it would be worth it to expose an FFT API that would be implemented in the browser, but nobody answered. In any case, having FFT code backed by native code would be an API on its own, and, while useful for audio, should be developed outside the audio working group, so that it's useful for other domains.

Nobody has ever opposed this, lots of people have requested it, but lots of people request lots of things, and it's just a few people working on this, choices need to be made. In light of the fact that performance numbers looked adequate (not amazing, adequate) for what people wanted to do, other things were worked on.

> Had to get this off my chest. Was planning to port my professional audio application to WebAudio, but after discovering that as of late 2020 it still doesn't expose a proper FFT I'm rather put off. I don't think I've ever before seen an audio API without FFT in my life, have to say that the lack of it here makes me doubt the expertise of those in charge.

"Those in charge" have expertise, but lack time and have inherited a spec that was shipped in Chrome without proper review, and have strived to improve it without breaking existing apps and backwards compatibility, with the available resources. Insulting them in a public bug tracker is not exactly the best way to request a feature, which would be to start a discussion in an issue in https://github.com/WebAudio/web-audio-api-v2/issues.

**Comment by linolinco** [comment]
Look, the key frustration here is that we all know that the complex-valued FFT result is already being computed in (among others) AnalyserNode. Regardless of its shortcomings, just adding a getComplexFrequencyData() accessor to AnalyserNode would be trivial, 100% backwards & forwards compatible, and already useful. Keep it simple: treat this as a bug report about a missing accessor. It surely cannot be reasonable for fundamentalist discussions about the API’s overall design and purpose, and the role for frequency-domain data in it (or not), to hold up such a simple fix for 7 years?

Yes, the next thing one would then like to see in AnalyserNode is windowing, and overlap-add, and finally re-synthesis - but these are discussions for another day. One step at a time.

**Comment by rtoy** [comment]
Adding `getComplexFrequencyData()` is acceptable to me.  

Can you open a [new issue (on v2)](https://github.com/WebAudio/web-audio-api-v2/issues/new/choose) for your thoughts on this? We are not really accepting anything new in v1.  v2 will have all the new things and any updates we want or need to make for v1.

**Comment by linolinco** [comment]
Okay, will do. Thanks!
