### ISSUE TITLE
Sometimes often no sound/audio but not always

### ISSUE THREAD

**Issue by melbaxa** [WebAudio/web-audio-api#2595]
Teracube 2e
iodé OS Android 11
Firefox 128.0.1 (fenix-128.0.1.multi.android-arm64-v8a.apk)
iodé Browser 127.0-iode.95 [Firefox]

I have coded a own webpage with a fingerboard for playing sound and a automatic playing the fingerboard. This works on my desktop device every time. But on my mobile device only sometimes. After many reloads of the webpage it works fine. But maybe after the next reload not.

- no sound / audio
- grafic osscilator flat (middle, 50% height).

So, i had installed on my mobile device Firefox 128.0.1 and in this the extension "Mobile DevTools". The console is always empty. No hint, no warning, no error.

I have no idea. Because sometimes it works fine. I am a little bit frustrated, because no hint, no warning, no error and sometimes it works. It is a bad situation, because I don't know if it works by all visitors or not.

Here a copy of the webpage (online to 20240728): https://www.zwixl.de/rsound/

... EDIT: maybe i have found the problem:
- Load/reload the webpage
- First: fingertouch in a empty area
- Next: fingertouch on the fingerboard.

So, it is a OS or browser problem? How solved it?

**Comment by mjwilson-google** [comment]
Hello, thanks for reaching out.  This repository is only for working on the Web Audio specification, and I don't think what you described is something that can be fixed by modifying the specification.

For support with the Firefox implementation please ask on https://bugzilla.mozilla.org/, StackOverflow, or the WebAudio Slack Channel as appropriate.
