### ISSUE TITLE
Add `MessageChannel` to AudioWorkletGlobalScope

### ISSUE THREAD

**Issue by FabianHummel** [WebAudio/web-audio-api#2607]
**Describe the feature**
I need to send a message from the audio processor to the main thread and also **receive the response**. Why is this not implemented, or is it planned to be implemented soon? Same thing with TextEncoder/Decoder, but there are workarounds using polyfills available.

**Describe the feature in more detail**
On the main thread we can already create MessageChannels to pass one port of the channel to the worker thread and listen for messages on the other port, to receive responses from the audio processor. However, the opposite situation is not possible, because the MessageChannel constructor does not exist.

### working example: (main -> worker -> main)
```js
// main.js
const channel = new MessageChannel();
channel.port1.onmessage = console.log; // we can receive the response here
worker.port.postMessage("request", [channel.port2]); // pass the ack-port

// worker.js
this.port.onmessage = event => {
    // do some logic
    event.ports[0].postMessage("response"); // send the response here.
}
```

### faulty example: (worker -> main -> worker)
```js
// main.js
worker.port.onmessage = event => {
    // do some logic on the main thread
    event.ports[0].postMessage("response"); // send the response here.
}

// worker.js
const channel = new MessageChannel(); // ERROR: MessageChannel is not defined.
channel.port1.onmessage = console.log; // we "could" receive the response here...
this.port.postMessage("request", [channel.port2]); // pass the ack-port
```

**Comment by padenot** [comment]
It is implemented. Each `AudioWorkletProcessor` have a `port` attribute that is the real-time thread side of the `AudioWorkletNode`'s `port` attribute, allowing bidirectional communication:

https://webaudio.github.io/web-audio-api/#dom-audioworkletprocessor-port
https://webaudio.github.io/web-audio-api/#dom-audioworkletnode-port

It is possible to use those ports to send more ports if needed, e.g. for direct `AudioWorkletGloabalScope` <=> `DedicatedWorkerGlobalScope` communication. Keep in mind that using `port` isn't real-time safe, and while it can work under some circumstances, it will eventually cause allocation and garbage collection, those aren't real-time safe. https://blog.paul.cx/post/a-wait-free-spsc-ringbuffer-for-the-web/ is a discussion on the topic and provides various solutions.

Also keep in mind, a Worklet has **nothing** to do with a Worker.

`TextEncoder`/`TextDecoder` aren't available in `AudioWorkletGlobalScope` because they aren't to be used in a real-time thread. There are no use-cases that require encoding and decoding character set in a real-time audio callback.

**Comment by FabianHummel** [comment]
Yes, i am aware of the `port` property of the `AudioWorkletProcessor`. However, as stated in my question, i am required to use the `MessageChannel` class to get a **response** from a request that is sent **from** the `AudioWorkletProcessor` to the main thread.

**Comment by padenot** [comment]
Nothing here requires the creation of a `MessageChannel`, arbitrary bidirectional communication has been achieved as long as `AudioWorkletProcessor` has existed, just use the existing ports appropriately, or get your message channel outside the `AudioWorkletGlobalScope`.

This is the issue tracker for the Web Audio API specification, and issues are to be related to the specification. Questions on how to do something with the Web Audio API are in general better suited to either [Stack Overflow](https://stackoverflow.com/questions/tagged/web-audio) or the [Web Audio API slack](https://web-audio-slackin.herokuapp.com/),

**Comment by FabianHummel** [comment]
Yes, `MessageChannel` is required to send the response back to the requestee. I have found a workaround, but its very cumbersome to implement and not the best solution. Why are the `MessagePort` and `MessageEvent` classes implemented in the `AudioWorkletGlobalScope`, but not `MessageChannel`?
