### ISSUE TITLE
AudioBufferSourceNode.buffer should only be set once

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#288]
The spec doesn't say, but the buffer attribute of an AudioBufferSourceNode should probably be only settable once. If you've started the source node and change the buffer while the previous buffer is playing, you have no control over when the new source starts.

**Comment by rtoy** [comment]
There hasn't been any opposition to the proposal, so can we consider this accepted?  I guess we also need to say that if you do set the buffer again, you get a NotSupportedError (or InvalidStateError?)

**Comment by padenot** [comment]
`InvalidStateError`, I'd say.

**Comment by joeberkovitz** [comment]
+1 on this point - NotSupportedError makes it sound as though the operation itself is unsupported, while InvalidStateError conveys that the problem is with the timing of the operation.

On Jan 15, 2015, at 5:59 AM, Paul ADENOT <notifications@github.com> wrote:

> 
> `InvalidStateError`, I'd say.
> —
> Reply to this email directly or view it on GitHub.
> 

.            .       .    .  . ...Joe

Joe Berkovitz
President

Noteflight LLC
Boston, Mass.
phone: +1 978 314 6271
www.noteflight.com
"Your music, everywhere"

**Comment by joeberkovitz** [comment]
Seems to be ready for editing

**Comment by padenot** [comment]
Yep, taking and changing the flags accordingly.
