### ISSUE TITLE
Conformance section: need to note use of MUST that is "RFC-legal" as opposed to common English usage

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#31]
> Originally reported on W3C Bugzilla [ISSUE-21515](https://www.w3.org/Bugs/Public/show_bug.cgi?id=21515) Tue, 02 Apr 2013 12:30:25 GMT
> Reported by Olivier Thereaux
> Assigned to 

Per discussion at Audio WG f2f 2013-03-26

The conformance section should note that the use of keywords MUST, MAY, SHOULD are used per RFC-2119 and constitute normative statements.

The group did not express a strong preference for either of the following two options. The choice will be left to the discretion of the editor:
1. make sure all normative statements use upper-case MUST, MAY, etc

or
1. state in conformance statement that all usage of words must, may, should are per RFC2119 and remove/paraphrase all other uses of the keywords, so that only conformance assertions use them.

**Comment by billhofmann** [comment]
Probably should be a "do this last" task, eh?

**Comment by rtoy** [comment]
Hmm. I actually prefer option 1 (MUST) because the writer needs to make a conscious decision to uppercase (unless you're shouting all the time).  "must", "may", "should" are such common words that it's easy to say them by accident.

I think it should also be reviewed on a more on-going process instead of at the end.  This is a living document right now and implementations are already implementing (or not) MUST items.  If this is incorrect now, implementations will end up breaking something somewhere down the line.  Thus, do a pass now, and then editors and reviewers need to take care that all future uses of these terms are correct.

**Comment by svgeesus** [comment]
Currently the spec is a mix of
a)  RFC 2119-style MUST, marked and styled as such
b) RFC 2119-style MUST, not marked up and and unstyled (should be converted to case a)
c) occasional colloquial uses of must, not marked up and indistinguishable from case b). Should be rewritten.

As an example  
"The value of its kind attribute must be equal to "audio", or an InvalidStateError exception MUST be thrown."

This could easily be rewritten to get rid of one of the must (there is only one testable assertion here) for example

"An InvalidStateError exception MUST be thrown if the value of its kind attribute is not equal to "audio""

**Comment by svgeesus** [comment]
Tried a PR but had unexplained conflicts
https://github.com/WebAudio/web-audio-api/pull/1276
The diff on the PR does not show conflicts.

**Comment by padenot** [comment]
I just merged this, closing this issue now.
