### ISSUE TITLE
Map AudioContext times to DOM timestamps

### ISSUE THREAD

**Issue by joeberkovitz** [WebAudio/web-audio-api#340]
At the moment the API cannot deliver a reliable mapping between AudioContext.currentTime  and DOM-related time bases such as Event.timeStamp or Performance.now(). This makes it difficult to either 1) schedule non-audio actions in the browser in relation to the audio signal, or 2) determine the relationship of non-audio events in relation to the audio signal.

Separately, Issue #12 documents the related problem of determining when a user will actually hear the audio signal scheduled to occur at a given AudioContext time.

**Comment by jipodine** [comment]
Does this mean that eventually all these clocks (AudioContext.currentTime, performance.now(), document.timeline.currentTime, requestAnimationFrame callback time) would be unified? This would be great, because today it is a real pain to synchronise the processes, even more across devices. (This is what I am trying to do now.)

This would also solve the granularity issue of AudioContext.currentTime, and the relative drifts of the clocks, which create interrelated issues (as trying to estimate the drift with a large tick)...

**Comment by cwilso** [comment]
No, that's not possible.  The AudioContext.currentTime proceeds non-linearly (it's the current "next block processing start time", and it is driven by the audio hardware's clock - and different audio context instances (presume here we've already exposed non-default audio devices, which we haven't but plan to) may have literally different clock crystals (and therefore run in different time).

performance.now, document.timeline and rAF callback time are locked together - they're all based on the system clock.

**Comment by cwilso** [comment]
No, that's not possible.  The AudioContext.currentTime proceeds non-monotonically (it's the current "next block processing start time", which jumps by at least a block at a time (you can't wait 0.001 second and expect that it's advanced by 0.001 second) and it is driven by the audio hardware's clock - and different audio context instances (presume here we've already exposed non-default audio devices, which we haven't but plan to) may have literally different clock crystals (and therefore run in different time).

performance.now, document.timeline and rAF callback time are locked together - they're all based on the system clock.

**Comment by jipodine** [comment]
So it will still be up to the user to synchronise the clocks. I am wondering if it is ever possible to accurately estimate the drift using the AudioContext.currentTime, because of the buffer size, that can be long, and that is unknown by the user. One other issue is to precisely insert an audio event in future without knowing the exact current time: at the moment, there is a jitter as big as the audio buffer size, which sounds bad, of course.

But I think it is possible, to at least provide a strictly monotonic audio clock, as there is already an example of this. Paul will correct me if I am wrong, but it seems that in Firefox *when you did not check the AudioContext.currentTime for a while (sic)*, the time inside the block is available:
See http://jipodine.github.io/web-audio-clock/ 
or simply type in a console here
`app.audio.context.currentTime * app.audio.context.sampleRate`
and you will notice that it is not an integer. Unfortunately it is not true any more on repeated calls.

Even if the complement inside an audio block is not drift-compensated, that would be a great improvement, yet.

And ultimately, I think that having only one unified time should be a goal for an environment. As an example, when using several audio devices with OSX Core Audio, one device is used as the time reference.

**Comment by cwilso** [comment]
Yes, it's possibly to accurately estimate the drift over time.  What isn't possible today is to accurately estimate what audio time is currently is - i.e. what bit is currently being played from the audio output right now.  

AudioContext.currentTime does not reporesent this precise current time - it represents the start of the next block to be processed (i.e. the time at which any changes scheduled now will take place). 

I disagree that having one unified time should be a goal for Web Audio.  That can certainly be mapped on top of what we have (once we've solved the mapping represented by this issue), and then the developer is in charge of which is the "master clock".

**Comment by karlt** [comment]
Jean-Philippe Lambert writes:

> But I think it is possible, to at least provide a strictly monotonic audio
> clock, as there is already an example of this.

It is monotonically non-decreasing, but not strictly increasing.

> Paul will correct me if I am
> wrong, but it seems that in Firefox *when you did not check the
> AudioContext.currentTime for a while (sic)*, the time inside the block is
> available:
> See http://jipodine.github.io/web-audio-clock/ 
> or simply type in a console here
> `app.audio.context.currentTime * app.audio.context.sampleRate`
> and you will notice that it is not an integer. Unfortunately it is not true
> any more on repeated calls.

That's an implementation bug.

https://bugzilla.mozilla.org/show_bug.cgi?id=1053011

**Comment by jipodine** [comment]
Yes, the Firefox example is an implementation bug, but it is still a very simple API example of how to address the audio time inside a block. The other possibility would be to provide a reference time corresponding to the current audio time.

We all agree that the main problem is the low precision of the current audio time. And even to evaluate the drift of the audio clock (versus the performance clock). Because, for now, to accurately measure the relative time differences, one needs a long duration in order to compensate for the uncertainty of reading the audio clock. 

While it depends on the audio host, getting the performance.now time while increasing the AudioContext.currentTime (on the audio driver's periodic callback), seems the only moment where the different clocks are comparable. By storing these two times, we could achieve some good precision.
 
Then, we would also need to know the supplemental delay introduced by the browser, and the operating system, in order to accurately schedule an event in future.

From this point, everything would be there to convert to an from the audio time. About the API, I personally think that having a unified (an compensated) time is easier for keeping the processes in sync, but any helper function or yet an other time would be good.

**Comment by joeberkovitz** [comment]
We believe this issue to be resolved by the latest change to #12 which effectively allows the user to convert between time coordinates, modulo doing the appropriate math.
