### ISSUE TITLE
start(), stop() and AudioParam methods should throw for NaN and Infinity

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#354]
What should happen if the user passes Infinity or NaN to the timeline functions such as setValueAtTime, linearRampToValueAtTime, exponentialRampToValueAtTime and setTargetAtTime?

The spec doesn't say what should happen if setTargetAtTime is given a timeConstant <= 0. I think timeConstant should be constrained to be > 0. An error should probably be thrown for non-positive values.

Similarly, setValueCurveAtTime should probably constrain the duration to be > 0. An error should probably be thrown for non-positive values.

**Comment by bjornm** [comment]
Please allow negative time values for the automation methods again. This is not different from allowing values lower than AudioContext.currentTime, which is really useful. Example:

  1. Imagine a GainNode with a fade in automation curve of 10s in a DAW. 
  2. Right when the context is initiated, the user fast-forwards to 5s and presses play.
  3. Playback from the middle of the automation curve requires setting events in the past (relative to AudioContext.currentTime). Since the context is newly created, the time will be negative.

**Comment by rtoy** [comment]
I don't quite understand your example.  Can you be a bit more explicit?

**Comment by cwilso** [comment]
I believe his point is he wants to jump in to the middle of a ramp with a
start point set in the past.  This can work normally, but if the
AudioContext has just started (i.e. it's time is close to zero), the start
point might be in negative time.

**Comment by bjornm** [comment]
Right. I've attached a screenshot. I'm playing back an AudioBufferSourceNode. It's connected to a GainNode which has a fade in going from 0s to 10s (track time). I want to jump into the middle of it (at 5s). Normally this would be ok since I can use times in the past: 

gainNode.setValueAtTime(0, audioContext.currentTime - 5)
gainNode.linearRampToValueAtTime(1, audioContext.currentTime - 5 + 10)

However, if the AudioContext has just started, the time argument might become negative. This throws an exception.

![ramp](https://cloud.githubusercontent.com/assets/570429/6147046/9556e6ba-b1f3-11e4-9e6e-a4893e704043.png)

**Comment by cwilso** [comment]
We should explicitly allow negative numbers.

**Comment by rtoy** [comment]
Do we need to discuss this more or are we going to allow negative times for automations?

**Comment by rtoy** [comment]
This is now inconsistent with #713 which was resolved by #849.

Now what?

**Comment by padenot** [comment]
This should not be allowed, it complicates the model.

The design of the Web Audio API makes you write your own timeline anyways, the timeline cannot be rewound, everything goes forward all the time.

**Comment by bjornm** [comment]
Please see my comment from Feb 2015. 

We have a need to be able to express AudioParam curves which start in the past. For instance, a slow fade in, which is started somewhere in the middle because you skipped forward right after the audio context was started.

I like to compare Web Audio to WebGL. In this case, cropping - stuff still can exist outside the screen even though you cannot see it. It creates a simpler api than if you had to check for cropping and change your graphics rendering accordingly, for instance, drawing half a circle instead of a complete one. I'm not saying this needs to happen for everything in web audio, but for AudioParam curves it definitely adds value for us.

**Comment by padenot** [comment]
This is different, in the sense that if we allow negative time, we need to always keep the list of all events that ever existed, and this has non-trivial performance implications. It's more like, keep all texture all the time in a WebGL context because you might want to be able to read back from a previous frame buffer.

The Web Audio API is an API for rendering audio in the near future. The raison d'être of `AudioParam` is because the audio rendering is controlled from the main thread, but actually rendered on another thread, a bit like CSS animation (that are scheduled on the main thread, but often rendered in the compositor thread or process), not to create a complete parameter automation track for the rendering of channel in a DAW.

**Comment by rtoy** [comment]
While I understand the desire to be able to have negative time, it seems to me that you are in control and can detect that negative time will be used and adjust `setValueAtTime()` and `linearRampToValueAtTime()` to produce the right curve.  Yes, it's more work on your part.

As for Paul's comment about keeping all past events, I don't think that's true. I think you only need to keep the current and previous event.  Any event inserted before the previous event can't have any effect because the previous event is still there.  Any future events will either start from the previous event or from the current event.

And Chrome just recently landed one last optimization for timelines where if the last event has ended, we can remove all the events and revert back to the faster non-automation code path.

**Comment by bjornm** [comment]
We already do recalculations of slope values at certain points, so we can certainly do this for negative time values as well.

However, allowing negative time seems to me like a special case of the more general one: allowing time values in the past. Consider this pretty common case regarding just-in-time scheduling of future audio to be played, for instance a synthesizer played live:

1. User touches screen / presses midi key
2. Program adds an oscillator node and schedules it to play at t.
3. Program adds a gain node and schedules an ADSR envelope starting at t.

The question is, how do you choose t for low latency and robust playback? If you choose the current time, you might miss occasionally because the render quantum was underway, so t will actually be in the past when the nodes are processed. OscillatorNode deals with this quite gracefully (starting asap), does AudioParam too? If yes, then I propose allowing negative time values in addition to past time values. The spec says the time value should be clamped to currentTime, but such a solution will distort most curves.

On the other hand, if you choose t to be the next safe render quantum, it might need to be 120ms later. Most Android devices batch a large number of render quanta in a single OS callback so for Android Samsung Galaxy Tab S2 it is 120ms (the largest value we tested). This causes a very high added latency for the uncommon, but more robust situation. 

As a compromise and workaround, we can chose t = currentTime and add redundant events for the AudioParam curve every 5 ms from t to t+120 (24 events), since we do not quite know at what context time the process will take place, but this is awkward. 

Regarding performance, rtoys suggestion struck me as well and just keeping the previous event sounds manageable to me. Supporting live synthesizer playback seems like a core use case for the web audio api and also in a developer friendly way, since most developers might not be too familiar with timing problems between javascript and c++ threads on different platforms. And low latency is always important.

I hope I'm explaining this clearly. Maybe there is something I'm missing? What are your thoughts?

...also, thanks a lot for landing the Chrome optimization, it sounds like a great improvement!

**Comment by joeberkovitz** [comment]
Resolved: we are still going to clamp automation time values to `currentTime`. This requires additional developer effort but avoids a host of new questions about automation events in the past interacting with times in the past.
