### ISSUE TITLE
Architectural layering: output stream access?

### ISSUE THREAD

**Issue by cwilso** [WebAudio/web-audio-api#359]
Need to think through how we are exposing the output stream to the system, to close the loop on how one recreates Web Audio in JS.  Yes, ROC, this is "shouldn't we have a Stream API here?"  :)

**Comment by cwilso** [comment]
I'm still concerned about the layering issues implicit in not resolving this prior to v1.

**Comment by joeberkovitz** [comment]
I'm also concerned about the implications. However, I think there needs to be a clear argument that deferring a full-blown abstraction of output streams will hurt the specification more than further delays in progressing it towards Recommendation, especially since WebRTC is itself in some flux.

We already have an open issue #445 relating to selection specific output devices that is being addressed by WebRTC. That *is* part of V1, and should result in WebAudio including some type of device selection mechanism for the destination of the context (which may sit on top of MediaStreamAudioDestinationNodes wrapped around devices obtained via getUserMedia(), which would seem to be one potential solution to the layering problem).

Also the proposed revisions to getUserMedia() can supply a MediaTrackConstraints object that can ask for particular sample rate ranges etc -- see http://w3c.github.io/mediacapture-main/getusermedia.html#dictionary-mediatrackconstraints-members

So I'd like to know what "showstopper" issues you feel remain given the above points. I'm not saying there aren't any -- just that I would like to surface them before having the group discuss this issue for V1.

**Comment by mdjp** [comment]
Note for review, based on TPAC 2017 conversation. Output stream access could be achived in a seperate spec maintained by the WG.

**Comment by mdjp** [comment]
See Audio Device Client explainer
https://github.com/WebAudio/web-audio-cg/blob/master/audio-device-client/explainer.md
