### ISSUE TITLE
More clarifications for BiquadFilterNode needed.

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#419]
The spec lists nominal values for the frequency, Q, and gain parameters of a biquad.  Are these intended to be informational or requirements?

For all filters, I think the frequency should satisfy 0 < frequency < sampleRate/2.  Q should satisfy Q > 0. gain can be any real value.

It's not specified what detune does or what the units are but I think it's pretty obvious from how detune is used in other places.  But what should happen if frequency + detune results in a value outside of range of (0, sampleRate/2)?  Clipped to 0 or sampleRate/2?

**Comment by Nantonos** [comment]
So this amounts to a proposal to 
a) remove Q from lowshelf and highshelf, 
b) change the other filters to use Q explicitly
c) do something different for lowpass and highpass (but exactly what is not specified)

I'm aware of resonant shelf filters in hardware, so a) is a restriction of functionality. Is that because the functionality is seen as not needed, or rarely used, or implemented better elsewhere?

For b) is the more complex term doing something more musically useful for Q? (such as compensating for bass drop in a highly resonant LPF?)

Its hard to evaluate c) since there is no motivation presented for the change.

**Comment by rtoy** [comment]
The actual motivation is to codify what Chrome, Firefox, and Safari actually do today in the implementation of the biquad filters.

**Comment by Nantonos** [comment]
Hello rtoy,

Thursday, January 8, 2015, 5:30:45 PM, you wrote:

> The actual motivation is to codify what Chrome, Firefox, and Safari
> actually do today in the implementation of the biquad filters.

Right, and I am asking what the impact of that change would be and
whether that impact is good or not.

I'm also asking why it is different; is it different-and-better?
Different-but-limited? Different because it was copy pasted from
somewhere without paying attention?

In other words, a "why" would be useful.


-- 
Best regards,
 Nantonos                            mailto:nantonos@epona.net

**Comment by rtoy** [comment]
On Thu, Jan 8, 2015 at 8:41 AM, Nantonos <notifications@github.com> wrote:

> Hello rtoy,
>
> Thursday, January 8, 2015, 5:30:45 PM, you wrote:
>
> > The actual motivation is to codify what Chrome, Firefox, and Safari
> > actually do today in the implementation of the biquad filters.
>
> Right, and I am asking what the impact of that change would be and
> whether that impact is good or not.
>

​The impact is the spec actually says what the implementations are doing
today.  ​

​Not churning the implementations are a good thing. I have not heard of any
complaints that the current filters and parameters don't do what people
expect.  (Perhaps because the spec never really said until Paul put in the
formulas?)​

>
> I'm also asking why it is different; is it different-and-better?
> Different-but-limited? Different because it was copy pasted from
> somewhere without paying attention?
>

​I'm confused on what "it" is here. Does "it" refer to what implementations
do today? ​

​Or does "it" refer to what the spec currently says?​

>
> In other words, a "why" would be useful.
>
>
​Knowing what "it" refers to would help me to answer the "why".  Maybe.​


>
> --
> Best regards,
> Nantonos mailto:nantonos@epona.net
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/419#issuecomment-69207175>
> .
>



-- 
Ray

**Comment by jipodine** [comment]
From an audio user point of view, I think it is easier to provide a unified API for all of the biquad filter types (directly derived from the cookbook by Robert Bristow-Johnson, of course):
 - gain everywhere, in dB (by simply multiplying the internal b coefficients by the linear gain, when not used in the formula)
 - quality everywhere: strictly monotonic when 0 < Q ≤ 1, resonant when Q > 1
Why? First, because this is very common; and nothing breaks when changing the filter type; and the gain is often used to compensate the quality.

**Comment by rtoy** [comment]
On Tue, Apr 21, 2015 at 4:28 AM, Jean-Philippe Lambert <
notifications@github.com> wrote:

> From an audio user point of view, I think it is easier to provide a
> unified API for all of the biquad filter types (directly derived from the
> cookbook by Robert Bristow-Johnson, of course):
>
>    - gain everywhere, in dB (by simply multiplying the internal b
>    coefficients by the linear gain, when not used in the formula)
>    - quality everywhere: strictly monotonic when 0 < Q ≤ 1, resonant when
>    Q > 1 Why? First, because this is very common; and nothing breaks when
>    changing the filter type; and the gain is often used to compensate the
>    quality.
>
>
​I understand your concerns and desire for a unified API.

However, biquads have been this way for years now without complaint, and
I'm rather reluctant to change things at this point.​ This also has the
potential of changing the behavior of existing apps (because no browser
implements the cookbook formulas).

>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/419#issuecomment-94753845>
> .
>



-- 
Ray
