### ISSUE TITLE
Define built-in oscillator output more carefully

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#447]
This might be an issue for implementors, but I think it is worth to raise the flag to hear WG's opinion.

I was fiddling with a JS test platform for Web Audio API and found that the sound produced by oscillator nodes between browser actually has difference in loudness (RMS level) - and in some cases it is more than audible.

I understand we cannot have sample-accurate consistency across the browsers, but I think we need some guideline for loudness level and have to build a common test platform around it. (which we already discussed)

~~~js
var mod = context.createOscillator();
var idx = context.createGain();
var car = context.createOscillator();

mod.connect(idx);
idx.connect(car.frequency);
car.connect(context.destination);

mod.frequency.value = 1000;
idx.gain.value = 220;
car.type = 'sawtooth';
car.frequency.value = 440;

mod.start(0.0);
car.start(0.0);
~~~

The code above produces (RMS to dBFS):
Chrome/Safari: -2.14dB
FireFox: -1.84dB

Although it is just 0.3dB difference, but if you change frequency, modulation index or waveform type, the difference varies. I think we don't want to see this type of variety across the browser.

**Comment by mdjp** [comment]
Would be exposed by proposed independent test suite as proposed by the WG

**Comment by joeberkovitz** [comment]
Resolution: The output of a built-in oscillator must be equivalent to the output of a PeriodicWave whose Fourier coefficients yield the built-in wave type, with normalization as per the resolution of #91.

**Comment by karlt** [comment]
On Mon, 01 Jun 2015 07:48:00 -0700, Joe Berkovitz wrote:

> Resolution: The output of a built-in oscillator must be equivalent to the
> output of a PeriodicWave whose Fourier coefficients yield the built-in wave
> type, with normalization as per the resolution of #91.

I'm not clear exactly what that means.

A PeriodicWave with an infinite number of coefficients would be
required to generate the basic waveform.  Is that what is meant
here?

Normalization would have no effect.  Band-limiting would be
applied to the specified infinite-resolution waveform which
already has range ±1, and so the discrete waveform would have a
slightly different range, as expected.  That all makes sense to
me.

It wouldn't make sense to normalize based on an inverse FFT of a
Fourier series truncated to the maximum size of arrays supported
by PeriodicWave.  That would mean a change the magnitude if the
maximum size of arrays is changed, in
https://github.com/WebAudio/web-audio-api/issues/386 for example.

**Comment by rtoy** [comment]
The intent is that the output of an oscillator for one of the builtin types is the same as if you created a custom oscillator using setPeriodicWave with a PeriodicWave created using the appropriate Fourier coefficients. Normalization is included.

**Comment by karlt** [comment]
The most precise and clear way to specify the magnitude, would be
to specify the coefficients in the Fourier series as indicated in
https://github.com/WebAudio/web-audio-api/issues/569#issue-97995530
Thank you for doing that.

If the text "This is useful if a builtin type is desired but without the
default normalization" can be removed from
https://github.com/rtoy/web-audio-api/commit/138649f42b993d0457d65a431f8e75a8743c342d,
then that clearly defines the built-in waveforms with their magnitude.

The talk about normalization here is unclear because some expect
normalization of unit-magnitude waveforms to have no effect, but
others are expecting an effect.

Personally, I think it would be best to keep the magnitude as
already specified in
http://webaudio.github.io/web-audio-api/#basic-waveform-phase
and I assume the coefficients in
138649f42b993d0457d65a431f8e75a8743c342d are consistent with that.

This would provide a square wave matching the one at
http://mathworld.wolfram.com/FourierSeriesSquareWave.html 
which is what I think most people would expect.
e.g. https://github.com/WebAudio/web-audio-api/issues/614

If there is good reason to change the specified magnitude to
something less than what is currently specified, then it is best
to alter the coefficients in
138649f42b993d0457d65a431f8e75a8743c342d
to clearly indicate the chosen magnitude, and
http://webaudio.github.io/web-audio-api/#basic-waveform-phase
should be adjusted appropriately.

Changing the magnitude by merely specifying that normalization is
applied as with PeriodicWave normalization is unclear because the
basic waveforms derive from an infinite series, but the
PeriodicWave normalization is usually applied to a finite series,
and so would depend on how the infinite series is truncated.

**Comment by rtoy** [comment]
You are basically asking to remove normalization.  The fact that PeriodicWave recently added a denormalization option basically means normalization is a done deal to me.

Chrome has had normalization since the very beginning and I think Firefox also normalizes.This is a breaking change and will very likely break everyone's use of oscillators.

Of course this can be changed, but I am opposed to this change in behaviour.  Normalization is well-defined now except for the number of terms used.  Any reasonable implementation will use at least 2048 coefficients (for sample rates of 44.1kHz or more).  Using more coefficients is unlikely to change the normalization appreciably.

If you want this change, I suggest filing a new issue to remove normalization so we can discuss in one issue instead of having spread out over two separate issues.
