### ISSUE TITLE
Audio Worker "bypass" Attribute

### ISSUE THREAD

**Issue by ghost** [WebAudio/web-audio-api#456]
Would it be possible to add a `bypass` attribute to the Audio Worker interface?

The purpose of this would be to allow audio workers to be effectively switched on and off without having to continually pull them from (and push them into) a node chain while maintaining references to their previous input/output connections.

```
interface AudioWorkerNode : AudioNode {
    attribute boolean bypass;
    ...
}
```

Simply put, while `bypass` is true the audio worker's `onaudioprocess` event handler will not be called.

---

As an afterthought, this attribute might be handy to have available on all audio nodes.

**Comment by Nantonos** [comment]
I agree with cwilso that bypass of an in-use node is a non-trivial undertaking. Partial blocks already mentioned; any processing which uses delays/previous samples could straddle blocks as well. Nodes need to be ramped down before being bypassed, to avoid clicks (and similarly ramped up on unbypass). Bypass poorly defined for n-in m-out nodes.

It is also a poor workaround which is better addressed by a repatching facility.

Suggest closing this issue without change.

**Comment by cwilso** [comment]
WG resolution on 1/8/2015 call: no bypass in v1.

**Comment by jsantell** [comment]
This is now in tools in Firefox 38 for testing out the Gecko implementation. Clicking the [power] button in the inspector with a node selected will bypass the processing/source. Implemented via `passThrough` attribute on AudioNodes, only exposed to chrome priviledged code, setting this to `true` enables the "bypass".

[patch bypassing source nodes](https://hg.mozilla.org/mozilla-central/rev/eb7712477525)
[patch bypassing processing of audio nodes](https://hg.mozilla.org/mozilla-central/rev/2ad221f9aca9)

**Comment by jsantell** [comment]
To follow up on a question regarding bypassing ChannelMerger and ChannelSplitter nodes from the WAC, in the Gecko implementation, we have all nodes bypassable (source nodes emit nothing, all other nodes copy the input buffer to output buffer), except ChannelMerger, ChannelSplitter and AudioDestination nodes are unaffected by setting the `passThrough` attribute.

**Comment by cwilso** [comment]
1) I think you're advocating for a generic passThrough on AudioNode, yes?
That would just not do anything on ChannelMerger/Splitter?  (It's kind of
irrelevant on AudioDestination, too, yes.)

2) Hmm.  Perhaps this should really be a 3-state switch - normal,
passThrough, or silent?

**Comment by jsantell** [comment]
I'm more saying it is possible to try a proof of concept to see if it is useful for others to advocate, than myself advocating for it -- a downside of this in content privilege code would be, someone mentioned, a shortcut for gates, which could cause issues mentioned earlier in this thread (and not sure if Gecko implementation addresses delivering partial blocks, tail-time processing, etc., as this is mainly for debugging uses, not accuracy), so that is a concern.

Regarding a 'silent' state, would that just cause an AudioNode to output silence, like a temporary `.disconnect()`? Would that make sense to also be an attribute of `bypass`, or a different attribute?

**Comment by rtoy** [comment]
I still fail to see the use cases where this can't be solved by sticking a
gain node on the input and/or output of the node you want to bypass.  This
is well-understood and well-specified today. And implementations today can
do something smart if a node knows that all inputs are silent, including
gain nodes with a gain value of 0.

On Wed, Jan 28, 2015 at 7:50 AM, Jordan Santell <notifications@github.com>
wrote:

> I'm more saying it is possible to try a proof of concept to see if it is
> useful for others to advocate, than myself advocating for it -- a downside
> of this in content privilege code would be, someone mentioned, a shortcut
> for gates, which could cause issues mentioned earlier in this thread (and
> not sure if Gecko implementation addresses delivering partial blocks,
> tail-time processing, etc., as this is mainly for debugging uses, not
> accuracy), so that is a concern.
>
> Regarding a 'silent' state, would that just cause an AudioNode to output
> silence, like a temporary .disconnect()? Would that make sense to also be
> an attribute of bypass, or a different attribute?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/456#issuecomment-71857476>
> .
>



-- 
Ray

**Comment by hoch** [comment]
> " a shortcut for gates"

This already explains why we shouldn't be doing this - once it is unleashed out there we can't prevent people from doing that. (Just imagine that doing it with setTimeout...) Also it doesn't make any sense to make this attribute as AudioParam so we can schedule it. (Some DAWs have the automatable bypass feature, but it can easily be done with a gain node and an extra path.)

I switched my opinion (which was in favor of bypass) when I realized that it is fairly unclear about how to handle the time progression or internal state in bypassed nodes.

**Comment by si-robertson** [comment]
Time progression wouldn't be affected by the bypass switch/flag. All a bypass does is send the signal directly from the input channel(s) to the output channel(s), it's a very common feature of hardware and software audio devices, e.g. rack mounted hardware in a music studio. There wouldn't be any point allowing the bypass flag to be scheduled either, it's simply a switch.

**Comment by hoch** [comment]
@si-robertson Please have a look below:

~~~js
var source = context.createBufferSource();
source.buffer = myBuffer; // let's say this is 5 seconds long.
source.start();
setTimeout(function () {
  source.bypass = true;
}, 2500);
setTimeout(function () {
  source.bypass = false;
}, 6000);
~~~

I really can't tell what should happen. Same thing can happen to Delay, Convolver or any node keeps internal state or buffer inside. Surely we can decide how we handle these cases, but it won't satisfy everyone.

I can completely understand the 'music studio' analogy, but also want to point out that we are talking about a 'node', not the whole plug-in or a hardware rack unit. I believe bypassing should be a feature of bigger unit, not a node.

Additionally, if we have to bring the bypass feature into the spec I prefer to have it as a AudioParam because many DAWs have been offering it as a sample-accurate automatable parameter.

**Comment by si-robertson** [comment]
@hoch I can see the issue there, the bypass state would make no difference to the audible sound because the node isn't modifying the samples in any way. That actually appears to be an issue with the specification, there's no way to distinguish processing nodes (dynamics, filters, etc) from everything else (if we could tell the difference, e.g. with a ProcessorNode interface or something, then it would make this feature request more viable).

**Comment by mdjp** [comment]
Bypass can be implemented by developers for the audio worklet.
