### ISSUE TITLE
Clarify constraint for positive value for exponentialRampToValue

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#486]
http://webaudio.github.io/web-audio-api/#widl-AudioParam-exponentialRampToValueAtTime-void-float-value-double-endTime says the value parameter must be strictly positive.

However, note that the IDL says the value is a float, but Javascript works with doubles.  Thus, the user can specify a value of, say, 1e-100, which is clearly positive.  However, the conversion of that to a float underflows to zero, so the user will get an error thrown that the value is not positive.

The text should probably include some (non-normative) information about this.

**Comment by karlt** [comment]
Could the API be changed to permit value = 0?

**Comment by rtoy** [comment]
I guess you could, but I think that would mean the value is actually 0 from t0 to t1 and independent of v0, according to the formula for the exponential ramp.  That's probably not what people would want.

**Comment by karlt** [comment]
rtoy writes:

> I guess you could, but I think that would mean the value is actually 0 from t0
> to t1 and independent of v0, according to the formula for the exponential
> ramp.

Yes, that would be my expectation.

> That's probably not what people would want.

I'm guessing that people would want 1e-100 to behave very
similarly to 1e-30, and similar behavior for zero.  Such behavior
for zero would provide this.

Throwing an exception would be a very different behavior, for a
relatively small change in the value.

**Comment by rtoy** [comment]
On Thu, Feb 19, 2015 at 5:02 PM, Karl Tomlinson <notifications@github.com>
wrote:

> rtoy writes:
>
> > I guess you could, but I think that would mean the value is actually 0
> from t0
> > to t1 and independent of v0, according to the formula for the exponential
> > ramp.
>
> Yes, that would be my expectation.
>
> > That's probably not what people would want.
>
> I'm guessing that people would want 1e-100 to behave very
> similarly to 1e-30, and similar behavior for zero. Such behavior
> for zero would provide this.
>

​Actually, no.  1e-100 would be very different from 1e-30 because 1e-100
would underflow to 0 but 1e-30 would not.  Anything under about 1e-45 would
underflow to 0.  Thus, you would have this nice smooth behavior down to
1e-45 and then suddenly smaller values produce 0 for the ramp.​


>
> Throwing an exception would be a very different behavior, for a
> relatively small change in the value.



​The spec already says we throw an exception if the value is not strictly
positive.


​


>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/486#issuecomment-75171998>
> .
>



-- 
Ray

**Comment by karlt** [comment]
rtoy writes:

> ​Actually, no.  1e-100 would be very different from 1e-30 because 1e-100
> would underflow to 0 but 1e-30 would not.  Anything under about 1e-45 would
> underflow to 0.  Thus, you would have this nice smooth behavior down to
> 1e-45 and then suddenly smaller values produce 0 for the ramp.​

The issue of underflow is a good reason why it would be helpful if
the behavior for value = 0 should match the limit of the
rounding-error-free curve as value approaches 0 from above.

When |value| is very small, the values on the curve will be very
small (except very close to T0).  When |value| is 0, the spec
could be changed so that the values on the curve are 0
(transitioning at T0).

**Comment by karlt** [comment]
A related issue is to specify the behavior when V0 is negative.

**Comment by rtoy** [comment]
On Thu, Feb 19, 2015 at 10:32 PM, Karl Tomlinson <notifications@github.com>
wrote:

> rtoy writes:
>
> > ​Actually, no. 1e-100 would be very different from 1e-30 because 1e-100
> > would underflow to 0 but 1e-30 would not. Anything under about 1e-45
> would
> > underflow to 0. Thus, you would have this nice smooth behavior down to
> > 1e-45 and then suddenly smaller values produce 0 for the ramp.​
>
> The issue of underflow is a good reason why it would be helpful if
> the behavior for value = 0 should match the limit of the
> rounding-error-free curve as value approaches 0 from above.
>
> When |value| is very small, the values on the curve will be very
> small (except very close to T0). When |value| is 0, the spec
> could be changed so that the values on the curve are 0
> (transitioning at T0).


​For simplicity, I did a few plot with V0=1, T0=0, T1=1 so the formula is

v(t)=V1^t

​
​The curves are visually quite different between V1=1e-100 and V1=1e-30.
Of course, in the actual implementation, 1e-100 will underflow to 0 so the
curve is v(t) = 1 for t = 0, and 0 for t > 0.
​
If we want to allow V1 =0, I won't oppose it, but want to note there is a
decidedly large difference in curves between V1=0 and V1=1e-30.  For
example v(0.03) is about 0.1 when V1=1e-30.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/486#issuecomment-75195903>
> .
>



-- 
Ray

**Comment by joeberkovitz** [comment]
Resolution: Add clarifying language to spec pointing devs to `setTargetAtTime()` if they would like to specify a zero target.

**Comment by rtoy** [comment]
Looking over this again, is this really what we want to say?  An exponentialRampToValueAtTime isn't really the same as setTargetAtTime.  For one, the exponential will reach the value; setTargetAtTime will never reach it.

**Comment by rtoy** [comment]
Oh, and for the record, here is a plot of expoentialRampToValue going from 1 to a small value from time 0 to time 1.  The plot includes graphs for values of 1e-30, 1e-50, and 1e-100.  Note that all of these values would underflow to 0 except for 1e-30.  The plot shows that they are quite different. Don't know if they would be audibly different.

![image](https://cloud.githubusercontent.com/assets/663356/8069224/c0ccaf7a-0ead-11e5-8632-f7e3bf3f6c1d.png)

**Comment by joeberkovitz** [comment]
I think the resolution is still valid.  Ignoring possible underflow for a moment, the behavior of `setTargetAtTime()` has the exact same variability that you illustrated in your graph, except that the results are governed by the value of the `timeConstant` parameter rather than the end value that one is ramping to exponentially with `exponentialRampToValue()`.  We could be looking at the behavior of either function in your graph, for the given time range. (And yes, all of the above curves would be audibly different, because of the start of the ramps rather than their tails.)

Back to underflow, though. Varying a time constant is a much more reliable way for developers to make the choices in your graph, because they don't have to specify behavior via a tiny end-value for an exp ramp that might underflow. This is why I think it makes sense to point them at `setTargetAtTime()` for near-zero final values of an exponential ramp, as per the recorded resolution. The sense of the group was that trying to "improve" the interpretation of tiny end values for `exponentialRampToValue()` would be tricky and unreliable. It would lead to developers getting one of the curves in your graph, but probably not the one they intended.

In my opinion it would almost be better for devs to get a zero ramp than something that sounded approximately right, but wasn't.

**Comment by rtoy** [comment]
For the particular case of an exponential ramp to very small positive values, it turns out that setTargetAtTime() with an appropriate time constant is a very close approximation to the ramp. 

Thus, this is the best way to achieve the ramp to 0, if things are done correctly.

**Comment by mdjp** [comment]
To be discussed further at TPAC.

**Comment by joeberkovitz** [comment]
Actually I thought @rtoy was agreeing with my approach which would make this ready for editing without further discussion -- but maybe there's some controversy that I'm not aware of?

**Comment by rtoy** [comment]
Yes, I think suggesting setTargetAtTime to get an exponential "ramp" to zero is a good solution.
