### ISSUE TITLE
MediaElementSourceNode should have start/stop methods ala AudioBufferSourceNode

### ISSUE THREAD

**Issue by luser** [WebAudio/web-audio-api#512]
The spec says that AudioBufferSourceNode "is useful for playing short audio assets which require a high degree of scheduling flexibility". For longer assets it seems to encourage using MediaElementSourceNode. However, you then lose the ability to precisely schedule playback, which seems unfortunate. I started looking into writing a multitrack recorder using the Web Audio API, but this seems like a bit of a showstopper since it doesn't seem possible to precisely schedule the playing of longer samples.

**Comment by notthetup** [comment]
I have used AudioBufferSourceNode for > 10min long assets and it works totally fine. You're only restricted by the size of memory your browser can allocation.

**Comment by luser** [comment]
Be that as it may, it seems silly to restrict precise scheduling to assets that fit in memory. Having poked at Gecko's media internals in the past I suspect this would not be a hard thing to support.

**Comment by padenot** [comment]
It's straightforward to precisely schedule an assert in the future, as you mention.

AudioBufferSourceNode's goal it to be able to start playing a buffer as fast as possible in the future, (say, possibly in reaction to user interaction). Any kind of network or disk IO is prohibited, in this context.

**Comment by joeberkovitz** [comment]
Resolution: Clarify spec, ABSN is useful for more than short assets. If sample accurate scheduled streaming required, currently should roll your own with AudioWorker.

**Comment by billhofmann** [comment]
So, language seems like it should note that, rather than "short assets", it's memory only assets, and assets that require network or disk I/O should be scheduled using AudioWorker.

**Comment by billhofmann** [comment]
Clarify use of AudioBufferSourceNode and provide recommendation for non-memory backed assets

**Comment by dorontal** [comment]
I cannot see how AudioWorker (I assume you mean an Audio Worklet Node) could help the start playback precise scheduling issue. By the time an audio worklet node gets its audio, that audio has already been scheduled - it has already started playing. But we need to control the timing of precisely when the playback starts. How is an Audio Worker going to help?

**Comment by hoch** [comment]
MESN and other Media-related AudioNodes are backed by non-memory assets. Thus scheduling them like AudioBufferSourceNode would be difficult. For that, we need a new scheduling model for real-time streaming backend and that is outside of V1 work.

This might be something in the area of [V2 decoding/encoding work](https://github.com/WebAudio/web-audio-api/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22Theme+-+Encoding%2FDecoding%22+). FWIW, we triaged it as "High Priority V2" issue.

**Comment by dorontal** [comment]
Thank you for your response. I do hope that the Web Audio folks realize how important this issue is. Currently there is no way to know exactly when a stream will start playing (when the stream cannot entirely fit in memory and AudioBufferSourceNode is not usable). This means that precise full-duplex recording with large streams is impossible. It is not possible to synchronize the start time of a large incoming stream with the microphone stream, for example.  Imagine how much more useful the Web Audio API would be if we solve this issue.

The issue seems SIMPLE TO FIX (please correct me if I'm wrong): here is one idea as to how to start "solving" this, without having looked into the code at all (I'd be happy to help on fixing this one):

If Media Element Source Node (MESN) could mark the playback start time in some variable, problem is solved. MESN "knows" when playback begins, because internally its code is the one that begins the playback after a bit of buffering. If it could mark, precisely at playback start time, the audio context's time at that point - this solves the problem. Now we'd know when playback had began. All the rest can be handled by the programmer outside the Web Audio API if only that number is communicated to the programmer - synchronization can occur then.

**Comment by hoch** [comment]
The workaround you mentioned can be better with AudioWorkletNode. Consider the following:

- Main thread (request) -> Worker (fetch, decode in chunk) -> SharedArrayBuffer (PCM data) -> AudioWorkletGlobalScope
- Main thread : AudioWorkletNode (schedule) -> AudioWorkletProcessor (sample playback)

The diagram is crude, but you get the idea. All the heavy-lifting happens in non-main threads, so the stability can be greatly improved.
