### ISSUE TITLE
Clarify computedPlaybackRate with other attributes

### ISSUE THREAD

**Issue by iccir** [WebAudio/web-audio-api#560]
I always have to resort to trial and error to remember how `computedPlaybackRate` interacts with the following:

1) The `loopStart` and `loopEnd` attributes of `AudioBufferSourceNode`
2) The `when`, `offset`, and `duration` parameters of `AudioBufferSourceNode#start`
3) The `when` parameter of `AudioBufferSourceNode#stop`

Assume that I'm using a `playbackRate` of `10.0` on a buffer containing a 100Hz sine wave.

From my testing, I need to multiply `duration` by `playbackRate` in order to have the audio sample last for the specified amount of time (and not end prematurely).  Whereas `when` is always specified relative to the time of the AudioContext.  `loopStart` and `loopEnd` are relative to the buffer, before playbackRate.

It would be nice to clarify all of these in the spec.

**Comment by joeberkovitz** [comment]
@iccir I just want to make sure we're understanding the issues here.  Here are the problems I see:

1. It's the case that `loopStart` and `loopEnd` are in seconds, but are converted to positions in the buffer without reference to any computedPlaybackRate (otherwise the loop points would not be stable across changes in playback rate, which would be useless). The spec is not very clear on this point; it says: "Please note that as a low-level implementation detail, the AudioBuffer is at a specific sample-rate (usually the same as the AudioContext sample-rate), and that the loop times (in seconds) must be converted to the appropriate sample-frame positions in the buffer according to this sample-rate." That is really more than a note: it needs to be spelled out in more detail, and the independence from computedPlaybackRate needs to be called out.

2. The `offset` parameter is unclear as to whether it accounts for playbackRate or not. I believe it doesn't consider computed playback rate, for the same reason as the loop points, but the group needs to discuss this.

NB: The `when` and `duration` parameters are definitely in terms of AudioContext time and thus take computedPlaybackRate into account. That should be clarified.

**Comment by iccir** [comment]
Sorry, just realized that I never replied to this.

1. I understand that `loopStart` and `loopEnd` are in seconds and internally converted to positions.  It would help if the example code given in 2.9.3 showed this conversion.  It would also help if the spec clarified whether or not the `actualLoopEnd` sample is played before looping to `actualLoopStart` (and what does that even mean?  Does the `actualLoopStart` sample get played too?).  I've had a lot of issues playing seamless loops across all browsers and hardware sampling rate.

2. I believe you are correct.  I don't appear to be multiplying the offset by playback rate, and everything is working across all browsers (I haven't tested Edge yet, however).

**Comment by joeberkovitz** [comment]
@iccir We'll clarify the spec. FWIW the `actualLoopEnd` sample is not played. This index is the index of the first sample after the loop.  The `actualLoopStart` sample does get played.

I've not seen problems with seamless loops at different rates etc. but if you do, please report those problems on public-audio-dev@w3.org so browser vendors can know about them.
