### ISSUE TITLE
Expose under-runs in audio context

### ISSUE THREAD

**Issue by mdjp** [WebAudio/web-audio-api#577]
Could under-runs be exposed as a read only value on an audio context. It would be a useful both in order to correctly report problems to the user, or possibly to allow automatic fall-back to less intensive processing.

**Comment by padenot** [comment]
When, at some point, we'll have a thing that represents the audio output stream, I'd say it would make more sense to put this there.

**Comment by mdjp** [comment]
makes sense to me, moving this to v.next so it doesn't disappear.

**Comment by bjornm** [comment]
It would be really useful if you could expose thread utilisation, e.g. cpu%, so that an app can take action before underruns actually occur.

**Comment by rtoy** [comment]
In a very early version of the spec, every node had a cpu (and priority) attribute.  There was no description of what these meant and no browser actually implemented it.  These were eventually removed.

Chrome has considered at least adding some kind of cpu attribute internally for our own internal use.  So far, all we done is think about it.

**Comment by padenot** [comment]
> Chrome has considered at least adding some kind of cpu attribute internally for our own internal use. So far, all we done is think about it.

Same for gecko. We have some stuff for memory usage, but not CPU.

**Comment by andrewmacp** [comment]
The ability to see under-runs on the AudioContext could be really useful together with the latencyHint to allow developers to probe for acceptable buffer sizes, assuming latencyHint implementations may allow requesting values below the current 'interactive' default.

**Comment by padenot** [comment]
Yeah I think pretty much everybody agrees this is needed.

However, we're fixing more pressing things, like worklets, constructors, speccing the compressor, multichannel.

**Comment by joeberkovitz** [comment]
This is dealt with in the video realm by https://wicg.github.io/media-playback-quality/

Would we want to use that approach as a template? It counts both dropped frames and total frames, which gives some useful information.

**Comment by joeberkovitz** [comment]
The CPU part seems too floppy and also more dangerous security-wise.

**Comment by bjornm** [comment]
Great, the media-playback-quality seems like a good solution for exposing underruns. 

Additionally, I think there's value in also exposing the "usage level", even without having any underruns. Let me explain further.

I'm comparing this to staying under 16ms in your javascript code to reach 60FPS and avoid jank in the user interface. In order to really achieve it, you need access to the actual time, not just after-the-fact information that you didn't keep your time budget. For some background on frame rate performance, see: https://developers.google.com/web/fundamentals/performance/rendering/

Exposing the "usage level" will allow the developer to be proactive and decide ahead of time to e.g. utilise voice dropping for synths or reduce the algorithmic complexity in AudioWorklets. As an alternative to exposing CPU information, here's a simple alternative. **Time utilisation**:

(most recent render quantum duration) / (render quantum interval)

If the render quantum interval is 6ms and the most recent render quantum duration took 4.5ms, that would yield a time utilisation of 0.75.

Regarding security, I'm assuming you're referring to browser fingerprinting. Some thoughts:
1. I don't see any added security concerns compared to just exposing underruns (as a fingerprinting mechanism, you could measure how many oscillators you can use before gettting an underrun). 
2. You can detect underruns already today with the use of ScriptProcessorNodes or AudioWorklets (detect lost callbacks by comparing AudioContext.currentTime to wall time, new Date().getTime()). 
3. It's already quite possible today to fingerprint cpu characteristics using javascript benchmarks (google "javascript cpu speed fingerprinting"). Maybe the only way to prevent this is to cap all javascript engines, which will obviously not be great for the web platform.

Hope this all makes sense :) Thanks.

**Comment by joeberkovitz** [comment]
Agreed, detecting underruns is fine. We're more concerned about exposing CPU usage percentages as was suggested above.

**Comment by bjornm** [comment]
Could you please elaborate a bit, given my thoughts above?

**Comment by rtoy** [comment]
Probably doable.  But note that we just went over the outstanding issues to prioritize them for further review.  We tried not to spend too much time solving the issue.  Since this is marked as High Priority V2, we'll take a closer look soon and figure out what to do and how to expose these items if possible.

**Comment by bjornm** [comment]
Sounds good! Let me know if I can be of any help.

**Comment by mdjp** [comment]
Closing as duplicate of #1595
