### ISSUE TITLE
Distance models: maxDistance vs refDistance

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#611]
What should happen if someone sets maxDistance < refDistance?

What should happen if someone sets refDistance = 0?  

Since these are all distances, presumably, we should throw an InvalidStateError if they are set to negative values.

**Comment by karlt** [comment]
rtoy writes:

> What should happen if someone sets maxDistance < refDistance?

With the linear model, I guess the expected value for distanceGain
would be unit when d <= maxDistance and max(0, 1 - f) when d >=
refDistance.

The tricky part is maxDistance < d < refDistance.

Trying to detect problems when the values are set is not an
appealling option because that would require the values to be set
in a particular order.

> What should happen if someone sets refDistance = 0?  

For linear, there is no problem.

For inverse and exponential, distanceGain can be zero when d > 0.

d = 0 is tricky.  Perhaps there is a case for unit gain, but
perhaps it is least surprising if distanceGain is still zero.

> Since these are all distances, presumably, we should throw an
> InvalidStateError if they are set to negative values.

Throwing an exception sounds reasonable.  

https://github.com/WebAudio/web-audio-api/issues/385 suggests TypeError.

**Comment by rtoy** [comment]
On Thu, Oct 8, 2015 at 5:42 PM, Karl Tomlinson <notifications@github.com>
wrote:

> rtoy writes:
>
> > What should happen if someone sets maxDistance < refDistance?
>
> With the linear model, I guess the expected value for distanceGain
> would be unit when d <= maxDistance and max(0, 1 - f) when d >=
> refDistance.
>
> The tricky part is maxDistance < d < refDistance.
>

​I find trying to make sense of the equation for these values is
difficult.  It seems pretty clear that the intention (and expectation?) is
that maxDistance >= refDistance.
​


>
> Trying to detect problems when the values are set is not an
> appealling option because that would require the values to be set
> in a particular order.
>

​What else can you do?  We could just say it's undefined behavior, but
that's also unappealing to me.
​


>
> > What should happen if someone sets refDistance = 0?
>
> For linear, there is no problem.
>
> For inverse and exponential, distanceGain can be zero when d > 0.
>

​I don't see a use case for a refDistance of 0 and would prefer to disallow
it.  If you want something small set it to 1 nm or something.
​


>
> d = 0 is tricky. Perhaps there is a case for unit gain, but
> perhaps it is least surprising if distanceGain is still zero.
>
> > Since these are all distances, presumably, we should throw an
> > InvalidStateError if they are set to negative values.
>
> Throwing an exception sounds reasonable.
>
> https://github.com/WebAudio/web-audio-api/issues/385 suggests TypeError.
>

​TypeError is fine with me.​


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/611#issuecomment-146726567>
> .
>



-- 
Ray

**Comment by joeberkovitz** [comment]
TPAC 2015: resolve by reworking formula for linear to use min(dref, dmax) in place of dref, rather than throwing exceptions. When this term == dmax, the fraction will evaluate to 0/0 and can be taken by definition as 1.

Alternatively, use min(dref, dmax - EPSILON) (some small number) to avoid the division by zero.
