### ISSUE TITLE
Should BaseAudioContext really have a constructor?

### ISSUE THREAD

**Issue by foolip** [WebAudio/web-audio-api#748]
http://webaudio.github.io/web-audio-api/#BaseAudioContext

There's a `[Constructor(optional AudioContextOptions contextOptions)]` which seems strange, presumably only `AudioContext` and `OfflineAudioContext` should have constructors?

**Comment by foolip** [comment]
Oh, it looks like `AudioContext` doesn't even have a constructor in the spec now. Refactoring mishap? That constructor also needs to spell out which exceptions can be thrown and why.

**Comment by padenot** [comment]
A constructor is being added and spelled out in a PR, since there is the need to do some things internally when creating an `AudioContext` (like, transitioning from "suspended" to "running" when the audio starts flowing through the system). It needs some rebasing, this `BaseAudioContext` patch has landed in the meantime.

**Comment by foolip** [comment]
Can you link to those PRs? I can't see anything relevant recently committed.

**Comment by padenot** [comment]
Sorry, yes, #644.
