### ISSUE TITLE
Merge SpatialPannerNode back into PannerNode?

### ISSUE THREAD

**Issue by foolip** [WebAudio/web-audio-api#749]
With [PannerNode's `setVelocity` removed](https://github.com/WebAudio/web-audio-api/issues/730), `SpatialPannerNode` and `PannerNode` are identical except for how position and orientation are set.

According to @rtoy the intent is to eventually remove `PannerNode`, and this is what I would like to discuss. I took a quick look at Chrome, Edge, Firefox and Safari, and they all support `PannerNode`, although Safari's implementation is prefixed.

Chrome's [use counter data for `createPanner`](https://www.chromestatus.com/metrics/feature/timeline/popularity/644) shows usage around 0.008%, which while lower than some things that have been removed, is still high enough to cause *some* pain for web developers.

Is any implementor excited about removing `PannerNode`, and if so in what time frame?

Assuming no concrete plan to really remove `PannerNode`, how about just merging `SpatialPannerNode` into it? In other words, add the `positionX/Y/Z` and `orientationX/Y/Z` attributes to `PannerNode` and drop `SpatialPannerNode`.

It looks like the `setPosition` and `setOrientation` methods could be redefined in terms of those new attributes, doing the equivalent of this:
```JavaScript
PannerNode.prototype.setPosition = function(x, y, z) {
  var startTime = this.context.currentTime;
  this.positionX.setValueAtTime(x, startTime);
  this.positionY.setValueAtTime(y, startTime);
  this.positionZ.setValueAtTime(z, startTime);
};
```

Thoughts?

**Comment by rtoy** [comment]
This is acceptable to me.  We'd have to update AudioListener appropriately too, but the changes are similar to what we would do to PannerNode.

I would however, still want to deprecate and possibly remove (eventually) setPosition/setOrientation.  At this point, they're just convenience functions.

**Comment by foolip** [comment]
I guess the maintenance burden would be non-existent, but that you'd still like to alert web developers to the fact that using setPosition/setOrientation can give bad results? Warning against its use in the spec and emitting console messages would make sense, and if usage never drops to the point where they can be removed without incident, that still wouldn't be a terrible outcome.

**Comment by rtoy** [comment]
Yes, for Chrome, I think a deprecation message would be useful.

**Comment by foolip** [comment]
We have a bit of a problem with deprecation that don't turn into removals and the risk that this causes developers to take the messages less seriously, so now most deprecations come with a removal date. However, a console message that doesn't say "deprecated" or "will be removed" but something to the effect of "these might not do what you wanted, check out these new attributes" would be great.

If merging `SpatialPannerNode` back into `PannerNode` isn't met with objections, it sounds like a plan!

**Comment by rtoy** [comment]
I am in favor of this plan.  If we keep setOrientation/setPosition for the PannerNode (and the setters for the AudioListener), we maintain 100% backward compatibility.  Then it's an easy upgrade if the developer wants to do automation.

And as side effect, you can now query the PannerNode and AudioListener for position and orientation.  This wasn't possible before so you had to keep track of this yourself. Now you can just ask the node where it is.

**Comment by joeberkovitz** [comment]
I'm in favor of this. We would need to define the old methods in terms of changes/queries to the corresponding new AudioParams

**Comment by hoch** [comment]
I am also in favor of this - less clutter and noise in the spec. The polyfill can be written easily as well.

**Comment by rtoy** [comment]
To answer @billhofmann's questions, this is my best recollection of how we got SpatialPanner.

Panner can't do automations; a known fact.  A common operation is basic stereo panning with automation, and panner node seemed like overkill for that.  So, we get StereoPannerNode.  But we still need to fix PannerNode somehow.  Thus was born SpatialPannerNode to add automation.

Why we didn't think about merging before I don't know.  @cwilso wrote the spec for SpatialPanner and I remember reviewing the first cut.  Then I think we all forgot about it and Chris landed his changes not too long ago when we remembered we needed it in the spec since the PannerNode was deprecated. (Don't know why we haven't marked it as deprecated already.)

And after some reflection, I also like to keep setPosition. It's not sample accurate, but very convenient to make sure the coordinates are all changed at the same time.  It's not really any worse than having the .value setters for all of the existing AudioParams.

**Comment by billhofmann** [comment]
Understood.  I think my concerns are:


·         Providing multiple methods to achieve “kind of” the same thing on one interface is asking for confusion

·         If doing setPosition ~= value setter on an AudioParam, then I’d vote for getting rid of setPosition – otherwise we should add set<Value> all other places we’re using AudioParam, right? (OK, a bit of an extreme argument, but follows from the “one way to do things” point)

·         If we think that using AudioParam is really difficult, then we have a bigger problem

On the backwards compatibility side of this, that would argue for changing the name since we’re breaking the interface (if we remove setPosition), and more explicitly deprecating Panner (I note also that AudioListener is deprecated but hard to see from the headings).  Do we have any way of checking actual in the field usage of Panner?

-Bill

**Comment by cwilso** [comment]
well, we could just explicitly say setPosition/etc on AudioListener, too
are just the relevant AudioParam setValueAtTime(now, x).

**Comment by rtoy** [comment]
On Fri, Mar 11, 2016 at 3:29 PM, Bill Hofmann <notifications@github.com>
wrote:

> Understood. I think my concerns are:
>
>
> · Providing multiple methods to achieve “kind of” the same thing on one
> interface is asking for confusion
>
> · If doing setPosition ~= value setter on an AudioParam, then I’d vote for
> getting rid of setPosition – otherwise we should add set<Value> all other
> places we’re using AudioParam, right? (OK, a bit of an extreme argument,
> but follows from the “one way to do things” point)


​One difference.  With one AudioParam, you're just setting one variable.
When moving, you have to set 3.  If the three setters happen across a
rendering boundary (which is possible in chrome), the motion isn't what you
probably wanted.  Does it matter? Don't know.

This is an argument for keeping setPosition, but this is better solved by
using automation.  Except that since the automation is a-rate, it's pretty
expensive because you need the azimuth and elevation every sample.  That
calculation needs 15 timeline values (6 from the panner for position,
orientation, and 9 from the listener for position, forward, and up).


>
> · If we think that using AudioParam is really difficult, then we have a
> bigger problem
>
> On the backwards compatibility side of this, that would argue for changing
> the name since we’re breaking the interface (if we remove setPosition), and
> more explicitly deprecating Panner (I note also that AudioListener is
> deprecated but hard to see from


​AudioListener is deprecated because it goes with Panner and is not
compatible with SpatialPanner automation.
​


> the headings). Do we have any way of checking actual in the field usage of
> Panner?
>
>
​For the panner itself: ​
https://www.chromestatus.com/metrics/feature/timeline/popularity/644
​, roughly 0.0071% of all web pages.​


​To put the percentages in context, look at the percentages for
AudioContext:
https://www.chromestatus.com/metrics/feature/timeline/popularity/652,
roughly 0.18% of all web pages.


​



> -Bill
>
> From: rtoy [mailto:notifications@github.com]
> Sent: Friday, March 11, 2016 2:59 PM
> To: WebAudio/web-audio-api
> Cc: Hofmann, Bill
> Subject: Re: [web-audio-api] Merge SpatialPannerNode back into PannerNode?
> (#749)
>
>
> To answer @billhofmann<
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_billhofmann&d=CwMCaQ&c=lI8Zb6TzM3d1tX4iEu7bpg&r=qzKCNHFKJMzZBJ52at1DkA-_8TPxvcij-zS_VXs8c5A&m=LhUXRiN5u1F0kt55EO9QyVhEuBeIXBhoPtPIgkpebH0&s=etUFCSSEnCKTwttbrRTJkkhzg6ZU0K4s00k_DuGLrLY&e=>'s
> questions, this is my best recollection of how we got SpatialPanner.
>
> Panner can't do automations; a known fact. A common operation is basic
> stereo panning with automation, and panner node seemed like overkill for
> that. So, we get StereoPannerNode. But we still need to fix PannerNode
> somehow. Thus was born SpatialPannerNode to add automation.
>
> Why we didn't think about merging before I don't know. @cwilso<
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cwilso&d=CwMCaQ&c=lI8Zb6TzM3d1tX4iEu7bpg&r=qzKCNHFKJMzZBJ52at1DkA-_8TPxvcij-zS_VXs8c5A&m=LhUXRiN5u1F0kt55EO9QyVhEuBeIXBhoPtPIgkpebH0&s=jJWyD4qAGN1ajh4Z5kxVxaXZ39KL0VyfzRmiHLVP3LM&e=>
> wrote the spec for SpatialPanner and I remember reviewing the first cut.
> Then I think we all forgot about it and Chris landed his changes not too
> long ago when we remembered we needed it in the spec since the PannerNode
> was deprecated. (Don't know why we haven't marked it as deprecated
> already.)
>
> And after some reflection, I also like to keep setPosition. It's not
> sample accurate, but very convenient to make sure the coordinates are all
> changed at the same time. It's not really any worse than having the .value
> setters for all of the existing AudioParams.
>
> —
> Reply to this email directly or view it on GitHub<
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_WebAudio_web-2Daudio-2Dapi_issues_749-23issuecomment-2D195594978&d=CwMCaQ&c=lI8Zb6TzM3d1tX4iEu7bpg&r=qzKCNHFKJMzZBJ52at1DkA-_8TPxvcij-zS_VXs8c5A&m=LhUXRiN5u1F0kt55EO9QyVhEuBeIXBhoPtPIgkpebH0&s=WOCWMGfD6F3DhzrqXbKAZWhaTMjzx-jByvyOSFpKYqg&e=>.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/749#issuecomment-195602252>
> .
>



-- 
Ray

**Comment by padenot** [comment]
Resolution: merge back the `SpatialPannerNode` into the `PannerNode`.
