### ISSUE TITLE
(DeZippering): De-zippering is not defined

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#76]
> Originally reported on W3C Bugzilla [ISSUE-17339](https://www.w3.org/Bugs/Public/show_bug.cgi?id=17339) Tue, 05 Jun 2012 11:32:29 GMT
> Reported by Philip Jägenstedt
> Assigned to 

Audio-ISSUE-46 (DeZippering): De-zippering is not defined [Web Audio API]

http://www.w3.org/2011/audio/track/issues/46

Raised by: Philip Jägenstedt
On product: Web Audio API

https://dvcs.w3.org/hg/audio/raw-file/tip/webaudio/specification.html#AudioGainNode says:

"""The implementation must make gain changes to the audio stream smoothly, without introducing noticeable clicks or glitches. This process is called "de-zippering"."""

It needs to be defined in detail what this means.

**Comment by rtoy** [comment]
The dezippering algorithm used in blink and webkit (as given by @chrislo in https://github.com/WebAudio/web-audio-api/issues/76#issuecomment-27954865) has some issues.

The smoothing quantum is fixed (as is the snap threshold).  The formula is applied for each rendering quantum.  That means for contexts at high sample rates, the parameter approaches the final value in much less time than in a context with a slower sampling rate.

This is undesirable; the parameters should take the same amount of *time* to reach the same value, not the same number of rendering quanta.  The smoothing constant needs to be adjusted for the sample rate.  Let's say .05 is the time constant at 44.1 kHz and adjust it appropriately for other sample rates.

Also, the parameter can have very large or very small values, but the snap threshold is the same value, independent of the parameter.  This means that for parameter values less than .001, we always snap them to the final value.  That means no smoothing at all.  I can't think of any parameters now where the difference between .001 and 0 is significant, but it's not impossible where such changes would be audible for some (current or future) parameter.

**Comment by joeberkovitz** [comment]
@rtoy I agree with you, but the comment you are citing is sort of a red herring.

The resolved approach is here: http://www.w3.org/2013/12/19-audio-minutes.html#item02 and states that dezippering should be "essentially an alias to setTargetAtTime()" which implies some time constant that is independent of sample rate. We did not agree that there would be a snap threshold and I don't know if there is any good rationale for the conditional snapping; I haven't heard one advanced.

If we adopt the resolved approach then the current blink/webkit impl. will not be compliant with the spec (both because sample rate affects it, and also because of the snap threshold).

**Comment by rtoy** [comment]
On Tue, May 5, 2015 at 12:59 PM, Joe Berkovitz <notifications@github.com>
wrote:

> @rtoy <https://github.com/rtoy> I agree with you, but the comment you are
> citing is sort of a red herring.
>
> The resolved approach is here:
> http://www.w3.org/2013/12/19-audio-minutes.html#item02 and states that
> dezippering should be "essentially an alias to setTargetAtTime()" which
> implies some time constant that is independent of sample
>

​Ah, I had forgotten about that.  This is acceptable to me as long as we
note that k-rate parameter smoothing isn't exactly like setTargetAtTime
because the parameter is held constant.​


> rate. We did not agree that there would be a snap threshold and I don't
> know if there is any good rationale for the conditional snapping; I haven't
> heard one advanced.
>
​My best guess is that it allows the implementation to skip the smoothing
if the current value equals the target value.  In this day and age, I don't
think that optimization really matters anymore.​


> If we adopt the resolved approach then the current blink/webkit impl. will
> not be compliant with the spec (both because sample rate affects it, and
> also because of the snap threshold).
>

​I'm ok with that. I don't think the sample rate affects were too big since
most people are probably running 44.1 or 48 kHz.  The snap threshold
probably​ isn't needed because it's probably not audible for any parameter
we have.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/76#issuecomment-99203396>
> .
>



-- 
Ray

**Comment by joeberkovitz** [comment]
Note: we're agreeing that dezippering is equivalent to setTargetAtTime() although doesn't constitute an active scheduled automation element and so can't be cancelled.

**Comment by joeberkovitz** [comment]
After much painful review and dissection of various cases, we've reached the conclusion (for a second time, so help us) that dezippering requires special-casing and ad hoc distinctions that favor one use case over another.

We're going to remove the piece of the spec that describes dezippering, and instead be very clear that automation methods on AudioParam must be used to achieve smooth transitions in use cases where this is desirable.

**Comment by joeberkovitz** [comment]
Add informative note to spec that the recommended technique for de-zippering is to place successive calls to setTargetAtTime(context.currentTime, /* value */, /* time constant */). The spec will be clarified to communicate that the starting value for setTargetAtTime() is the current computed value at the start time, **not** the value of `.value`.

**Comment by joeberkovitz** [comment]
@padenot You already have a branch 76-remove-dezippering for this but no PR -- can you create the PR for your branch please? (I created my own completely separate resolution of this issue bc I didn't realize you'd done that)

**Comment by padenot** [comment]
@joeberkovitz, it's been opened since the 4th of November last year.

**Comment by joeberkovitz** [comment]
@padenot any reason not to merge it at this point?

**Comment by padenot** [comment]
No reason, I'll do that now.

**Comment by sidewayss** [comment]
FYI - I just received the deprecation notice for this change in the Chrome Dev Tools Console M63.
**As of M64, January 2018, GainNode.gain.value is no longer valid.**

As someone who is arriving here fresh from the deprecation notice, here is my translation/consolidation of the information I have gleaned from the various links presented to me.  Hopefully this will save some time/energy for other newbies.
1) De-Zippering is another word for smooth fades between gain values.  It's useful in digital audio because sudden changes might cause pops or clicks.
2) The W3C decided that browsers should no longer provide default de-zippering for javascript, and developers must henceforth specify a smooth fade via [AudioParam.setTargetAtTime](https://developer.mozilla.org/en-US/docs/Web/API/AudioParam/setTargetAtTime) or a sudden change of value (not smooth) via [setValueAtTime](https://developer.mozilla.org/en-US/docs/Web/API/AudioParam/setValueAtTime).
3) There is also [SetValueCurveAtTime](https://developer.mozilla.org/en-US/docs/Web/API/AudioParam/setValueCurveAtTime), which creates more sophisticated fades, based on an array of values.
4) It seems that SetValueAtTime is generally less desirable due to the possibility for clicks and pops.

Finally: This seems to be exclusive to GainNodes, though I can see how it might apply to other types of web audio nodes.  Can someone on this thread clarify that point?  The discussion here so far is ambiguous.

**Comment by cwilso** [comment]
You are essentially correct.  The only important thing is that this isn't just about GainNodes - in fact, if it were only about gain, leaving the smoothing in would probably be best.  

1. De-zippering is another word for smoothing between subsequent values in an AudioParam (it's not just gain values, but any AudioParam - in fact, the worst problems with built-in zippering were with smoothing of frequency values, which caused portamento-like "pitch glide" effects).  De-zippering is just avoiding the "stair-stepping" between values set only occasionally, by using the audio param scheduler to make changes at audio rate.
2. Yes, if you want a sudden change of value (or don't really care), use setValueAtTime.  If you want to smooth values, setTargetAtTime is probably easiest to use.
3. setValueCurveAtTime probably isn't the best replacement - it can be used, but it's a lot more complex, and probably not necessary.
4. setValueAtTime won't give you pops and clicks in many scenarios - for example, in setting frequency values on an oscillator, it's probably the right thing to do.  For gain, yes, you probably want to use setTargetAtTime - for delayTime on a delay node, you definitely want to use setTargetAtTime, because unsmoothed values WILL cause pops and clicks.

For most changes you can probably just use something like setTargetAtTime( value, 0.01 ) and it will smooth well enough.

**Comment by sidewayss** [comment]
Thanks for the detailed explanations.
But is this Chrome M64 deprecation and subsequent removal of a feature only for GainNode.gain.value?  Or is this not a Chrome-specific thread?  I'm trying to clarify the current implementation(s) too.  Seems like I should change all my .value settings to use setXxxAtTime.  Does this apply to other properties than .value?  I get the impression that your list of scenarios is incomplete.

Personally, I'm not doing much with web audio beyond simple mixing - no f/x.  I'm going to assume that your "For most changes" suggestion covers all my needs.  But I'm curious if there is any kind of general rule as to when/where this applies, versus a list of disconnected circumstances.  I saw some detail in one of your comments earlier in this thread, but I'm not up on all the math involved.

**Comment by cwilso** [comment]
IIRC, Mozilla never implemented de-zippering.  Chrome (and all other Webkit- and Blink-derived browsers) did de-zippering EVERYWHERE (i.e. on all AudioParams).  The deprecation in Chrome will make it so that all AudioParams will not automatically smooth, and thus be compatible with Firefox.

The problem is that some parameters should NOT be smoothed automatically - an OscillatorNode's frequency.value, for example, as I stated before -  but some arguably *should* be smoothed (e.g. delayTime on a DelayNode - where almost any change would result in pops and clicks as it would cause a discontinuous jump in the waveform).  The Working Group looked through this, and decided it was better not to apply "magic" here; that is, to just put it in the hands of developers.  There's no "general rule", per se - just have to think through how smoothing would affect things, and if it's necessary to avoid discontinuous jumps in the output.

Realistically, if all you're doing is something like offering a slider that is linked to a GainNode's .value, you're _probably_ not going to hear any zippering anyway.  But it's safer, for Gain, to use a setTargetAtTime to avoid any possibility.

**Comment by cwilso** [comment]
Oops, meant to also say - if you were going to hear clicks, you'd already be hearing them in Firefox, since they never implemented de-zippering.

**Comment by sidewayss** [comment]
Thanks again for the detailed info.  The delay time example now makes perfect sense to me, no math required.  This is yet another time when I'm glad my web audio manipulation is simple so far.  It's a lot of moving parts when you get into the full feature set, a lot of details to think through.

**Comment by joeberkovitz** [comment]
@sidewayss `GainNode.gain.value` is valid, it's just that it does not do dezippering any more. (This applies to all `value` setters for all `AudioParams`, not just GainNode.) The deprecation message is not clearly worded.

When called as a setter, the spec states that `value` is identical to `setValueAtTime(value, context.currentTime)`. See: https://webaudio.github.io/web-audio-api/#dom-audioparam-value

**Comment by rtoy** [comment]
As the author of the message, it says `GainNode` because you used a `GainNode`.  If you had used a different node, it would mention the node.  We thought it would be better to specify the node that was affected rather than be generic and leaving it up to you to figure out which of the zillion nodes in the graph were affected by this.

**Comment by sidewayss** [comment]
OK, I'm going to modify my code regardless, if for no other reason than to avoid extraneous, brightly colored console messages.  Yes, the deprecation message is muddily worded and the links/sub-links, including this thread, don't provide clear info.  That's the entire reason I posted originally on this thread, to both receive and provide clarity.  Thanks for providing some additional clarity. @joeberkovitz and @rtoy.

Yes, I figured that the deprecation message might be using my code to customize the message, but that was part of the reason I needed further clarity, especially after reading all the info in the trail of links from that message, including this issue thread.  This probably isn't the best place to clarify all this info, but it's better than nowhere, and at least I personally am now properly informed :-)

**Comment by sidewayss** [comment]
@rtoy - I could consolidate the relevant text from this thread into a few paragraphs if you would like to post that someplace and link to it in the deprecation message.  I am a programmer who doesn't mind doing documentation, especially if I learn something in the process, as I have here.  I am always glad to save someone else the trouble I have gone through to figure out something new.
Otherwise you might link to the numbered comments by myself and @cwilso in this thread, which have some consolidated info, and below which follow these additional comments and clarifications.

**Comment by sidewayss** [comment]
...and won't there be a post deprecation "this has already changed" message?  Or will there not be one because of the fact that AudioParam.value still works, it just doesn't de-zipper?  That would be the worst!  To have older, production code, then only stumble on this problem after M64 via clicks and pops or other just glitches, because it's still legal, and the deprecation period has passed.
I have not been away from this code in Chrome for more than a few weeks, so this deprecation message only appeared in M63, AFAICT.  Not much of a window of opportunity for deprecation.

**Comment by rtoy** [comment]
We can certainly postpone the removal. The main reason for the relatively short time frame is that Firefox never implemented de-zippering.

But there's also another side-effect of this change.  The value setter becomes _exactly_ the same as `setValueAtTime`.  This means that if already had an automation running, you may get errors because you can't call that in the middle of a `setValueCurveAtTime` automation.  Internal stats show that this doesn't really ever happen, fortunately.

**Comment by sidewayss** [comment]
I agree that it's a limited audience, a limited codebase that is affected by this.  The glitch is: This is not a full-on feature deprecation, where the old feature becomes illegal.  It's a sub-feature deprecation within the feature.  So post-deprecation looks identical to pre-deprecation-notice to the programmer, unless there are audio glitches.
I'm the lowest person on this thread's totem pole in terms of any decision, but if you're asking for my input: I would not delay the actual deprecation, but I would keep the deprecation message for a while, so those programmers have more time to catch it and understand the implications prior to user complaints about audio glitches.  Just change the words in the M64 message to reflect that the change has already occurred.

**Comment by rtoy** [comment]
This is no longer about the spec.  So if there are additional comments, please file a bug at crbug.com/new and we can continue the discussion there.  That being said, the message links to https://www.chromestatus.com/features/5287995770929152, and I can update that to provide a bit more detail.

As far as the spec is concerned, this is a done deal and there's we're not going to change this.  Chrome was just slow in removing the dezippering.
