### ISSUE TITLE
DynamicsCompressor reduction attribute is float or AudioParam?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#761]
Currently the spec says the DynamicCompressorNode.reduction is a read-only float.

Chrome and Safari implemented this as an AudioParam.  I'm assuming it's always been this way.   However, Firefox implements it as a read-only float.

Just want clarification that we really want a float and not and AudioParam.  I don't have any use-case where I want reduction to be an AudioParam.

**Comment by hoch** [comment]
The gain reduction is the result of compression (based on ratio, threshold and envelop following) - so that's not something you can directly manipulate. We should make it as float.

Only 'probable' use case would be: making AudioParam to produce output and connect it to the other audio nodes, so the gain reduction can be used to control other nodes' AudioParams. However, we are not there yet.

**Comment by RByers** [comment]
The MDN [docs](https://developer.mozilla.org/en-US/docs/Web/API/DynamicsCompressorNode) and sample code show `reduction` as an AudioParam.  Is MDN really out of date with the Firefox implementation?

**Comment by padenot** [comment]
Yeah, I'm changing that right now, that's a mistake, we made the
AudioParam -> float transition a while back.

**Comment by rtoy** [comment]
Closing this.  We made this change in PR #404 to fix issue #243.

I had completely forgotten about that.
