### ISSUE TITLE
Exposing buffers between audio worklet and context

### ISSUE THREAD

**Issue by svgeesus** [WebAudio/web-audio-api#784]
Raised by Norbert Schnell at WAC2016

**Comment by taisel** [comment]
Has sharedarraybuffer been discussed for Web Audio?
I'd imagine it *should* be a prerequisite so support for user-driven buffer sharing can manage a lot of limitations.

https://tc39.github.io/ecmascript_sharedmem/shmem.html

**Comment by hoch** [comment]
AudioWorkletProcessor processes the audio sample array from the other audio nodes. Why do you need shared-array buffer? Do you want synchronous communication between main - audio threads? The notion of "blocking synchronization" might not work well with Web Audio API implementation because we never block the audio thread for anything.

I do also want to have some clarification on this original issue. postMessage()/onmessage is not good enough for this purpose?

**Comment by taisel** [comment]
Lockless ring buffer queues are possible with sharedarraybuffer. I already use it in a project to pipe audio from a webworker to main thread.

**Comment by taisel** [comment]
postMeesage also has a latency/overhead that I'm trying to avoid.

**Comment by taisel** [comment]
With a synthesis script and an audio worker both laying in separate webworkers, one can avoid pushing a pcm stream thread main thread avoiding UI blocking all together if one uses sharedarraybuffer using such a construct.

**Comment by hoch** [comment]
> Lockless ring buffer queues are possible with sharedarraybuffer. I already use it in a project to pipe audio from a webworker to main thread.

@taisel This is exactly what AudioWorklet does. We are adding the feature to the spec, so you do not have to this. Another FIFO means another latency. Not sure if we're willing to take that path.

I believe you're asking 'synchronous communication' between worklet instances via shared array buffer. This needs to go up to the design of Worklet infrastructure and should be discussed there first.

**Comment by taisel** [comment]
@hoch Asynchronous streaming of audio samples generated on the fly within JavaScript from within another webworker. No intermediate audio graph nodes to contain the data prior to writing to output buffer in the target audio worker.

**Comment by taisel** [comment]
Perhaps linking the use case as is will provide context:
Where we write into a SharedArrayBuffer from a webworker - https://github.com/taisel/IodineGBA/blob/master/IodineGBA/core/Worker.js#L173

Where we read available samples on the main thread to pass to a scriptprocessornode eventually: https://github.com/taisel/IodineGBA/blob/master/user_scripts/WorkerGlueCode.js#L215

**Comment by taisel** [comment]
Internally there's a bunch of intermediate code being rewritten so as to support a proper AudioWorker to pipe to, rather than pipe to main thread (Unless fallback).

**Comment by hoch** [comment]
@taisel The primary goal of AudioWorklet is to support sample-accurate/synchronous audio processing in JavaScript along with built-in audio nodes. It seems like you want to have a 'back-channel' between worklet instances and the other worker, I still believe this is a much broader design problem that needs to be addressed at the level of Worklet/Worklet interaction.

Two questions:
1. Have you talked to anyone who works on Worklet/Worklet infrastructure before?
2. What is stopping you from using SharedArrayBuffer in conjunction with AudioWorklet?

**Comment by josh83abc** [comment]
**Very interesting topic! I clearly see a big limitation if it is not possible to access a SharedArrayBuffer from an AudioWorklet! I will give you clear examples**

But first let me tell you more about what I'm doing : I'm working on a popular DJ app and I'm currently converting the audio engine from Flash to HTML5.

In Flash, all the audio is generated inside a single audio loop, the equivalent of ScriptProcessorNode BUT with no input. Also all the song PCM data is stored in a big array in the memory. 

Therefore, inside a single audio loop (equivalent of onaudioprocess), we can pick as much as audio data from the song we need and from any position in the song. This is required for lot of effects (scratch, beatsync, sample-accurate loops...). Indeed it is not unusual to seek the position of the song in the middle of an audio loop. The typical audio loop size we used is 4096 samples.

Another example is a classic"resampler" which allows to change the speed of the music. Here is an example https://iwebdj.com/pitch.html. At each audio loop, it takes "blocksize * playback_rate" samples to output "blocksize" samples.

As you can see, such application works well with the ScriptProcessor which can have pick any PCM data from the song, since all PCM data stored in a big Float32Array.

**HOWEVER, as far I understand, this won't be possible with the AudioWorklet right?** Because this requires that the AudioWorklet would have access to the song PCM data (stored in a big SharedArrayBuffer I guess). Since postMessage is asynchronous, it is useless for accessing audio data on the fly. 

I'm also concerned since AudioWorklet is intended to replace ScriptProcessor entirely at one point. Or maybe I'm missing something.... I'm still pretty new to WebAudio :)

I would love to have you opinion @hoch !! :)

**Comment by padenot** [comment]
The discussion here is outdated. It will be possible to use `SharedArrayBuffer` with an `AudioWorklet`. I suggest we close this.

**Comment by hoch** [comment]
As @padenot commented, the MessagePort in AudioWorkletNode/AudioWorkletProcessor is supposed to support "transferable". So using SAB shouldn't be a problem. Note that the burden of implementing a ring buffer with SAB underneath is on to developers.

**Comment by josh83abc** [comment]
Thanks @padenot and @hoch for the reply!! It is a great news that ShareArrayBuffers will be accessible inside the AudioWorkletProcessor! I assume I'm not the only one who needs to access various audio buffers (other that the input buffer) inside the AudioWorklet/ScriptProcessor. 
Keep up the good work! :)

**Comment by joeberkovitz** [comment]
Shouldn't be an issue since we can serialize SABs between main and audio thread. Closing.

**Comment by unicomp21** [comment]
@joeberkovitz what's the workaround?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer

**Comment by rtoy** [comment]
I believe the answer as of right now is that there is no workaround.

**Comment by joeberkovitz** [comment]
The impact of losing SAB functionality impacts the use of lots of features and APIs across the Web Platform. It's regrettable and I think we're all waiting to see what best practices and solutions emerge in light of the vulnerabilities that have been exposed. Hopefully SAB will re-emerge since it's a globally useful thing.

**Comment by karlt** [comment]
I wonder whether it is possible to create a MessageChannel and pass one MessagePort to the worklet and the other to the webworker.  Messages would be copied, which is not as efficient as a shared buffer, but at least the main thread is no longer involved, once worker and worklet each have a MessagePort.

**Comment by joshontheweb** [comment]
@karlt In some early tests, this appears to work.  In fact, you don't even need to create a new message channel necessarily.  I was able to pass the audio worklets default main thread facing port as a transferable to a web worker and receive the data properly.

**Comment by hoch** [comment]
Yes. A port pair in AWN/AWP was derived from the same MessageChannel object. So transferring a port to the other scope is a valid operation. That was our intention when we added MessagePort and you can find the discussion somewhere here.

**Comment by josh83abc** [comment]
I'm trying to use access to a SAB inside a AudioWorklet but it doesnt work :/, is it normal?

SAB works fine with WebWorkers, I just send the SAB reference to the Worker with postMessage.
But when I do the same with AudioWorklet (I send the SAB reference to the AudioWorklet via postMessage), I get "null" in the AudioWorklet.

Main thread side : audioworklet.port.postMessage(new SharedBufferArray(20));
AudioWorklet side : this.port.onmessage = function(e) { console.log(e.data); }  // output "null"

My app is music player and the SAB contains the music track audio data (can be up to 100MB). The AudioWorklet generate all the output and therefore needs to have access to the whole music track data.  

I'm using the production Chrome 64.0, the canary build crashes on my computer.

Thanks a lot! :)

**Comment by mark-buer** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer

> Note that SharedArrayBuffer was disabled by default in all major browsers on 5 January, 2018 in response to Spectre.

**Comment by hoch** [comment]
@josh83abc Also this is not a support forum, so please consider filing [a bug against the browser](crbug.com).

**Comment by josh83abc** [comment]
@mark-buer, I'm aware that SAB are temporaly disabled in browsers because of Spectre, but I have the SAB flags manually enabled in Chrome. It works for Webworkers, but not for AudioWorklets.
 
@hoch, I just want to know if accessing SAB from AudioWorklets should work today (= if you have implemented it)? if yes, then it must be a bug...

**Comment by hoch** [comment]
Yes, examples like [audiotool](https://www.audiotool.com/board/news/chrome_audioworklet) uses SharedArrayBuffer with AudioWorklet AFAIK.

**Comment by josh83abc** [comment]
Ok very good! Thanks @hoch :). I just needed your confirmation because I thought that maybe you removed the SAB at the last minute of the recent security issues (Spectre...).
Yes I see that audiotool use SAB + AudioWorklet in their project but they don't necessarily use the SAB inside the AudioWorklet processor.
I will see if it works with Chrome canary and if not I will fill a bug report :)

**Comment by josh83abc** [comment]
I just tested on Chrome Canary (v66), the bug is fixed, sending a SharedArrayBuffer reference from the main thread to the AudioWorkletProcessor via postMessage works now :)
