### ISSUE TITLE
State of access to multichannel audio devices

### ISSUE THREAD

**Issue by svgeesus** [WebAudio/web-audio-api#787]
Several related issues. Needs more discussion.

**Comment by padenot** [comment]
It's unclear what is needed here. There is already some support: `AudioDestinationNode.maxChannelCount`, that allow authors to determine the number of channels on the device.

**Comment by joeberkovitz** [comment]
@svgeesus Can you clarify what this issue is? Otherwise let's close it.

**Comment by bjornm** [comment]
Is this issue regarding multi-channel audio input devices? If it is, +1 :) 

Maybe that falls under getUserMedia() rather than web audio, but it would be really useful to query available input devices for channel counts (enumerateDevices) and then add a channel map as an optional constraint to getUserMedia() where you could specify exactly which input channels you want to receive. This could of course be 1, 2 or any number of simultaneous input channels.

**Comment by padenot** [comment]
The Web Audio API does not deal with input devices. Devices are interacted with using `navigator.mediaDevices`.

**Comment by bjornm** [comment]
Sounds good.

**Comment by hoch** [comment]
One reference point: https://www.w3.org/TR/2015/WD-audio-output-20150210/#h-webaudio-extensions

Not sure if this is still under the development though.

**Comment by padenot** [comment]
It's not, see https://github.com/w3c/mediacapture-output/issues/46

**Comment by joeberkovitz** [comment]
Not clear what this represents -- other groups are dealing with input devices. Closing.
