### ISSUE TITLE
OscillatorNode.frequency parameter nominal range for negative values.

### ISSUE THREAD

**Issue by g200kg** [WebAudio/web-audio-api#813]
If the AudioParam values are finally clamped to the nominal range,
OscillatorNode.frequency parameter range should be extended to negative values.
Current nominal range is [0, Nyquist frequency], but in FM use case, modulation from other OSC should be effective for negative values.

**Comment by hoch** [comment]
So is this question about querying the frequency from an oscillator? The negative frequency of a carrier oscillator by FM modulation has not been exposed to JS and I don't think it ever will be. (i.e. you cannot poll frequency.value to observe the instantaneous frequency.)

@padenot However, I think we forgot to catch the spec change here:
http://webaudio.github.io/web-audio-api/#the-oscillatornode-interface

If the computed frequency is limited by [-fs/2, fs/2], we might not be able to do FM synthesis correctly because harmonic components above Fs/2 will not be wrapped around. I believe The computed frequency should be unbound.

**Comment by rtoy** [comment]
On the other hand, allowing computed frequency go above Nyquist breaks the band-limited requirement of the oscillator.  You can't have it both ways.

**Comment by g200kg** [comment]
Thank you, I see about nominal range of computed value. 
In one more use case of negative frequency, it is convenient to generate inverted sawtooth for LFO.
Should I use additional gain node to invert waveform?

**Comment by hoch** [comment]
@rtoy and I discussed the use case (phase inversion) of negative frequency, but it might introduce some undefined behaviors for a custom oscillator. I am fine with allowing the negative frequency, but this needs to be discussed here first.

**Comment by rtoy** [comment]
And to be clear, it's not undefined behavior for a custom oscillator.  Let's just say that it won't necessarily be the inverse because you have both cos and sin terms.  I think you will get the negative but with a non-zero delay.  I'd have to do the math to make sure.

**Comment by g200kg** [comment]
Either way, the custom oscillator's instantaneous frequency easily goes negative by modulation because the nominal range of ComputedValue is [-fs/2, fs/2].

**Comment by rtoy** [comment]
From an implementation viewpoint, it's simpler if the osc.frequency AudioParam limits were [-fs/2, fs/2].  Then there's no need to have special case code that only handles the oscillator frequency param for the computed value. 

But simplicity of implementation should not be the driving factor. :-)  Consistency and utility are far more important.

**Comment by mdjp** [comment]
Agreed that OscillatorNode.frequency parameter range should be extended to negative values. Move to V1.

**Comment by padenot** [comment]
Agreed. Patch coming up.
