### ISSUE TITLE
AudioContext.baseLatency == graph latency?

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#823]
This is current definition of `baseLatency` in the spec:

> This represents the number of seconds of processing latency incurred by the AudioContext in handling audio through the graph.

I thought we agreed this only can be done by shooting an impulse to the audio graph and analyzing the result. In short, this is not practically feasible within a real-time audio context. Of course you can provide some sorts of _estimation_, but that does not go further than throwing a random number from my perspective. Note the spec does not say this is an _estimation_.

What are we trying to achieve with this `baseLatency` here? Isn't this about providing a batch callback size from the audio hardware? (i.e. FIFO buffer size after AudioDestinationNode)

**Comment by padenot** [comment]
I agree with @hoch, here, the prose is weird.

The system output latency is something that is available from the system, usually, and is very useful.

The graph latency is not something that is easily computable other than by trying to shoot an impulse, as @hoch says.

The latency added by an Web Audio API implementation that is not running directly off a system audio callback can be folded in this number I suppose. From my perspective as a Web Audio API developer, this is all system overhead. This can be some buffering added for cross-process transfer of audio buffer (for example, because of sandboxing), or some other buffering.

**Comment by rtoy** [comment]
Yeah, the text is wrong.  The example computation does reflect the buffering and is not the audio graph latency.  Also, in Chrome's implementation, this is related to the latency of an event.  If a keypress could be handled instantaneously, there would still be a delay before the action gets played because many rendering quanta could have already been computed, so the event doesn't go out until later after all of the already rendered audio has been played.

Not sure what we should say here.

**Comment by padenot** [comment]
@pozdnyakov, do you agree ?

**Comment by pozdnyakov** [comment]
I also agree with @hoch It is not quite clear how to estimate graph latency, especially before context starts processing the audio.

**Comment by rtoy** [comment]
It was never intended to be the graph latency because we all know that's really hard to determine.  Just bad phrasing---I'll try to fix it up shortly.
