### ISSUE TITLE
AudioWorkletProcessor should extend EventTarget if 'message' events can be dispatched to it

### ISSUE THREAD

**Issue by smaug----** [WebAudio/web-audio-api#937]
Currently it is very much underdefined how AudioWorkletProcessor.onmessage is supposed to behave.
 AudioWorkletProcessor.postMessage sends some data which onmessage is supposed to get, but since onmessage is type EventHandler, something somewhere is supposed to dispatch an event, probably 'message' event using MessageEvent interface.

**Comment by smaug----** [comment]
or, since AudioWorkletProcessor is apparently something JS is supposed to extend, it needs to be defined somehow that onmessage is something which is called when event is dispatched.
... this all is very unclear still in the spec.

**Comment by hoch** [comment]
Yes, the current PR is not clear about the behavior of message passing. It vaguely mentions that it is similar to how Worker behaves, but it is not true. (That part came from the previous AudioWorker spec proposal)

This is partly because of the infancy of Worklet spec work. Note that the message passing in Worklet is not considered or defined yet. Also please take a look at my alternative idea is to ditch the conventional message passing. (#936)

**Comment by hoch** [comment]
Let me revisit this since we decided to throw away the alternative design in #936.

We might have to invent the notation for the messaging system in AudioWorklet. There is an implicit association between a pair of instances of AudioWorkletNode and AudioWorkletProcessor that are created by a single constructor call. Therefore,

`AudioWorkletNode_A.postMessage()` will be routed to `AudioWorkletProcessor_A.onmessage`, and `AudioWorkletProcessor_A.postMessage()' will go to `AudioWorkletNode_A.onmessage()`.

The IDL notation for this messaging relationship is yet to be written, so please feel free to suggest ideas if you have any.

**Comment by hoch** [comment]
Fixed by #963.
