### ISSUE TITLE
[TAG] None of the audio worklet stuff actually has normative spec text

### ISSUE THREAD

**Issue by domenic** [WebAudio/web-audio-api#951]
In particular, the definitions for registerProcessor and postMessage do not actually contain the algorithm used. They seem to contain some non-normative description of behavior that is desired in the table describing their parameters, but this is not very useful.

See the algorithm for https://drafts.css-houdini.org/css-paint-api-1/#registering-custom-paint or https://w3c.github.io/ServiceWorker/spec/service_worker/index.html#service-worker-postmessage for what should be specified here

EDIT: I guess the AudioWorkletNode constructor has normative spec text, but it currently doesn't do anything useful; see #952.

**Comment by hoch** [comment]
I submitted the [PR](https://github.com/WebAudio/web-audio-api/pull/945/files) for the registration process. See [here](https://hoch.github.io/web-audio-api/#AudioWorkletGlobalScope) for the preview. If this is acceptable, I can expand AudioWorkletNode instantiation process as well.

And for the messaging, I am discussing the solution with @bfgeek at the moment. We might propose something new instead of using Worker's `postMessage()`.

**Comment by joeberkovitz** [comment]
@hoch what is the need for a solution that goes beyond documenting `postMessage()` in the normative fashion that @domenic suggested?

**Comment by hoch** [comment]
@joeberkovitz 

We should discuss it as a separate issue. We believe postMessage() is simply too big and redundant for our purpose. We also don't want to be throwing an object (not string or value) tied to the main thread to the rendering thread. The current postMessage() allows this AFAIK.

This has nothing to do with the normative text. That work is being done at the moment.

**Comment by hoch** [comment]
Fixed by #945 and #976.

The `postMessage()` communication still needs a normative description.

**Comment by joeberkovitz** [comment]
We're not going to have postMessage any more so this is done.
