### ISSUE TITLE
Derive tail time from input connection status in AudioWorkletNode

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#970]
As noted in https://github.com/WebAudio/web-audio-api/pull/959#discussion_r77810324, we need to have a way of telling the AudioWorkletNode if there are any inputs connected.  Without this, any tail time processing for the node can't be implemented correctly.

I can see this being indicated in at least two ways.  As @joeberkovitz mentions, we can have `contextInfo.connected`.  Or maybe `process(null, outputs)`; that is, instead of an input array, we pass in `null`.

**Comment by padenot** [comment]
I find the style of the second solution better. How about passing in an empty array instead of `null` so that code that iterate will not break? I suspec that this will be the common case.

In addition, I think having an argument list that having monomorphic parameters is also going to be better for JITs but I'm not a specialist.

**Comment by joeberkovitz** [comment]
I like the empty-array concept better than both my proposal and `process(null, outputs)`. It is good to do something that can be safely ignored by simplistic code when the implementor doesn't care.

One question: should this be an array of empty arrays, instead of an empty array? What if `process()` was written to expect a certain minimum number of channels?

**Comment by padenot** [comment]
I meant an array that has the same structure as before, but empty. So I'd say, [[],[]] for a stereo input, for example. Maybe we're being over-cautious here.

**Comment by joeberkovitz** [comment]
That is less likely to fail than passing in `[]`, which seems good. There is one minor downside I see: if the implementor wants to see if the node has no connected inputs, they would now have to check `inputs[0].length` instead of `inputs.length`.

This is part of why I arrived at `contextInfo.connected` - it dodged this issue, although it's less attractive conceptually.

**Comment by joeberkovitz** [comment]
This is addressed by #959 (still in review)

**Comment by rtoy** [comment]
Can someone write down what the actual conclusion is here?  That would be really helpful to know when reviewing #1009.

**Comment by joeberkovitz** [comment]
Sorry, I thought the conclusion had been documented adequately in #1009.

We concluded that we should use empty arrays to indicate disconnection of an input. What we did not decide (but #1009 proposes) was what level of the 3-deep nested arrays the "emptiness" should occur on.

**Comment by rtoy** [comment]
I meant that this issue should state the conclusion first. Then reviewers can verify that #1009 satisfies the conclusion.  #1009 had a conclusion but without a definitive answer here, it was kind of hard to tell if #1009 was doing the right thing.

**Comment by joeberkovitz** [comment]
Sorry, I'll be more careful to document things in the issue first next time.
